<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Administrace: Systémové nastavení";

    // Table header
    $lang['header_system_menu'] =  "Systémové nastavení";
    $lang['header_charts'] =  "Grafy";
    $lang['header_reminders'] =  "Expirace Cache & Upomínky karantény";
    $lang['header_authentication'] =  "Prokázání identity";
    $lang['header_virus_info'] =  "Informace o virech";
    $lang['header_display'] =  "Vzhled";
    $lang['header_paths'] =  "Cesty & Porty";
    $lang['header_bandwidth'] =  "Účtování kontektivity";
    $lang['header_stats_reporting'] =  "Site Statistics Reporting";

    // Text labels
    $lang['text_yes'] =  "Ano";
    $lang['text_no'] =  "Ne";
    $lang['text_accept'] =  "Přijaté";
    $lang['text_reject'] =  "Odmítnuté";
    $lang['text_enable_user_autocreation'] =  "Povolit automatické vytváření uživatelských účtů?";
    $lang['text_internal_auth'] =  "Automaticky přidělit hesla novým účtům?";
    $lang['text_enable_false_negative_management'] =  "Povolit sledování false negatives?";
    $lang['text_enable_stats_tracking'] =  "Povolit sledování statistik?";
    $lang['text_enable_virus_scanning'] =  "Povolit anti-virovou ochranu?";
    $lang['text_enable_spam_filtering'] =  "Povolit filtrovaní spamů?";
    $lang['text_enable_banned_files_checking'] =  "Povolit kontrolu zakázaných příloh e-mailů?";
    $lang['text_enable_bad_header_checking'] =  "Povolit kontrolů neplatných hlaviček e-mailů?";
    $lang['text_enable_spamtraps'] =  "Povolit spam-trap účty?";
    $lang['text_enable_charts'] =  "Povolit generování grafů?";
    $lang['text_enable_address_linking'] =  "Povolit uživatelům přidružení e-mailové adresy k jejich účtu?";
    $lang['text_enable_username_changes'] =  "Povolit uživatelům měnit si jejich přihlašovací jména?";
    $lang['text_enable_privacy_invasion'] =  "Povolit administrátorům číst e-maily uživatelů?";
    $lang['text_system_default_user_is_local'] =  "Should the System Default user (@.) only catch mail for local recipients?";
    $lang['text_user_virus_scanning'] =  "Povolit uživatelům zapnutí/vypnutí anti-viru?";
    $lang['text_user_spam_filtering'] =  "Povolit uživatelům zapnutí/vypnutí filtrování spamu?";
    $lang['text_user_banned_files_checking'] =  "Povolit uživatelům zapnutí/vypnutí kontroly zakázaných příloh?";
    $lang['text_user_bad_header_checking'] =  "Povolit uživatelům zapnutí/vypnutí kontroly hlaviček e-mailů?";
    $lang['text_size_limit'] =  "Velikostni limit e-mailu (bytes):";
    $lang['text_oversize_policy'] =  "E-maily přesahující povolenou velikost by měly být...";
    $lang['text_admin_email'] =  "E-mailová adresa administrátora:";
    $lang['text_smtp_server'] =  "Downstream SMTP server (MTA-TX):";
    $lang['text_smtp_port'] =  "Downstream SMTP - číslo portu:";
    $lang['text_key_file'] =  "Soubor obsahující šifrovací klíč (volitelné):";
    $lang['text_newuser_template_file'] =  "Template e-mailu zasílaného novým uživatelům:";
    $lang['text_chart_ham_colour'] =  "Barva pro zobrazení potvrzených non-spam:";
    $lang['text_chart_spam_colour'] =  "Barva pro zobrazení potvrzených spamů:";
    $lang['text_chart_virus_colour'] =  "Barva pro zobrazení virů:";
    $lang['text_chart_fp_colour'] =  "Barva pro zobrazení false positives:";
    $lang['text_chart_fn_colour'] =  "Barva pro zobrazení false negatives:";
    $lang['text_chart_suspected_ham_colour'] =  "Barva pro zobrazení nepotvrzených non-spam:";
    $lang['text_chart_suspected_spam_colour'] =  "Barva pro zobrazení podezřelých na spam:";
    $lang['text_chart_wl_colour'] =  "Barva pro zobrazení whitelisted položek:";
    $lang['text_chart_bl_colour'] =  "Barva pro zobrazení blacklisted položek:";
    $lang['text_chart_background_colour'] =  "Barva pozadí grafu:";
    $lang['text_chart_font_colour'] =  "Barva fontů v grafu:";
    $lang['text_chart_autogeneration_interval'] =  "Interval automatického generovaní grafů (v minutách):";
    $lang['text_expiry_period'] =  "Expirační doba pro e-mail v karanténě (dní):";
    $lang['text_ham_cache_expiry_period'] =  "Expirační doba pro non-spam v cache (dní):";
    $lang['text_reminder_threshold_count'] =  "E-mail reminder threshold (items):";
    $lang['text_reminder_threshold_size'] =  "E-mail reminder threshold (size):";
    $lang['text_reminder_template_file'] =  "E-mail reminder template file:";
    $lang['text_reminder_login_url'] =  "URL pro přihlášení do Maia pro e-mailové upomínky:";
    $lang['text_banner_title'] =  "Titulek stránky:";
    $lang['text_use_icons'] =  "Zobrazit ikony v nástrojové liště?";
    $lang['text_use_logo'] =  "Zobrazit logo v horní části stránky?";
    $lang['text_logo_file'] =  "Obrázek [soubor] loga:";
    $lang['text_logo_alt_text'] =  "Alternativní text pro obrázek loga:";
    $lang['text_logo_url'] =  "URL, na kterou by mělo logo odkazovat :";
    $lang['text_virus_info_url'] =  "URL template pro informace o virech:";
    $lang['text_virus_lookup'] =  "Virus name rewriting rules:";
    $lang['text_none'] =  "Žádné (žádné vyhledávání)";
    $lang['text_google'] =  "Google Search";
    $lang['text_fprot'] =  "F-Prot";
    $lang['text_fsecure'] =  "F-Secure";
    $lang['text_fsecurejp'] =  "F-Secure Japan";
    $lang['text_sophos'] =  "Sophos";
    $lang['text_nod32'] =  "NOD32";
    $lang['text_norman'] =  "Norman Virus Control";
    $lang['text_trend'] =  "Trend Micro";
    $lang['text_symantec'] =  "Symantec";
    $lang['text_mcafee'] =  "McAfee VirusScan";
    $lang['text_currency_label'] =  "Symbol měny:";
    $lang['text_bandwidth_cost'] =  "Cena jednoho přeneseného gigabajtu za měsíc:";
    $lang['text_enable_stats_reporting'] =  "Povoli reportování statistik?";
    $lang['text_primary_report_server'] =  "Primární server pro report statistik:";
    $lang['text_primary_report_port'] =  "Číslo portu primárního serveru:";
    $lang['text_secondary_report_server'] =  "Sekundární server pro report statistik:";
    $lang['text_secondary_report_port'] =  "Číslo portu sekundárního serveru:";
    $lang['text_reporter_sitename'] =  "Jméno vašeho serveru:";
    $lang['text_reporter_username'] =  "'Maia Reporter ID' pro váš server:";
    $lang['text_reporter_password'] =  "Heslo reportéra pro váš server:";

    // Buttons
    $lang['button_submit'] =  "Aktualizovat nastavení";
    $lang['button_restore'] =  "Vymazat formulář";

    // Links
    $lang['link_admin_menu'] =  "Návrat do Administračního menu";
?>
