<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Karanténa";

    // Table headers
    $lang['header_spam'] =  "Podezření na Spam";
    $lang['header_viruses'] =  "Viry/Malware";
    $lang['header_banned_files'] =  "Zablokované přílohy";
    $lang['header_bad_headers'] =  "Nesprávné Emailové hlavičky";
    $lang['header_quarantine_contents'] =  "Obsah karantény";

    // Text labels
    $lang['text_item'] =  "Položka";
    $lang['text_items'] =  "Položky";
    $lang['text_score'] =  "Score";
    $lang['text_received'] =  "Přijato";
    $lang['text_from'] =  "Od";
    $lang['text_to'] =  "Pro";
    $lang['text_ham'] =  "Non-spam?";
    $lang['text_spam'] =  "Spam?";
    $lang['text_rescue'] =  "Non-spam!";
    $lang['text_delete'] =  "Smazat";
    $lang['text_subject'] =  "Předmět";
    $lang['text_virus'] =  "Virus";
    $lang['text_file_name'] =  "Název souboru";
    $lang['text_no_subject'] =  "žádný předmět";
    $lang['text_empty'] =  "Vaše karanténa je prázdná.";
    $lang['text_updated'] =  "Vaše karanténa byla aktualizována.";
    $lang['text_of'] =  "of";
    $lang['text_spam_confirmed'] =  "%d položek podezření na spam bylo potvrzeno";
    $lang['text_spam_rescued'] =  "%d položek podezření na spam bylo zachráněno";
    $lang['text_spam_deleted'] =  "%d položek podezření na spam bylo smazáno";
    $lang['text_viruses_rescued'] =  "%d virus/malware položky byly zachráněny";
    $lang['text_viruses_deleted'] =  "%d virus/malware položky byly smazány";
    $lang['text_attachments_rescued'] =  "%d položek zakázaných příloh byly zachráněny";
    $lang['text_attachments_deleted'] =  "%d položek zakázaných příloh byly smazány";
    $lang['text_headers_rescued'] =  "%d poškozených e-mailů bylo zachráněno";
    $lang['text_headers_deleted'] =  "%d poškozených e-mailů bylo smazáno";
    $lang['text_suspected_spam_item'] =  "položka Podezření na Spam";
    $lang['text_suspected_spam_items'] =  "položky Podezření na Spam";
    $lang['text_virus_item'] =  "Virus/Malware položka";
    $lang['text_virus_items'] =  "Virus/Malware položky";
    $lang['text_banned_file_item'] =  "Zablokovaná příloha";
    $lang['text_banned_file_items'] =  "Zablokované přílohy";
    $lang['text_bad_header_item'] =  "Poškozený E-mail";
    $lang['text_bad_header_items'] =  "Poškozené E-maily";
    $lang['text_rescue_error'] = "Nelze zachránit email: ";

    // Button text
    $lang['button_confirm_spam'] =  "Všechny položky na seznamu jsou Spam";
    $lang['button_delete_viruses'] =  "Smazat tyto Viry";
    $lang['button_delete_attachments'] =  "Smazat tyto Soubory";
    $lang['button_delete_headers'] =  "Smazat tyto Poškozené E-maily";
    $lang['button_confirm'] =  "Potvrdit status těchto položek";
    $lang['button_delete_all_items'] =  "Smazat všechny položky v karanténě";

    // Link text
    $lang['link_prev'] =  "Předchozí";
    $lang['link_next'] =  "Další";
    $lang['link_quarantine'] =  "Návrat na menu Karantény";
    $lang['link_welcome']  = "Návrat na Uvítací stránku";

?>
