<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Nastavení Emailového Filtru";

    // Table headers
    $lang['header_addresses'] =  "E-mailové Adresy";
    $lang['header_miscellaneous'] =  "Různá Nastavení";
    $lang['header_address'] =  "Adresa";
    $lang['header_login_info'] =  "Přihlašovací údaje";

    // Text messages
    $lang['text_username'] =  "Přihlašovací jméno";
    $lang['text_email_address'] =  "E-mailová adresa";
    $lang['text_password'] =  "Heslo";
    $lang['text_reminders'] =  "Posílat e-mailové upozornění o karanténě?";
    $lang['text_charts'] =  "Zobrazit grafy?";
    $lang['text_yes'] =  "Ano";
    $lang['text_no'] =  "Ne";
    $lang['text_virus_scanning'] =  "Anti-virová kontrola";
    $lang['text_enabled'] =  "Povoleno";
    $lang['text_disabled'] =  "Zakázáno";
    $lang['text_quarantined'] =  "Karantenizován";
    $lang['text_labeled'] =  "Označen";
    $lang['text_discarded'] =  "Vyřazen";
    $lang['text_detected_viruses'] =  "Zjištěný vir by měl být...";
    $lang['text_spam_filtering'] =  "Filtrování Spamu";
    $lang['text_detected_spam'] =  "Zjištěný spam by měl být...";
    $lang['text_prefix_subject'] =  "Přidat prefix do předmětu emailu považovaného za spam";
    $lang['text_add_spam_header'] =  "Přidat X-Spam: hlavičky pokud je Score";
    $lang['text_consider_mail_spam'] =  "Považuj email za 'Spam' pokud je Score";
    $lang['text_quarantine_spam'] =  "Umístit Spam do karantény pokud je Score";
    $lang['text_kill_spam'] =  "Vyřadit Spam (bez karantény) pokud je Score";
    $lang['text_attachment_filtering'] =  "Filtrování Příloh";
    $lang['text_mail_with_attachments'] =  "Email s přílohou představující možné nebezpečí by měl být...";
    $lang['text_bad_header_filtering'] =  "Filtrování nesprávných hlaviček emailů";
    $lang['text_mail_with_bad_headers'] =  "Email obsahující nesprávnou hlavičku by měl být...";
    $lang['text_settings_updated'] =  "Nastavení vašeho Emailového Filtru bylo aktualizováno.";
    $lang['text_address_added'] =  "Adresa %s byla spojena s vaším účtem.";
    $lang['text_login_failed'] =  "Autentikace selhala pro '%s'.";
    $lang['text_primary'] =  "Primární adresa";
    $lang['text_no_addresses_linked'] =  "Žádné adresy nejsou spojené s tímto účtem.";
    $lang['text_new_primary_email'] =  "%s je od teď vaší primární emailovou adresou.";
    $lang['text_language'] =  "Jazyk";
    $lang['text_charset'] =  "Znaková sada";
    $lang['text_theme']	= "Motiv";
    $lang['text_spamtrap'] =  "Slouží tento účet jako spam-trap?";
    $lang['text_auto_whitelist'] =  "Přidat odesílatele zachráněného emailu do whitelistu?";
    $lang['text_items_per_page'] =  "Kolik emailových zpráv se má zobrazit na stránku?";
    $lang['text_digest_interval'] = "Interval pro souhrnný e-mail? (0 pro deaktivaci, v hodinách)";
    $lang['text_domain_digest_interval'] = "Výchozí interval pro souhrnný e-mail? (0 pro deaktivaci, v hodinách)";
    $lang['text_new_login_name'] =  "Nové přihlašovací jméno";
    $lang['text_new_password'] =  "Nové heslo";
    $lang['text_confirm_new_password'] =  "Potvrďte nové heslo";
    $lang['text_login_name_empty'] =  "Přihlašovací jméno je požadováno.";
    $lang['text_login_name_not_allowed'] =  "Přihlašovací jména nemohou začínat '@'.";
    $lang['text_password_empty'] =  "Musíte zadat heslo a potvrzení hesla.";
    $lang['text_password_mismatch'] =  "Heslo a jeho potvrzení se neshodují.";
    $lang['text_login_name_exists'] =  "Požadované přihlašovací jméno je již zaregistrováno jiným uživatelem.";
    $lang['text_password_updated'] =  "Vaše heslo bylo změněno.";
    $lang['text_credentials_updated'] =  "Vaše přihlašovací jméno a heslo bylo změněno.";

    // Buttons
    $lang['button_add_email_address'] =  "Přidat E-Mailovou Adresu";
    $lang['button_reset'] =  "Reset";
    $lang['button_update_misc'] =  "Aktualizovat Různá Nastavení";
    $lang['button_update_address'] =  "Aktualizovat nastavení této adresy";
    $lang['button_update_all_addresses'] =  "Aktualizovat nastavení všech adres";
    $lang['button_make_primary'] =  "Nastavit jako vychozí";
    $lang['button_change_login_info'] =  "Aktualizovat přihlašovací údaje";

    // Links
    $lang['link_settings'] =  "Návrat na stránku Nastavení";
?>
