<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Administration: Configuration du syst&egrave;me";

    // Table header
    $lang['header_system_menu'] =  "Configuration g&eacute;n&eacute;rale";
    $lang['header_charts'] =  "Graphiques";
    $lang['header_reminders'] =  "Dur&eacute;e du cache et Rappels de quarantaine";
    $lang['header_authentication'] =  "Authentification";
    $lang['header_virus_info'] =  "Informations sur les virus";
    $lang['header_display'] =  "Affichage";
    $lang['header_paths'] =  "Chemins (PATH)";
    $lang['header_bandwidth'] =  "Gestion de la bande passante";
    $lang['header_stats_reporting'] =  "Statistiques globales";

    // Text labels
    $lang['text_yes'] =  "Oui";
    $lang['text_no'] =  "Non";
    $lang['text_accept'] =  "Accept&eacute;";
    $lang['text_reject'] =  "Refus&eacute;";
    $lang['text_enable_user_autocreation'] =  "Cr&eacute;ation automatique des comptes utilisateurs ?";
    $lang['text_internal_auth'] =  "G&eacute;n&eacute;ration automatique des mots de passe pour les nouveaux comptes ?";
    $lang['text_enable_false_negative_management'] =  "Gestion des \"faux n&eacute;gatifs\" ?";
    $lang['text_enable_stats_tracking'] =  "Activation des statistiques ?";
    $lang['text_enable_virus_scanning'] =  "Activation de la d&eacute;tection de virus ?";
    $lang['text_enable_spam_filtering'] =  "Activation des filtres &agrave; Pourriels ?";
    $lang['text_enable_banned_files_checking'] =  "Activation de la d&eacute;tection des attachements banis ?";
    $lang['text_enable_bad_header_checking'] =  "Activation de la v&eacute;rification des en-t&Atilde;&#170;tes ?";
    $lang['text_enable_spamtraps'] =  "Activation des comptes pi&egrave;ges \"Pots de miel\" pour les Pourriels ?";
    $lang['text_enable_charts'] =  "Activation des graphiques ?";
    $lang['text_enable_address_linking'] =  "Permettre aux utilisateurs de lier leur compte avec d'autres adresses e-mail ?";
    $lang['text_enable_username_changes'] =  "Permettre aux utilisateurs de changer leur nom de compte ?";
    $lang['text_enable_privacy_invasion'] =  "Permettre aux administrateurs de lire les e-mails des utilisateurs ?";
    $lang['text_system_default_user_is_local'] =  "Utilisation du compte par d&eacute;faut (@.) seulement pour les boites locales ?";
    $lang['text_user_virus_scanning'] =  "Laisser les utilisateurs (des)activer la d&eacute;tection de virus ?";
    $lang['text_user_spam_filtering'] =  "Laisser les utilisateurs (des)activer les filtres a Pourriels ?";
    $lang['text_user_banned_files_checking'] =  "Laisser les utilisateurs (des)activer la d&eacute;tection des pi&egrave;ces jointes interdites ?";
    $lang['text_user_bad_header_checking'] =  "Laisser les utilisateurs (des)activer la v&eacute;rifications des en-t&ecirc;tes ?";
    $lang['text_size_limit'] =  "Taille maximale des messages (octets) :";
    $lang['text_oversize_policy'] =  "Les objets trop volumineux seront ...";
    $lang['text_admin_email'] =  "Adresse de contact de l'administrateur:";
    $lang['text_smtp_server'] =  "Serveur pour l'envoi apr&egrave;s v&eacute;rifications (MTA-TX) :";
    $lang['text_smtp_port'] =  "Port SMTP pour MTA-TX:";
    $lang['text_key_file'] =  "Fichier contenant la clef de chiffrage (option) :";
    $lang['text_newuser_template_file'] =  "Fichier mod&egrave;le pour le courriel envoy&eacute; aux nouveaux utilisateurs :";
    $lang['text_chart_ham_colour'] =  "Couleur utilis&eacute;e pour les messages confirm&eacute;s normaux :";
    $lang['text_chart_spam_colour'] =  "Couleur utilis&eacute;e pour les messages confirm&eacute;s pourriels :";
    $lang['text_chart_virus_colour'] =  "Couleur utilis&eacute;e pour les virus :";
    $lang['text_chart_fp_colour'] =  "Couleur utilis&eacute;e pour les faux positif :";
    $lang['text_chart_fn_colour'] =  "Couleur utilis&eacute;e pour les faux n&eacute;gatif :";
    $lang['text_chart_suspected_ham_colour'] =  "Couleur utilis&eacute;e pour les messages suspect&eacute;s normaux :";
    $lang['text_chart_suspected_spam_colour'] =  "Couleur utilis&eacute;e pour les messages suspect&eacute;s pourriels :";
    $lang['text_chart_wl_colour'] =  "Couleur utilis&eacute;e pour les courriels en liste blanche :";
    $lang['text_chart_bl_colour'] =  "Couleur utilis&eacute;e pour les courriels en liste noire :";
    $lang['text_chart_background_colour'] =  "Couleur de fonds des graphiques :";
    $lang['text_chart_font_colour'] =  "Couleur pour les polices de caract&egrave;res utilis&eacute;es dans les graphiques :";
    $lang['text_chart_autogeneration_interval'] =  "Intervalle de g&eacute;n&eacute;ration automatique des graphiques (min.) :";
    $lang['text_expiry_period'] =  "Dur&eacute;e de vie des courriels en quarantaine (jours) :";
    $lang['text_ham_cache_expiry_period'] =  "Dur&eacute;e de vie des courriels normaux cach&eacute;s (jours) :";
    $lang['text_reminder_threshold_count'] =  "Limite d'envoi d'un rappel (nombre objets) :";
    $lang['text_reminder_threshold_size'] =  "Limite d'envoyer d'un rappel (taille) :";
    $lang['text_reminder_template_file'] =  "Fichier mod&egrave;le pour les rappels :";
    $lang['text_reminder_login_url'] =  "URL de connection pour les courriels de rappel :";
    $lang['text_banner_title'] =  "Titre de la page principale :";
    $lang['text_use_icons'] =  "Afficher les images dans la barre de menu ?";
    $lang['text_use_logo'] =  "Afficher un logo sur la bani&egrave;re de la page d'entr&eacute;e ?";
    $lang['text_logo_file'] =  "Fichier contenant l'image pour le logo :";
    $lang['text_logo_alt_text'] =  "Texte alternatif (alt) pour le logo :";
    $lang['text_logo_url'] =  "URL pour lier le logo :";
    $lang['text_virus_info_url'] =  "Mod&egrave;le d'URL pour l'information sur les virus :";
    $lang['text_virus_lookup'] =  "R&egrave;gles pour modifier le nom des virus :";
    $lang['text_none'] =  "Aucun (pas de recherche)";
    $lang['text_google'] =  "Recherche via Google";
    $lang['text_fprot'] =  "F-Prot";
    $lang['text_fsecure'] =  "F-Secure";
    $lang['text_fsecurejp'] =  "F-Secure Japan";
    $lang['text_sophos'] =  "Sophos";
    $lang['text_nod32'] =  "NOD32";
    $lang['text_norman'] =  "Norman Virus Control";
    $lang['text_trend'] =  "Trend Micro";
    $lang['text_symantec'] =  "Symantec";
    $lang['text_mcafee'] =  "McAfee VirusScan";
    $lang['text_currency_label'] =  "Symbole mon&eacute;taire :";
    $lang['text_bandwidth_cost'] =  "Prix mensuel de la bande passante, par Gigaoctets :";
    $lang['text_enable_stats_reporting'] =  "Permettre la transmission des statistiques du site ?";
    $lang['text_primary_report_server'] =  "Serveur primaire pour transmettre les statistiques :";
    $lang['text_primary_report_port'] =  "Num&eacute;ro de port pour le serveur primaire :";
    $lang['text_secondary_report_server'] =  "Serveur secondaire pour transmettre les statistiques :";
    $lang['text_secondary_report_port'] =  "Num&eacute;ro de port pour le serveur secondaire :";
    $lang['text_reporter_sitename'] =  "Nom du site :";
    $lang['text_reporter_username'] =  "Identification de rapporteur Maia (ID) :";
    $lang['text_reporter_password'] =  "Mot de passe de rapporteur Maia :";

    // Buttons
    $lang['button_submit'] =  "Mise &agrave; jour des options";
    $lang['button_restore'] =  "Efface le formulaire";

    // Links
    $lang['link_admin_menu'] =  "Retour au menu d'administration";
?>
