<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */


    // Page subtitle
    $lang['banner_subtitle'] =  "Administration: Aide";

    // Table header
    $lang['header_help_menu'] =  "Aide";

    // Users
    $lang['adminhelp_find_users'] =  "<b>%s</b> permet de rechercher un utilisateur dans la base de " .
                                     "donn&eacute;es suivant les crit&egrave;res fournis. Le caract&egrave;re " .
    			                     "'*' sert de jocker pouvant se substituer &agrave; zero ou plusieurs " .
	                    			 "caract&egrave;res. Par exemple, \"ch*e\" peut trouver les pr&eacute;noms ".
				                     "comme \"christophe\" et \"charles\". La recherche est sensible " .
				                     "a la casse, rendant \"Jean\" diff&eacute;rent de \"jean\". Les " .
				                     "administrateurs des domaines ne pourront effectuer des recherches que " .
				                     "sur des utilisateurs des domaines sous leur contr&ocirc;le.";

    $lang['adminhelp_add_email_address'] =  "<b>%s</b> permet d'ajouter une adresse e-mail dans la " .
    					                    "base de donn&eacute;es ainsi qu'un utilisateur qui sera ". 
					                        "alors propri&eacute;taire de cette adresse. Le nom de ".
					                        "l'utilisateur est le m&ecirc;me que l'adresse e-mail. " .
					                        "Si vous utilisez un syst&egrave;me d'authentification " .
					                        "POP3 ou IMAP, l'adresse que vous donnez ici doit &ecirc;tre " .
					                        "modifi&eacute;e pour correspondre au domaine du serveur de " .
					                        "messagerie. Maia fera ce travail automatiquement, entrez " .
					                        "simplement une adresse e-mail valide.";

    $lang['adminhelp_link_email_address'] =  "<b>%s</b> permet de faire un lien entre une adresse e-mail " .
                                             "et un compte utilisateur existant. Une adresse e-mail ne " .
	                        				 "peut appartenir qu'&agrave; un seul utilisateur. Cr&eacute;er " .
                        					 "un nouveau lien va donc casser un lien pr&eacute;-existant, " .
                        					 "et supprimer le compte de l'utilisateur si ce dernier n'est " .
                        					 "plus li&eacute; &agrave;  aucune adresse. Si l'ancien utilisateur est supprim&eacute;, " .
                        					 "les donn&eacute;es relatives au compte (statistiques, listes blanches et noires, ".
                        					 "quarantaine et cache) seront transf&eacute;r&eacute;es au nouveau propri&eacute;taire.";

    $lang['adminhelp_delete_email_address'] =  "<b>%s</b> permet de suprimer une adresse de courriel du " .
					                           "syst&egrave;me. Cependant, vous ne pouvez pas supprimer l'adresse " .
                        					   "principale d'un utilisateur. Si vous d&eacute;sirez le faire, " .
                        					   "vous devez en premier lieu donner une autre adresse primaire ".
                        					   "pour l'utilisateur en question. Il s'agit d'une option de ".
                        					   "s&eacute;curit&eacute; pour &eacute;viter de supprimer un utilisateur ".
        				                       "qui ne poss&egrave;de qu'une adresse. Pour supprimer un utilisateur, ".
                        					   "utilisez la commande <b>%s</b> ci-dessous.";

    $lang['adminhelp_delete_user'] =  "<b>%s</b> suprime un compte utilisateur du syst&egrave;me, y compris " .
				                      "toutes les informations de statistiques, les listes blanches " .
                    				  "et noires et tous les courriels en quarantaine / cach&eacute;s pour cet " .
                    				  "utilisateur. De plus, toutes les adresses associ&eacute;es seront " .
                    				  "&eacute;galement supprim&eacute;es. Dans le cas ou l'option <b>%s</b> est " .
                    				  "activ&eacute;e, les courriels &agrave; destination des adresses supprim&eacute;es " .
                    				  "cr&eacute;erons un nouveau compte utilisateur. Cette option n'emp&ecirc;che ".
                    				  "pas que le compte soit recr&eacute;&eacute; par la suite, il faut donc supprimer aussi le compte " .
                    				  "sur le serveur de courrier.";

    $lang['adminhelp_impersonate'] =  "<b>%s</b> liste le r&eacute;sultat de la recherche d'utilisateur et offre" .
                    				  "la possibilit&eacute; de changer de personnalit&eacute; (endosser une autre ".
                    				  "identit&eacute;). Lors de la s&eacute;lection d'un nom dans la liste, vous serez " .
                    				  "connecte au syst&egrave;me comme si vous &eacute;tiez l'utilisateur en question. " .
                    				  "Ceci vous permet de voir Maia avec les yeux de l'utilisateur, ".
                    				  "pour l'aider dans des situations difficiles. Pour quitter l'identit&eacute; ".
                    				  "endoss&eacute;e, il suffit de cliquer sur %s dans la barre d'outils.";

    // Domains
    $lang['adminhelp_domain_administration'] =  "<b>%s</b> retourne la liste des domaines dont vous &ecirc;tes d&eacute;clar&eacute;" .
                        					    "administrateur. Le domaine @. permet de d&eacute;finir les param&egrave;tres " .
                        					    "par d&eacute;faut pour l'ensemble du syst&egrave;me et ne peut pas &ecirc;tre supprim&eacute;.".
                        					    "S&eacute;lectionnez un autre domaine pour d&eacute;finir les options par d&eacute;faut du ".
                        					    "domaine en question, param&egrave;tres qui peuvent &ecirc;tre encore modifi&eacute;s par ".
                        					    "l'utilisateur final (possibilit&eacute; de limiter les options modifiables).";

    $lang['adminhelp_add_domain'] =  "<b>%s</b> permet &agrave; l'administrateur principal d'ajouter un nouveau " .
                    				 "domaine dans le syst&egrave;me, avec les options standard qui sont copi&eacute;es ".
                    				 "du domaine par d&eacute;faut (@.). Pour ajouter des administrateurs au nouveau ".
                    				 "domaine nouvellement cr&eacute;&eacute; ou pour ajuster les param&egrave;tres par d&eacute;faut, s&eacute;lectionnez ".
                    				 "le domaine depuis la liste ci-dessous.";

    $lang['adminhelp_domain_settings'] =  "<b>%s</b> affiche les options par d&eacute;faut pour le domaine choisi. " .
                    				      "Ces options sont identiques &agrave; celles que l'utilisateur peut modifier ".
				                          "pour ses propres adresses de courriel, cependant les modifications ".
                    				      "et choix op&eacute;r&eacute;s ici sont valables seulement pour les nouvelles adresses. ".
				                          "Les utilisateurs ont alors la possibilit&eacute; de modifier leurs propre options".
                    				      "Pour plus amples renseignements, veillez consulter la page %s".
				                          "de l'utilisateur.";

    $lang['adminhelp_administrators'] =  "<b>%s</b> retourne la liste des administrateurs du domaine ".
                    				     "et permet &agrave; l'administrateur principal de supprimer les privil&egrave;ges pour ".
				                         "tout ou partie des administrateurs. De plus, l'adminsitrateur principal ".
                    				     "peut modifier les param&egrave;tres de <i>tous</i> les domaines, et ne peut ".
                    				     "pas supprimer ses propres privil&egrave;ges (sauf dans le cas de connexion ".
                    				     "avec le suffix \"&amp;super=unregister\")";

    $lang['adminhelp_add_administrator'] =  "<b>%s</b> affiche la liste de tous les utilisateurs du syst&egrave;me ".
                        					"qui ne sont ni des adminstrateurs pour ce domaine ni l'administrateur principal. ".
                        					"Il est alors possible pour l'administrateur ".
                        					"principal de choisir un utilisateur pour en faire un administrateur ".
                        					"du domaine concern&eacute;. Il est possible pour un administrateur d'avoir ".
                        					"des privil&egrave;ges utilisables sur plusieurs domaines diff&eacute;rents ".
                        					"(pour autant que l'administrateur principal ait donn&eacute; les droits). ".
                        					"De m&ecirc;me, il est possible d'avoir plusieurs administrateurs pour un ".
                        					"domaine particulier. L'administrateur principal est administrateur" . 
                        					"de tous les domaines";
                        					
    // Virus Aliases
    $lang['adminhelp_virus_aliases'] =  "<b>%s</b> retourne une liste contenant les alias de virus ainsi que le".
                    				    "nom g&eacute;n&eacute;rique du virus auquel ils sont assimil&eacute;s, pour l'ensemble du syst&egrave;me. Il vous est ".
                    				    "possible &agrave; tout moment, d'effacer ces alias, mais ceci ne reconstituera ".
                    				    "pas ses anciennes statistiques.";
				    

    $lang['adminhelp_add_virus_alias'] =  "<b>%s</b> vous permet de cr&eacute;er un alias pour un nom de virus " .
                    				      "existant. Cette fonctionnalit&eacute; permet d'avoir des statistques " .
                    				      "coh&eacute;rentes lors de l'utilisation de plusieurs anti-virus, avec ".
                    				      "des noms diff&eacute;rents pour le m&ecirc;me virus (par exemple dans le cas ".
                    				      "du virus Worm.Klez.H et Worm/Klez-H@MM). Le fait de faire un " .
				                          "alias de l'un sur l'autre permet &agrave; Maia de comptabiliser ".
                    				      "correctement ces virus.";

    // Languages
    $lang['adminhelp_languages'] =  "<b>%s</b> retourne la liste des diff&eacute;rentes langues install&eacute;es ".
				                    "support&eacute;es par Maia. La langue par d&eacute;faut (Anglais - English) est ".
                    				"toujours pr&eacute;sente et ne peut pas &ecirc;tre supprim&eacute;e.";

    $lang['adminhelp_install_languages'] =  "<b>%s</b> vous permet d'installer de nouvelles langues ".
			                        		"et de les rendre disponnibles pour les autres utilisateurs. ".
                        					"Pour ce faire, vous devez en premier installer les fichiers ".
                        					"pour la langue en question dans le r&eacute;pertoire ./locale/ en ".
                        					"respectant la convention de nommage &agrave; deux lettres ISO-639 ".
                        					"(par exemple en, fr, de, ...). Une fois les fichiers install&eacute;s, ".
                        					"vous verrez votre nouvelle langue dans la liste.";

    // System Configuration
    $lang['adminhelp_enable_user_autocreation'] =  "<b>%s</b> permet &agrave; Maia de cr&eacute;er automatiquement des comptes ".
                        					       "utilisateurs lorsqu'un courriel arrive &agrave; destination d'une ".
					                               "adresse qui n'est pas encore connue du syst&egrave;me. Le nom de ".
                        					       "l'utilisateur sera son adresse de courriel et pourra &ecirc;tre ".
                        					       "chang&eacute; ult&eacute;rieurement par l'utilisateur (par exemple, lors de ".
                        					       "la premi&egrave;re connexion au syst&egrave;me). Les options de ce compte ".
                        					       "seront tir&eacute;es de la configuration par d&eacute;faut du domaine concern&eacute; ".
                        					       "si elle existe, sinon les param&egrave;tres du syst&egrave;me seront appliqu&eacute;s. ".
                        					       "Dans le cas o&ugrave; cette option n'est pas activ&eacute;e, les comptes " .
					                               "ne seront cr&eacute;&eacute;s que lors de la premi&egrave;re connexion des utilisateurs. Cette ".
                        					       "fonction doit &ecirc;tre utilis&eacute;e avec pr&eacute;caution, sinon une grande ".
                        					       "quantit&eacute; de comptes peuvent &ecirc;tre cr&eacute;&eacute;s par une attaque cherchant ".
					                               "&agrave; deviner les comptes existants sur une machine.";

    $lang['adminhelp_internal_auth'] =  "<b>%s</b> active la g&eacute;n&eacute;ration automatique d'un mot de passe al&eacute;atoire ".
                    				    "de 8 caract&egrave;res de long et les transmet par courriel &agrave; l'utilisateur. ".
                    				    "Ce dernier peut alors utiliser ces informations pour se connecter au ".
                    				    "syst&egrave;me et les modifer via sa page d'options personnelles.";

    $lang['adminhelp_enable_false_negative_management'] =  "<b>%s</b> active ou d&eacute;sactive le cache des courriels ".
					                            	       "sains qui permet &agrave; Maia de r&eacute;cup&eacute;rer les faux n&eacute;gatifs ".
                            						       "(pourriels pris pour des courriels sains). Le fait de pouvoir ".
						                                   "informer Maia des erreurs permet d'am&eacute;liorer la pertinence du syst&egrave;me ;".
                            						       " cette option doit donc &ecirc;tre activ&eacute;e, &agrave; moins que ".
						                                   "l'espace disque consomm&eacute; par ce cache soit trop ".
                            						       "important. Il est possible de contr&ocirc;ler la dur&eacute;e ".
						                                   "de vie de ce cache. Voir <b>%s</b> pour plus de d&eacute;tails.";

    $lang['adminhelp_enable_stats_tracking'] =  "<b>%s</b> active ou d&eacute;sactive les statistiques internes de Maia. ".
                        					    "Dans la pluspart des cas, cette option sera active, car elle permet ".
					                            "de donner des informations pr&eacute;cieuses. Dans le cas d'analyses ".
                        					    "via un outil externe, il est possible de stopper cet outil, ".
					                            "permettant d'&eacute;conomiser quelques ressources.";

    $lang['adminhelp_enable_virus_scanning'] =  "<b>%s</b> active ou d&eacute;sactive globalement la d&eacute;tection ".
                        					    "de virus et autre forme de logiciels malicieux.";

    $lang['adminhelp_user_virus_scanning'] =  "<b>%s</b> permet d'autoriser ou pas les utilisateurs &agrave; modifier ".
					                          "la d&eacute;tection des virus.";

    $lang['adminhelp_enable_spam_filtering'] =  "<b>%s</b> active ou d&eacute;sactive globalement les filtres de ".
                        					    "d&eacute;tection des pourriels.";

    $lang['adminhelp_user_spam_filtering'] =  "<b>%s</b>permet d'autoriser ou pas les utilisateurs &agrave; modifier ".
					                          "la d&eacute;tection des pourriels.";

    $lang['adminhelp_enable_banned_files_checking'] =  "<b>%s</b> active ou d&eacute;sactive globalement la d&eacute;tection ".
                            						   "des pi&egrave;ces jointes interdites.";

    $lang['adminhelp_user_banned_files_checking'] =  "<b>%s</b> permet d'autoriser ou pas les utilisateurs &agrave; modifier ".
                                				     "la d&eacute;tection des pi&egrave;ces jointes interdites.";

    $lang['adminhelp_enable_bad_header_checking'] =  "<b>%s</b> active ou d&eacute;sactive globalement la d&eacute;tection ".
                            						 "des en-t&ecirc;tes non valides.";

    $lang['adminhelp_user_bad_header_checking'] =  "<b>%s</b> permet d'autoriser ou pas les utilisateurs &agrave; modifier ".
                        					       "la d&eacute;tection des en-t&ecirc;tes non valides.";

    $lang['adminhelp_enable_spamtraps'] =  "<b>%s</b> active ou d&eacute;sactive globalement l'utilisation des comptes ".
                    				       "\"pots de miel \" pour les pourriels. Ces comptes ne sont pas utilis&eacute;s ".
				                           "pour des messages utiles, mais tout ce qui arrive sur ces adresses ".
                    				       "sera consid&eacute;r&eacute; comme des pourriels avec apprentissage automatique. Ces ".
				                           "comptes doivent &ecirc;tre utilis&eacute;s avec prudence et une bonne compr&eacute;hension ".
                    				       "du syst&egrave;me. Le but de ce genre de compte est d'attirer tous les ".
				                           "pourriels qui utilisent une d&eacute;tection des comptes existant (dictionnaire) ".
                    				       "pour les faire apprendre au syst&egrave;me, assurant ainsi une bonne protection ".
				                           "des utilisateurs. Donc, si vous ne fa&icirc;tes pas confiance dans l'utilisation ".
                    				       "de cette commande par vos utilisateurs, il est judicieux de couper ".
				                           "l'acc&egrave;s &agrave; cette fonction ici.";

    $lang['adminhelp_enable_address_linking'] =  "<b>%s</b> Autorise la possibilit&eacute; de lier plusieurs adresses ".
                        					     "de courriel &agrave; un seul compte utilisateur. Les administrateurs ".
                        					     "peuvent toujours effectuer la liaison pour les utilisateurs, ".
                        					     "depuis la page d'administration des utilisateurs, m&ecirc;me si cette ".
                        					     "option est d&eacute;sactiv&eacute;e.";

    $lang['adminhelp_enable_username_changes'] =  "<b>%s</b> active ou d&eacute;sactive la possibilit&eacute; donn&eacute;e aux utilisateurs ".
					                              "de modifier leur nom d'utilisateur. Ceci n'est applicable que ".
                        					      "lors de l'utilisation de l'authentification interne.";

    $lang['adminhelp_enable_privacy_invasion'] =  "<b>%s</b> active ou d&eacute;sactive la possibilit&eacute; donn&eacute;e aux administrateurs ".
                        					      "de lister et lire les courriels stock&eacute;s dans les zones ".
					                              "de quarantaine et le cache des courriels sains des utilisateurs ".
                        					      "sous leur contr&Atilde;&#180;le. Normalement, dans le cadre du respect ".
                        					      "de la sph&egrave;re priv&eacute;e, cette option doit &ecirc;tre d&eacute;sactiv&eacute;e, sauf ".
                        					      "si la politique interne de votre soci&eacute;t&eacute; permet de lire ".
                        					      "le contenu des courriels.";

    $lang['adminhelp_system_default_user_is_local'] =  "<b>%s</b> d&eacute;termine si l'utilisateur par d&eacute;faut du syst&egrave;me ".
                            						   "global (@.) ne couvre que les adresses locales, ou aussi ".
                            						   "les adresses externes. En cas d'activation pour les domaines ".
                            						   "externes, vous allez alors capter dans ce compte, les courriels ".
                            						   "en partance de vos utilisateurs. Dans la majorit&eacute; des cas, ".
                            						   "il est judicieux de r&eacute;pondre <b>Oui</b>.";

    $lang['adminhelp_size_limit'] =  "<b>%s</b> indique la taille maximale (en octets) du courriel qui sera pass&eacute; au travers ".
                			         "des filtres de contenu. Il est a noter que suivant les cas, un ajustement ".
                    				 "de la base de donn&eacute;es est n&eacute;cessaire, pour &ecirc;tre en coh&eacute;rence avec la valeur ".
                    				 "donn&eacute;e ici. Par exemple, il faut d&eacute;finir la valeur de <b>max_allowed_packet</b> ".
                    				 "dans MySQL comme au mimimum &eacute;gal &agrave; la valeur entr&eacute;e ici.";

    $lang['adminhelp_oversize_policy'] =  "<b>%s</b> d&eacute;termine le traitement des &eacute;l&eacute;ments dont la taille est ".
                    				      "trop importante. L'utilisation de <b>%s</b> permet aux &eacute;l&eacute;ments ".
                    				      "trop volumineux d'&ecirc;tre transmis dans la bo&icirc;te de destination, alors ".
                    				      "que <b>%s</b> rejette le message, avec un avertissement &agrave; ".
                    				      "l'exp&eacute;diteur lui sp&eacute;cifiant le type de probl&egrave;me survenu.";

    $lang['adminhelp_installation_directory'] =  "<b>%s</b> d&eacute;finit le chemin (absolu) o&Atilde;¹ sont stock&eacute;s ".
					                             "les scripts PHP pour Maia. Ceci permet &agrave; Maia de d&eacute;terminer ".
                        					     "l'emplacement exact des fichiers de langues, et les autres ".
					                             "&eacute;l&eacute;ments pouvant &ecirc;tre install&eacute;s.";

    $lang['adminhelp_amavisd_conf'] =  "<b>%s</b> d&eacute;finit l'emplacement (chemin / PATH) du fichier de configuration (amavis.conf) ".
		                    		   "de amavisd-new, qui renferme les informations de configuration.";

    $lang['adminhelp_admin_email'] =  "<b>%s</b> d&eacute;finit l'adresse de courriel de l'administrateur syst&egrave;me ".
                    				  "qui sera contact&eacute; en cas de demande d'assistance.";

    $lang['adminhelp_smtp_server'] =  "<b>%s</b> d&eacute;finit le nom du serveur SMTP (ou son adresse IP) que Maia ".
				                      "utilise pour l'envoi des messages mis en quarantaine ou des diff&eacute;rents rappels.";

    $lang['adminhelp_smtp_port'] =  "<b>%s</b> d&eacute;finit le num&eacute;ro de port du service SMTP que Maia ".
                    			    "utilise pour l'envoi des messages en quarantaine ou des diff&eacute;rents ".
                    				"rappels. Le num&eacute;ro standard est 25, mais dans le cas de la configuration ".
                    				"en serveur double, avec un serveur de r&eacute;c&eacute;ption (MTA-RX) et un serveur ".
                				    "de sortie (MTA-TX), le port probable &agrave; utiliser est 10025.";

    $lang['adminhelp_key_file'] =  "<b>%s</b> d&eacute;finit le nom du fichier (avec le chemin complet, ou alors relatif  " .
                			       "depuis le r&eacute;pertoire d'installation de Maia) qui contient la clef de ".
    		                       "chiffrement (type Blowfish) utilisable pour le site. Le fait de laisser ".
	                		       "vide cette information implique qu'il ne vous sera pas possible de chiffrer ".
                			       "les messages stock&eacute;s dans la base de donn&eacute;es. Pour g&eacute;n&eacute;rer une telle clef, ".
                			       "il vous faut utiliser le programme <b>generate-key.pl</b> et sauver le ".
                			       "r&eacute;sultat dans un fichier, et mettre le nom dans le champ.";

    $lang['adminhelp_newuser_template_file'] =  "<b>%s</b> d&eacute;finit le nom du fichier (avec le chemin complet,ou alors ".
                        					    "relatif depuis le r&eacute;pertoire d'installation de Maia) qui sera ".
                        					    "utilis&eacute; comme mod&egrave;le lors de l'envoi du courriel de bienvenue ".
                        					    "pour les nouveaux utilisateurs, si le syst&egrave;me d'authentification ".
                        					    "utilis&eacute; est le mode interne. Le mod&egrave;le peut contenir les ".
                        					    "objets internes suivants, qui seront &eacute;valu&eacute;s : ".
                            					"<font color=\"red\">%%%%LOGIN%%%%</font>, " .
                                                "<font color=\"red\">%%%%PASSWORD%%%%</font>, " .
                                                "<font color=\"red\">%%%%LOGINURL%%%%</font>, et " .
                                                "<font color=\"red\">%%%%ADMINEMAIL%%%%</font>.";

    $lang['adminhelp_expiry_period'] =  "<b>%s</b> d&eacute;finit le nombre de jours durant lesquels les pourriels ".
                    				    "suspects serons gard&eacute;s. Si le d&eacute;lai est d&eacute;pass&eacute;, les pourriels en ".
				                        "question seront supprim&eacute;s, assurant un nettoyage forc&eacute; des zones de ".
                    				    "quarantaine non nettoy&eacute;es. Il est &agrave; noter que les pourriels qui ".
                    				    "sont \"confirm&eacute;s\" par les utilisateurs sont directement trait&eacute;s ".
                    				    "et effac&eacute;s, sans attendre le d&eacute;lai.";

    $lang['adminhelp_ham_cache_expiry_period'] =  "<b>%s</b> d&eacute;finit le nombre de jours durant lesquels les" .
                                                  "courriels sains serons gard&eacute;s. Si le d&eacute;lai est d&eacute;pass&eacute;, les".
	                        				      "courriels en  question seront supprim&eacute;s, assurant un ".
                        					      "nettoyage forc&eacute; des caches de courriels sains non nettoy&eacute;es." .
                        					      "Il est &agrave; noter que les courriels qui sont \"confirm&eacute;s\" par ".
                        					      "les utilisateurs sont directement trait&eacute;s et effac&eacute;s, sans ".
                        					      "attendre le d&eacute;lais.";

    $lang['adminhelp_reminder_threshold_count'] =  "<b>%s</b> d&eacute;finit &agrave; quel moment un rappel doit &ecirc;tre envoy&eacute; ".
					                               "aux utilisateurs, bas&eacute; sur le nombre d'&eacute;l&eacute;ments dans la ".
                        					       "zone de quarantaine. Ce rappel lui demandera de venir ".
                        					       "traiter les courriels, ayant atteint la limite en nombre.";

    $lang['adminhelp_reminder_threshold_size'] =  "<b>%s</b> d&eacute;finit &agrave; quel moment un rappel doit &ecirc;tre envoy&eacute; ".
                        					      "aux utilisateurs, bas&eacute; sur la taille de la zone de ".
                        					      "quarantaine. Ce rappel lui demandera de venir traiter ".
                        					      "les courriels, ayant atteint la limite d'espace disque.";

    $lang['adminhelp_reminder_template_file'] =  "<b>%s</b> d&eacute;finit le nom du fichier, (avec le chemin complet ,ou alors ".
                        					     "relatif depuis le r&eacute;pertoire d'installation de Maia) qui sera " .
					                             "utilis&eacute; pour les courriels de rappel. Le mod&egrave;le peut contenir ".
                        					     "les objets internes suivants, qui seront &eacute;valu&eacute;s : ".
                        					     "<font color=\"red\">%%%%VIRUSCOUNT%%%%</font>, " .
                                                 "<font color=\"red\">%%%%SPAMCOUNT%%%%</font>, " .
                                                 "<font color=\"red\">%%%%BANNEDCOUNT%%%%</font>, " .
                                                 "<font color=\"red\">%%%%HEADERCOUNT%%%%</font>, " .
                                                 "<font color=\"red\">%%%%VIRUSSIZE%%%%</font>, " .
                                                 "<font color=\"red\">%%%%SPAMSIZE%%%%</font>, " .
                                                 "<font color=\"red\">%%%%BANNEDSIZE%%%%</font>, " .
                                                 "<font color=\"red\">%%%%HEADERSIZE%%%%</font>, " .
                                                 "<font color=\"red\">%%%%MAIAURL%%%%</font>, " .
                                                 "<font color=\"red\">%%%%ADMINEMAIL%%%%</font>, " .
                                                 "<font color=\"red\">%%%%EXPIRYPERIOD%%%%</font>, " .
                                                 "<font color=\"red\">%%%%OLDESTITEMTTL%%%%</font>, et " .
                                                 "<font color=\"red\">%%%%OLDESTITEMAGE%%%%</font>.";

    $lang['adminhelp_reminder_login_url'] =  "<b>%s</b> d&eacute;finit l'URL qui appara&icirc;tra aux utilisateur dans ".
                        					 "les courriels de rappel, leur demandant de se connecter ".
                        					 "rapidement au syst&egrave;me, pour g&eacute;rer leur zone de quarantaine /".
                        					 "cache de courriels. Il s'agit typiquement de la page de ".
                        					 "connexion &agrave; Maia.";

    $lang['adminhelp_banner_title'] =  "<b>%s</b> D&eacute;finit le texte qui sera affich&eacute; en titre, dans la ".
                    				   "bani&egrave;re visible sur toutes les pages de Maia.";

    $lang['adminhelp_use_icons'] =  "<b>%s</b> permet d'activer ou de d&eacute;sactiver l'utilisation d'".
                    				"icones dans la barre d'outils dans toutes les pages Maia. ".
                    				"Si vous d&eacute;sactiver cette option, un texte remplacera les images.";

    $lang['adminhelp_use_logo'] =  "<b>%s</b> permet d'activer ou non l'affichage d'un logo dans la partie ".
			                       "en haut &agrave; gauche de la bani&egrave;re Maia.";

    $lang['adminhelp_logo_file'] =  "<b>%s</b> d&eacute;finit le chemin d'acc&egrave;s (relatif depuis le r&eacute;pertoire ".
                    				"d'installation de Maia) au fichier contenant l'image que vous d&eacute;sirez ".
                    				"utiliser comme logo.";

    $lang['adminhelp_logo_alt_text'] =  "<b>%s</b> d&eacute;finit le texte qui sera associ&eacute; au logo, " .
                    				    "affich&eacute; par les navigateurs qui ne pr&eacute;sentent pas les images.";

    $lang['adminhelp_logo_url'] =  "<b>%s</b> d&eacute;finit l'URL (hyperlien) associ&eacute; au logo (ou au texte le cas &eacute;ch&eacute;ant). ".
                    			   "Aucun lien ne sera cr&eacute;&eacute; si ce champ est vide.";

    $lang['adminhelp_virus_info_url'] =  "<b>%s</b> sp&eacute;cifie l'hyperlien que Maia fournit permettant &agrave; un ".
                    				     "utilisateur de chercher de l'information sur un virus en ".
				                         "particulier. La variable \"%%%%VIRUSNAME%%%%\" sera remplac&eacute;e par ".
                    				     "le nom actuel du virus, retourn&eacute; par le scanneur de virus. En cas ".
                    				     "d'utilisation d'un seul d&eacute;tecteur, il est judicieux de renvoyer vers ".
                    				     "le site web du vendeur, afin de rechercher ce nom dans la base des ".
                    				     "virus du vendeur. Une liste de ces hyperliens peut &ecirc;tre consult&eacute;e ".
                    				     "sur le site Internet de Maia. Dans le cas de multiple d&eacute;tecteurs de ".
				                         "virus ou si vous trouvez de meilleures informations, utilisez ".
                    				     "simplement Google comme moteur de recherche.";

    $lang['adminhelp_virus_lookup'] =  "<b>%s</b> donne les r&egrave;gles de traduction des noms de virus pour ".
                    				   "que Maia puisse cherche les informations sur le site Internet ".
				                       "d&eacute;fini. Par exemple, supposons que votre d&eacute;tecteur de virus ".
                    				   "retourne un nom \"Worm.Sobig.F\", mais que ce virus est identifi&eacute; ".
                    				   "sous le nom de \"worm_sobig_f\" (dans le moteur de recherche), ".
                    				   "il est alors n&eacute;cessaire de proc&eacute;der &agrave; quelques ajustements. Maia ".
                        			   "propose une s&eacute;rie de r&egrave;gles adapt&eacute;es aux produits les plus r&eacute;pandus. ".
                    				   "Enfin, il est aussi possible de n'effectuer aucune modification sur ".
                    				   "le nom, mais le mieux est de l'accorder avec le param&egrave;tre <b>%s</b>.";

    $lang['adminhelp_currency_label'] =  "<b>%s</b> d&eacute;finit le symbole mon&eacute;taire utilis&eacute; par Maia, lors de ".
                    				     "l'affichage des co&ucirc;ts. Il vous est possible de choisir un caract&egrave;re ".
                    				     "particuler (par exemple \"\$\") ou une cha&icirc;ne (\"Sfr.\"), ou alors ".
                    				     "un code HTML ( \"&amp;euro;\", \"&amp;yen;\", etc.).";

    $lang['adminhelp_bandwidth_cost'] =  "<b>%s</b> d&eacute;finit le co&ucirc;t mensuel pour un traffic de 1 Goctet sur ".
                    				     "votre site Internet, dans la monnaie locale. Ceci permet &agrave; Maia ".
				                         "d'estimer le co&ucirc;t engendr&eacute; par les diff&eacute;rents types de courriels.";

    $lang['adminhelp_enable_stats_reporting'] =  "<b>%s</b> active la collaboration de diff&eacute;rents serveurs ".
                        					     "Maia, en transmettant un r&eacute;sum&eacute; des messages rapport&eacute;s comme ".
                        					     "pourriels. Cette mise en r&eacute;seau des diff&eacute;rents serveurs ".
                        					     "augmente la pr&eacute;cision g&eacute;n&eacute;rale de d&eacute;tection de mani&egrave;re ".
                        					     "significative. Le fonctionnement de cette distribution repose ".
                        					     "uniquement sur la mise &agrave; disposition des r&eacute;sultats des r&egrave;gles, ".
                        					     "de SpamAssassin et l'adresses IP d'o&ugrave; provient le message, sans ".
                        					     "envoi de courriels. L'adresse IP est utilis&eacute;e dans un ".
                        					     "m&eacute;canisme de compteur de pourriels &eacute;mis depuis cette adresse, ".
                        					     "avec une notion temporelle. Cette liste constitu&eacute;e est ensuite ".
                        					     "ajout&eacute;e comme r&egrave;gle suppl&eacute;mentaire dans SpamAssassin, permettant ".
                        					     "aux syst&egrave;mes Maia de r&eacute;cup&eacute;rer ces informations. Une r&egrave;gle (".
                        					     "exp&eacute;rimentale) suppl&eacute;mentaire suit l'&eacute;volution des courriels ".
                        					     "pass&eacute; au travers de cette r&egrave;gle pour v&eacute;rifier le statut final (" .
                        					     "sain ou pourriel) tel qu'annonc&eacute; par vos utilisateurs. En fonction ".
                        					     "des retours, les r&egrave;gles en question sont ajust&eacute;es.";

    $lang['adminhelp_primary_report_server'] =  "<b>%s</b> d&eacute;finit le nom ou l'adressse IP du serveur primaire ".
                        					    "utilis&eacute; pour rapporter les informations statistiques. G&eacute;n&eacute;ralement ".
                        					    "on trouvera ici le site de rapport Maia Mailguard, qui r&eacute;cup&egrave;re ".
                        					    "les informations des serveurs Maia du monde entier.";

    $lang['adminhelp_primary_report_port'] =  "<b>%s</b> donne le num&eacute;ro du port utilis&eacute; pour se " .
                        					  "connecter au serveur de rapport principal. Les rapports Maia ".
                            				  "sont mieux prot&eacute;g&eacute;s en utilisant une connexion supportant ".
                        					  "SSL. Dans ce cas, le num&eacute;ro de port normalis&eacute; SSL est 443.";

    $lang['adminhelp_secondary_report_server'] =  "<b>%s</b> d&eacute;finit le nom ou l'adresse IP du serveur secondaire ".
					                              "utilis&eacute; pour rapporter les pourriels. Ces rapports seront ".
                        					      "envoy&eacute;s au serveur principal et au serveur secondaire, pour ".
					                              "autant que cette valeur soit non nulle. Ceci permet, pour ".
                        					      "une soci&eacute;t&eacute;, d'avoir ses propres serveurs r&eacute;cup&eacute;rant les rapports ".
                        					      "de pourriels, pour centraliser les efforts de d&eacute;tection.";

    $lang['adminhelp_secondary_report_port'] =  "<b>%s</b> donne le num&eacute;ro du port utilis&eacute; pour se " .
                        					    "connecter au serveur de rapport secondaire. Les rapports Maia ".
                        					    "sont mieux prot&eacute;g&eacute;s en utilisant une connexion supportant ".
                        					    "SSL. Dans ce cas, le num&eacute;ro de port normalis&eacute; SSL est 443.";

    $lang['adminhelp_reporter_sitename'] =  "<b>%s</b> d&eacute;finit le nom de votre site qui sera utilis&eacute; lors des ".
                        					"rapports sur les pourriels (usuellement, le nom de votre soci&eacute;t&eacute;). ".
                        					"Ce nom appara&icirc;tra dans la liste des rapports.";

    $lang['adminhelp_reporter_username'] =  "<b>%s</b> d&eacute;finit le nom du rapporteur (Reporter ID) utilis&eacute; par le " .
                        					"script pour se connecter au serveur de rapports. Pour obtenir un ".
                        					"compte pour votre site, veuillez utiliser la page %s.";

    $lang['adminhelp_reporter_registration'] =  "Enregistrement des rapports Maia";

    $lang['adminhelp_reporter_password'] =  "<b>%s</b> donne le mot de passe utilis&eacute; par les scripts Maia ".
                          				    "pour s'annoncer sur le serveur de rapport. Ceci doit correspondre ".
				                            "au mot de passe que vous avez choisi lors de votre demande de ".
                    				        "compte (ReporterID).";

    $lang['adminhelp_enable_charts'] =  "<b>%s</b> active ou d&eacute;sactive la cr&eacute;ation par Maia de graphiques pour ".
				                        "les pages de statistiques. Pour avoir cette fonction activ&eacute;e, il vous ".
                    				    "faut aussi lib&eacute;rer l'option <b>%s</b>. En outre, il est possible d'avoir ".
                    				    "une g&eacute;n&eacute;ration dynamique des graphiques, lors de la demande de la page, ".
                    				    "ou alors statiques, bas&eacute; sur une g&eacute;n&eacute;ration &agrave; heure fixe. Se reporter ".
                    				    "&agrave; <b>%s</b> pour plus de d&eacute;tails.";

    $lang['adminhelp_chart_ham_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
                    				       "repr&eacute;senter les courriels sains confirm&eacute;s.";

    $lang['adminhelp_chart_spam_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
                                            "repr&eacute;senter les pourriels confirm&eacute;s.";

    $lang['adminhelp_chart_virus_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
	                        			     "repr&eacute;senter les virus et autre malware.";

    $lang['adminhelp_chart_fp_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
                    				      "repr&eacute;senter les faux positifs";

    $lang['adminhelp_chart_fn_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
                				          "repr&eacute;senter les faux n&eacute;gatifs";

    $lang['adminhelp_chart_suspected_ham_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
                            						 "repr&eacute;senter les pourriels suspect&eacute;s.";

    $lang['adminhelp_chart_suspected_spam_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
						                              "repr&eacute;senter les pourriels suspect&eacute;s.";

    $lang['adminhelp_chart_wl_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
                    				      "repr&eacute;senter les &eacute;l&eacute;ments envoy&eacute;s par des exp&eacute;diteurs en liste blanche.";

    $lang['adminhelp_chart_bl_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e dans les graphiques pour ".
                    				      "repr&eacute;senter les &eacute;l&eacute;ments envoy&eacute;s par des exp&eacute;diteurs en liste noire.";

    $lang['adminhelp_chart_background_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e pour le fond des graphiques.";

    $lang['adminhelp_chart_font_colour'] =  "<b>%s</b> d&eacute;finit la couleur utilis&eacute;e pour les caract&egrave;res.";

    $lang['adminhelp_chart_autogeneration_interval'] =  "<b>%s</b> d&eacute;termine l'intervalle (en minutes) entre les ".
                            						    "mise &agrave; jour des graphiques. Si vous d&eacute;finissez une ".
						                                "valeur nulle, cette option n'est pas active, assurant que ".
                            						    "la g&eacute;n&eacute;ration des graphiques se fait de mani&egrave;re dynamique, ".
						                                "&agrave; chaque requ&ecirc;te des utilisateurs. Pour des sites fortement ".
                            						    "utilis&eacute;s, il est judicieux de demander une g&eacute;n&eacute;ration ".
						                                "statique pour &eacute;viter la consommation intensive des ressources " .
                            						    "du syst&egrave;me.";

    // Statistics
    $lang['adminhelp_reset_stats'] =  "<b>%s</b> permet la remise &agrave; z&eacute;ro des compteurs de Maia, ".
                    				  "y compris ceux pour les virus, les r&egrave;gles de SpamAssassin ".
                    				  "et les courriels. Par contre, les statistques pour les courriels ".
                    				  "sains et pourriels suspect&eacute;s sont conserv&eacute;s, car leur valeur sont ".
                    				  "directement &eacute;valu&eacute;es depuis les zone de quarantaine / cache.";

?>
