<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

// Menu items
    $lang['menu_welcome'] = "Bienvenue";
    $lang['menu_stats'] =  "Statistiques";
    $lang['menu_settings'] =  "Configuration";
    $lang['menu_whiteblacklist'] =  "Liste blanche/noire";
    $lang['menu_quarantine'] =  "Quarantaine";
    $lang['menu_report'] =  "Rapporte comme Pourriel";
    $lang['menu_admin'] =  "Administration";
    $lang['menu_help'] =  "Aide";
    $lang['menu_logout'] =  "Quitter";

    // Text messages
    $lang['text_version'] =  "Version";
    $lang['text_all_users'] =  "Tous les utilisateurs";
    $lang['text_day'] =  "jour";
    $lang['text_efficiency'] =  "Efficacit&eacute;";
    $lang['text_sensitivity'] =  "Sensibilit&eacute;";
    $lang['text_specificity'] =  "Sp&eacute;cificit&eacute;";
    $lang['text_ppv'] =  "PPV";
    $lang['text_npv'] =  "NPV";
    $lang['text_false_positive'] =  "Faux positifs";
    $lang['text_false_negative'] =  "Faux n&eacute;gatifs";
    
    $lang['powered_by'] = "Powered by Maia Mailguard - http://www.maiamailguard.com";
    
    $lang['text_truncate_subject'] = "Tronquer les lignes non-email en:  (caract&egrave;res)";
    $lang['text_truncate_email'] = "Tronquer les lignes email en: (caract&egrave;res)";

    // Links
    $lang['link_systemwide'] =  "Afficher les statistiques du syst&egrave;me";
    $lang['link_personal'] =  "Afficher vos statistiques personnelles";
    $lang['link_viruses'] =  "Afficher les statistiques des virus";
    $lang['link_rules'] =  "Afficher les statistiques des r&egrave;gles SpamAssassin";

    // Table headers
    $lang['header_score'] =  "Score";
    $lang['header_count'] =  "Nombre";
    $lang['header_size'] =  "Taille";
    $lang['header_min'] =  "Min";
    $lang['header_max'] =  "Max";
    $lang['header_average'] =  "Moy";
    $lang['header_bandwidth'] =  "Bande Passante";
    $lang['header_percent'] =  "%";
    $lang['header_cost'] =  "Co&ucirc;t";
    $lang['header_items'] =  "&Eacute;l&eacute;ments";
    $lang['header_type'] =  "Type de courriel";
    $lang['header_user'] =  "Statistiques de l'utilisateur : %s";
    $lang['header_systemwide'] =  "Statistiques globales";
    $lang['header_spam_score'] =  "Score";
    $lang['header_rule_triggered'] =  "R&egrave;gles utilis&eacute;es";
    $lang['header_explanation'] =  "Explication";

    $lang['array_header'] =  array("ham"               => "Courriels (ham) confirm&eacute;s",
                                      "suspected_ham"  => "Courriels (ham) &agrave; confirmer",
                                      "suspected_spam" => "Pourriels (spam) &agrave; confirmer",
                                      "spam"           => "Pourriels (spam) confirm&eacute;s",
                                      "virus"          => "Virus / Malware",
                                      "fp"             => "Faux positifs",
                                      "fn"             => "Faux n&eacute;gatifs",
                                      "wl"             => "Exp&eacute;diteurs en liste blanche",
                                      "bl"             => "Exp&eacute;diteurs en liste noire",
                                      "bad_header"     => "En-t&ecirc;tes courriel invalides",
                                      "banned_file"    => "Pi&egrave;ces jointes interdites",
                                      "oversized"      => "Courriels trop volumineux");

    $lang['array_count'] =  array("ham"                => "Courriels re&ccedil;us",
                                      "suspected_ham"  => "Courriels &agrave; confirmer re&ccedil;us",
                                      "suspected_spam" => "Pourriel &agrave; confirmer (en quarantaine) re&ccedil;us",
                                      "spam"           => "Pourriels confirm&eacute;s re&ccedil;us",
                                      "virus"          => "Virus re&ccedil;us",
                                      "fp"             => "Courriels identif&eacute;s comme pourriels (faux positifs)",
                                      "fn"             => "Pourriels identifi&eacute; comme courriels (faux n&eacute;gatifs) ",
                                      "wl"             => "Courriels re&ccedil;us depuis un exp&eacute;diteur en liste blanche",
                                      "bl"             => "Courriels re&ccedil;us depuis un exp&eacute;diteur en liste noire",
                                      "bad_header"     => "Courriels comportant des en-t&ecirc;tes non valides",
                                      "banned_file"    => "Courriels avec pi&egrave;ces jointes interdites",
                                      "oversized"      => "Courriels trop volumineux");

    $lang['array_arrivals'] =  array("ham"             => "Arriv&eacute;e de courriels",
                                      "suspected_ham"  => "Arriv&eacute;e de courriels &agrave; valider",
                                      "suspected_spam" => "Arriv&eacute;e de pourriels &agrave; valider",
                                      "spam"           => "Arriv&eacute;e de pourriels confirm&eacute;s",
                                      "virus"          => "Arriv&eacute;e de virus",
                                      "fp"             => "Erreurs de faux positif",
                                      "fn"             => "Erreurs de faux n&eacute;gatif",
                                      "wl"             => "Arriv&eacute;e d'exp&eacute;diteurs en liste blanche",
                                      "bl"             => "Arriv&eacute;e d'exp&eacute;diteurs en liste noire",
                                      "bad_header"     => "Arriv&eacute;e de courriels comportant des en-t&ecirc;tes non valides",
                                      "banned_file"    => "Arriv&eacute;e de courriels avec pi&egrave;ces jointes interdites",
                                      "oversized"      => "Arriv&eacute;e de courriels trop volumineux");

    $lang['array_highest_score'] =  array("ham"        => "Score le plus &eacute;lev&eacute; pour un courriel",
                                      "suspected_ham"  => "Score le plus &eacute;lev&eacute; pour un courriel &agrave; confirmer",
                                      "suspected_spam" => "Score le plus &eacute;lev&eacute; pour un pourriel &agrave; confirmer",
                                      "spam"           => "Score le plus &eacute;lev&eacute; pour un pourriel",
                                      "virus"          => "",
                                      "fp"             => "Score le plus &eacute;lev&eacute; pour un faux positif",
                                      "fn"             => "Score le plus &eacute;lev&eacute; pour un faux n&eacute;gatif",
                                      "wl"             => "",
                                      "bl"             => "",
                                      "bad_header"     => "",
                                      "banned_file"    => "",
                                      "oversized"      => "");

    $lang['array_lowest_score'] =  array("ham"         => "Score le plus faible pour un courriel sain",
                                      "suspected_ham"  => "Score le plus faible pour un courriel &agrave; confirmer",
                                      "suspected_spam" => "Score le plus faible pour un pourriel &agrave; confirmer",
                                      "spam"           => "Score le plus faible pour un pourriel",
                                      "virus"          => "",
                                      "fp"             => "Score le plus faible pour un faux positif",
                                      "fn"             => "Score le plus faible pour un faux n&eacute;gatif",
                                      "wl"             => "",
                                      "bl"             => "",
                                      "bad_header"     => "",
                                      "banned_file"    => "",
                                      "oversized"      => "");

    $lang['array_average_score'] =  array("ham"        => "Score moyen des courriels",
                                      "suspected_ham"  => "Score moyen des courriels &agrave; confirmer",
                                      "suspected_spam" => "Score moyen des pourriels &agrave; confirmer",
                                      "spam"           => "Score moyen des pourriels",
                                      "virus"          => "",
                                      "fp"             => "Score moyen des faux positif",
                                      "fn"             => "Score moyen des faux n&eacute;gatifs",
                                      "wl"             => "",
                                      "bl"             => "",
                                      "bad_header"     => "",
                                      "banned_file"    => "",
                                      "oversized"      => "");

    $lang['array_largest_size'] =  array("ham"         => "Taille du plus gros courriel",
                                      "suspected_ham"  => "Taille du plus gros courriel &agrave; confirmer",
                                      "suspected_spam" => "Taille du plus gros pourriel &agrave; confirmer",
                                      "spam"           => "Taille du plus gros pourriel",
                                      "virus"          => "Taille du plus gros courriel contenant un virus",
                                      "fp"             => "Taille du plus gros faux positif",
                                      "fn"             => "Taille du plus gros faux n&eacute;gatif",
                                      "wl"             => "Taille du plus gros courriel en liste blanche",
                                      "bl"             => "Taille du plus gros courriel en liste noire",
                                      "bad_header"     => "Taille du plus gros courriel contenant des en-t&ecirc;tes non valides",
                                      "banned_file"    => "Taille du plus gros courriel contenant une pi&egrave;ce jointe interdite",
                                      "oversized"      => "Taille du plus gros courriel trop volumineux");

    $lang['array_smallest_size'] =  array("ham"        => "Taille du plus petit courriel",
                                      "suspected_ham"  => "Taille du plus petit courriel &agrave; confirmer",
                                      "suspected_spam" => "Taille du plus petit pourriel &agrave; confirmer",
                                      "spam"           => "Taille du plus petit pourriel",
                                      "virus"          => "Taille du plus petit courriel contenant un virus",
                                      "fp"             => "Taille du plus petit faux positif",
                                      "fn"             => "Taille du plus petit faux n&eacute;gatif",
                                      "wl"             => "Taille du plus petit courriel en liste blanche",
                                      "bl"             => "Taille du plus petit courriel en liste noire",
                                      "bad_header"     => "Taille du plus petit courriel contenant des en-t&ecirc;tes non valides",
                                      "banned_file"    => "Taille du plus petit courriel contenant une pi&egrave;ce joite interdite",
                                      "oversized"      => "Taille du plus petit courriel trop volumineux");

    $lang['array_average_size'] =  array("ham"         => "Taille moyenne d'un courriel",
                                      "suspected_ham"  => "Taille moyenne d'un courriel &agrave; confirmer",
                                      "suspected_spam" => "Taille moyenne d'un pourriel &agrave; confimer",
                                      "spam"           => "Taille moyenne d'un pourriel",
                                      "virus"          => "Taille moyenne d'un courriel contenant un virus",
                                      "fp"             => "Taille moyenne d'un faux positif",
                                      "fn"             => "Taille moyenne d'un faux n&eacute;gatif",
                                      "wl"             => "Taille moyenne d'un courriel en liste blanche",
                                      "bl"             => "Taille moyenne d'un courriel en liste noire",
                                      "bad_header"     => "Taille moyenne d'un courriel contenant des en-t&ecirc;tes non valide",
                                      "banned_file"    => "Taille moyenne d'un courriel contenant une pi&egrave;ce jointe interdite",
                                      "oversized"      => "Taille moyenne d'un courriel trop volumineux");

    $lang['array_bandwidth'] =  array("ham"            => "Bande passante pour les courriels",
                                      "suspected_ham"  => "Bande passante pour les courriels &agrave; confirmer",
                                      "suspected_spam" => "Bande passante pour les pourriels &agrave; confirmer",
                                      "spam"           => "Bande passante pour les pourriels",
                                      "virus"          => "Bande passante pour les courriels contenant un virus",
                                      "fp"             => "Bande passante pour les faux positifs",
                                      "fn"             => "Bande passante pour les faux n&eacute;gatifs",
                                      "wl"             => "Bande passante pour les courriels en liste blanche",
                                      "bl"             => "Bande passante pour les courriels en liste noire",
                                      "bad_header"     => "Bande passante pour les courriels contenant des en-t&ecirc;tes non valides",
                                      "banned_file"    => "Bande passante pour les courriels contenant une pi&egrave;ce jointe interdite",
                                      "oversized"      => "Bande passante pour les courriels trop volumineux");

    $lang['array_cost'] =  array(     "ham"            => "Co&ucirc;t pour les courriels",
                                      "suspected_ham"  => "Co&ucirc;t pour les courriels &agrave; confirmer",
                                      "suspected_spam" => "Co&ucirc;t pour les pourriels &agrave; confirmer",
                                      "spam"           => "Cout pour les pourriels",
                                      "virus"          => "Co&ucirc;t pour les courriels contenant un virus",
                                      "fp"             => "Co&ucirc;t pour les faux positifs",
                                      "fn"             => "Co&ucirc;t pour les fauc n&eacute;gatifs",
                                      "wl"             => "Co&ucirc;t pour les courriels en liste blanche",
                                      "bl"             => "Co&ucirc;t pour les courriels en liste noire",
                                      "bad_header"     => "Co&ucirc;t pour les courriels contenant des en-t&ecirc;tes non valide",
                                      "banned_file"    => "Co&ucirc;t pour les courriels contenant une pi&egrave;ce jointe interdite",
                                      "oversized"      => "Co&ucirc;t pour les courriels trop volumineux");

    $lang['array_percentage'] =  array("ham"           => "en pourcentage du total de courriels re&ccedil;us",
                                      "suspected_ham"  => "en pourcentage du total de courriels re&ccedil;us",
                                      "suspected_spam" => "en pourcentage du total de courriels re&ccedil;us",
                                      "spam"           => "en pourcentage du total de courriels re&ccedil;us",
                                      "virus"          => "en pourcentage du total de courriels re&ccedil;us",
                                      "fp"             => "en pourcentage du total de courriels re&ccedil;us",
                                      "fn"             => "en pourcentage du total de courriels re&ccedil;us",
                                      "wl"             => "en pourcentage du total de courriels re&ccedil;us",
                                      "bl"             => "en pourcentage du total de courriels re&ccedil;us",
                                      "bad_header"     => "en pourcentage du total de courriels re&ccedil;us",
                                      "banned_file"    => "en pourcentage du total de courriels re&ccedil;us",
                                      "oversized"      => "en pourcentage du total de courriels re&ccedil;us");
?>
