<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Options de filtrage par d&eacute;faut pour le domaine";

    // Table headers
    $lang['header_domain'] =  "Domaine";
    $lang['header_admins'] =  "Administrateurs du domaine";
    $lang['header_revoke'] =  "Supprimer un administrateur";
    $lang['header_admin_name'] =  "Adminsitrateur";
    $lang['header_add_administrator'] =  "Ajouter un administrateur";

    // Text labels
    $lang['text_yes'] =  "Oui";
    $lang['text_no'] =  "Non";
    $lang['text_virus_scanning'] =  "V&eacute;rification des virus";
    $lang['text_enabled'] =  "Activ&eacute;";
    $lang['text_disabled'] =  "Desactiv&eacute;";
    $lang['text_quarantined'] =  "Mis en quarantaine";
    $lang['text_discarded'] =  "Effac&eacute;";
    $lang['text_labeled'] =  "Mettre une &eacute;tiquette";
    $lang['text_detected_viruses'] =  "Les courriels contenant un virus seront ...";
    $lang['text_spam_filtering'] =  "Filtrage de pourriel";
    $lang['text_detected_spam'] =  "Les pourriels d&eacute;tect&eacute;s seront ...";
    $lang['text_prefix_subject'] =  "Ajouter un pr&eacute;fix dans le sujet du pourriel";
    $lang['text_add_spam_header'] =  "Ajoute une en-t&ecirc;te X-Spam: quand le score est >=";
    $lang['text_consider_mail_spam'] =  "Le mail est un pourriel si le score est >=";
    $lang['text_quarantine_spam'] =  "Le pourriel est mis en quarantaine si le score est >=";
    $lang['text_attachment_filtering'] =  "Filtrage sur les pi&egrave;ces jointes";
    $lang['text_mail_with_attachments'] =  "Les courriels contenant une pi&egrave;ce jointe dangereuse seront...";
    $lang['text_bad_header_filtering'] =  "Filtrage des en-t&ecirc;tes non valides";
    $lang['text_mail_with_bad_headers'] =  "Les courriels contenant des en-t&ecirc;tes non valides seront ...";
    $lang['text_settings_updated'] =  "Vos options de filtrage par d&eacute;faut pour le domaine sont mises &agrave; jour.";
    $lang['text_system_default'] =  "Options par d&eacute;faut pour tout le syst&egrave;me";
    $lang['text_no_admins'] =  "Il n'y a pas d'administrateur s&eacute;l&eacute;ctionn&eacute; pour ce domaine.";
    $lang['text_no_available_admins'] =  "Il n'existe pas d'utilisateur pour administrer ce domaine.";
    $lang['text_administrators_added'] =  "Le(s) nouvel(aux) administrateur(s) est(sont) ajout&eacute;(s) pour ce domaine.";
    $lang['text_admins_revoked'] =  "Les privil&egrave;ges des administrateurs s&eacute;l&eacute;ctionn&eacute;s sont supprim&eacute;s.";
    $lang['text_cache_ham_question'] =  "Mettre les courriels sains en cache (pour apprentissage) ?";
    $lang['text_enable_user_autocreation'] =  "Activer la cr&eacute;ation automatique des utilisateurs ?";
    $lang['text_domain_theme'] = "Th&egrave;me par d&eacute;faut pour le domaine";

    // Buttons
    $lang['button_reset'] =  "Effacer";
    $lang['button_update_domain'] =  "Mise &agrave; jour des options par d&eacute;faut du domaine";
    $lang['button_revoke'] =  "Supprimer les privil&egrave;ges des administrateurs s&eacute;l&eacute;ctionn&eacute;s";
    $lang['button_grant'] =  "Accorder les privil&egrave;ges administrateur";

    // Links
    $lang['link_domain_settings'] =  "Retour aux options du domaine";
    $lang['link_admin_domains'] =  "Retour au menu d'administration du domaine";
?>
