<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Zone de quarantaine";

    // Table headers
    $lang['header_spam'] =  "Pourriel &agrave; confirmer";
    $lang['header_viruses'] =  "Virus / Malware";
    $lang['header_banned_files'] =  "Pi&egrave;ces jointes interdites";
    $lang['header_bad_headers'] =  "En-t&ecirc;tes non valides";
    $lang['header_quarantine_contents'] =  "Contenu de la quarantaine";

    // Text labels
    $lang['text_item'] =  "Courriel";
    $lang['text_items'] =  "Courriels";
    $lang['text_score'] =  "Score";
    $lang['text_received'] =  "Re&ccedil;u";
    $lang['text_from'] =  "Exp&eacute;diteur";
    $lang['text_to'] =  "Destinataire";
    $lang['text_ham'] =  "Courriel sain (Ham) ?";
    $lang['text_spam'] =  "Pourriel (Spam) ?";
    $lang['text_rescue'] =  "Sain (Ham) !";
    $lang['text_delete'] =  "Supprimer";
    $lang['text_subject'] =  "Sujet ";
    $lang['text_virus'] =  "Virus";
    $lang['text_file_name'] =  "Nom de fichier";
    $lang['text_no_subject'] =  "pas de sujet";
    $lang['text_empty'] =  "Votre zone de quarantaine est vide.";
    $lang['text_updated'] =  "Votre zone de quarantaine a &eacute;t&eacute; mise &agrave; jour.";
    $lang['text_of'] =  "sur";
    $lang['text_spam_confirmed'] =  "%d pourriels ont &eacute;t&eacute; confirm&eacute;s";
    $lang['text_spam_rescued'] =  "%d pourriels &agrave; confirmer ont &eacute;t&eacute; r&eacute;cup&eacute;r&eacute;s";
    $lang['text_spam_deleted'] =  "%d pourriels &agrave; confirmer ont &eacute;t&eacute; supprim&eacute;s";
    $lang['text_viruses_rescued'] =  "%d courriels avec virus/malware ont &eacute;t&eacute;s r&eacute;cup&eacute;r&eacute;s";
    $lang['text_viruses_deleted'] =  "%d courriels avec virus/malware ont &eacute;t&eacute;s supprim&eacute;s";
    $lang['text_attachments_rescued'] =  "%d courriels avec pi&egrave;ces jointes interdites ont &eacute;t&eacute; r&eacute;cup&eacute;r&eacute;s";
    $lang['text_attachments_deleted'] =  "%d courriels avec pi&egrave;ces jointes interdites ont &eacute;t&eacute;s supprim&eacute;s";
    $lang['text_headers_rescued'] =  "%d courriels corrompus ont &eacute;t&eacute; r&eacute;cup&eacute;r&eacute;s";
    $lang['text_headers_deleted'] =  "%d courriels corrompus ont &eacute;t&eacute; supprim&eacute;s";
    $lang['text_suspected_spam_item'] =  "Pourriel &agrave; confirmer";
    $lang['text_suspected_spam_items'] =  "Pourriels &agrave; confirmer";
    $lang['text_virus_item'] =  "Contient Virus/Malware";
    $lang['text_virus_items'] =  "Contient Virus/Malware";
    $lang['text_banned_file_item'] =  "Pi&egrave;ce jointe interdite";
    $lang['text_banned_file_items'] =  "Pi&egrave;ces jointes interdites";
    $lang['text_bad_header_item'] =  "Courriel corrompu";
    $lang['text_bad_header_items'] =  "Courriels corrompus";


    // Button text
    $lang['button_confirm_spam'] =  "TOUS ces courriels sont des pourriels";
    $lang['button_delete_viruses'] =  "Supprimer ces virus";
    $lang['button_delete_attachments'] =  "Supprimer ces fichiers";
    $lang['button_delete_headers'] =  "Supprimer ces courriels corrompus";
    $lang['button_confirm'] =  "Confirmer le statuts de ces courriels";
    $lang['button_delete_all_items'] =  "Supprimer TOUS les courriels en quarantaine";

    // Link text
    $lang['link_prev'] =  "Pr&eacute;c&eacute;dent";
    $lang['link_next'] =  "Suivant";
    $lang['link_quarantine'] =  "Retour au menu de la quarantaine";
    $lang['link_welcome'] = "Retour &agrave; la page d'accueil";
?>
