<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Configuration des filtres des courriels";

    // Table headers
    $lang['header_addresses'] =  "Adresses de courriel";
    $lang['header_miscellaneous'] =  "Options diverses";
    $lang['header_address'] =  "Adresse de courriel";
    $lang['header_login_info'] =  "Informations de connexion";

    // Text messages
    $lang['text_username'] =  "Nom d'utilisateur";
    $lang['text_email_address'] =  "Adresse de courriel";
    $lang['text_password'] =  "Mot de passe";
    $lang['text_reminders'] =  "Envoi des rappels de quarantaine ?";
    $lang['text_charts'] =  "Affichage des graphiques ?";
    $lang['text_yes'] =  "Oui";
    $lang['text_no'] =  "Non";
    $lang['text_virus_scanning'] =  "D&eacute;tection de virus";
    $lang['text_enabled'] =  "Activ&eacute;";
    $lang['text_disabled'] =  "Desactiv&eacute;";
    $lang['text_quarantined'] =  "Mis en quarantaine";
    $lang['text_labeled'] =  "Etiquett&eacute;";
    $lang['text_discarded'] =  "Jet&eacute;";
    $lang['text_detected_viruses'] =  "Les courriels contenant des virus seront ...";
    $lang['text_spam_filtering'] =  "Filtre a pourriels";
    $lang['text_detected_spam'] =  "Les pourriels seront ...";
    $lang['text_prefix_subject'] =  "Ajouter un pr&eacute;fix dans le sujet des pourriels";
    $lang['text_add_spam_header'] =  "Ajouter une en-t&ecirc;te X-Spam: lorsque le score est de";
    $lang['text_consider_mail_spam'] =  "Le score d&eacute;terminant un pourriel est de";
    $lang['text_quarantine_spam'] =  "Le score d&eacute;teminant la mise en quarantaine est de";
    $lang['text_attachment_filtering'] =  "Filtrage sur les pi&egrave;ces jointes";
    $lang['text_mail_with_attachments'] =  "Les courriels contenant une pi&egrave;ce jointe dangereuse seront...";
    $lang['text_bad_header_filtering'] =  "Filtrage des en-t&ecirc;tes non valides";
    $lang['text_mail_with_bad_headers'] =  "Les courriels contenant des en-t&ecirc;tes non valides seront ...";
    $lang['text_settings_updated'] =  "Vos options de filtrage sont mises &agrave; jour.";
    $lang['text_address_added'] =  "L'adresse %s a &eacute;t&eacute; li&eacute;e &agrave; votre compte.";
    $lang['text_login_failed'] =  "Erreur d'authentification pour '%s'.";
    $lang['text_primary'] =  "Adresse principale";
    $lang['text_no_addresses_linked'] =  "Il n'y a pas d'adresse li&eacute;e avec ce compte.";
    $lang['text_new_primary_email'] =  "%s est a pr&eacute;sent votre adresse principale.";
    $lang['text_language'] =  "Langue de l'affichage";
    $lang['text_charset'] =  "Jeu de caract&egrave;re utilis&eacute; pour l'affichage";
    $lang['text_theme'] = "Th&egrave;me"; 
    $lang['text_spamtrap'] =  "Compte \"pot de miel\" pour les pourriels ?";
    $lang['text_auto_whitelist'] =  "Ajouter les exp&eacute;diteurs de couriers r&eacute;cup&eacute;r&eacute;s dans votre liste blanche ?";
    $lang['text_items_per_page'] =  "Nombre de courriels affich&eacute;s par page ?";
    $lang['text_new_login_name'] =  "Nouveau nom d'utilisateur";
    $lang['text_new_password'] =  "Nouveau mot de passe";
    $lang['text_confirm_new_password'] =  "Confirmation du nouveau mot de passe";
    $lang['text_login_name_empty'] =  "Un nom d'utilisateur est obligatoire.";
    $lang['text_login_name_not_allowed'] =  "Les noms d'utilisateurs ne peuvent pas commencer par un signe '@'.";
    $lang['text_password_empty'] =  "Un mot de passe est n&eacute;cessaire et la confirmation doit &ecirc;tre fournie.";
    $lang['text_password_mismatch'] =  "Le mot de passe et la confirmation ne correspondent pas.";
    $lang['text_login_name_exists'] =  "Le nom d'utilisateur d&eacute;sir&eacute; est d&eacute;j&agrave; utilis&eacute;.";
    $lang['text_password_updated'] =  "Votre mot de passe a &eacute;t&eacute; chang&eacute;.";
    $lang['text_credentials_updated'] =  "Votre nom d'utilisateur et votre mot de passe ont &eacute;t&eacute; chang&eacute;s.";

    // Buttons
    $lang['button_add_email_address'] =  "Ajouter une adresse de courriel";
    $lang['button_reset'] =  "Effacer";
    $lang['button_update_misc'] =  "Mise &agrave; jour des options diverses";
    $lang['button_update_address'] =  "Mise &agrave; jour des options pour cette adresse";
    $lang['button_update_all_addresses'] =  "Mise &agrave; jour des options pour TOUTES les adresses";
    $lang['button_make_primary'] =  "D&eacute;finir comme adresse principal";
    $lang['button_change_login_info'] =  "Mettre &agrave; jour les informations de connexion";

    // Links
    $lang['link_settings'] =  "Retour sur vos options";
?>
