<?php
    /*
     * $Id: welcome.php 631 2005-05-03 19:19:22Z jleaver $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Bienvenue sur Maia Mailguard!";
    $lang['text_welcome_first_time'] = "Bienvenue sur Maia Mailguard. Il semblerait que ce soit votre premi&egrave;re connexion sur ce ".
                                       "syst&egrave;me. Merci de lire attentivement ce message afin de comprendre l'importance de votre ".
                                       "participation dans notre lutte contre les pourriels (Spam).<P>" .
                                       "Tout d'abord, pour activer rapidement la protection anti-spam de votre compte, veuillez ".
                                       "choisir un des niveaux de protection ci dessous et cliquer sur \"Changer le niveau\". " .
                                       "Le niveau \"&Eacute;lev&eacute;\" est utilisable sans danger et est m&ecirc;me recommand&eacute;.<P>" .
                                       "Maia Mailguard filtre votre courrier et emp&ecirc;che la plus grande partie des contenus " .
                                       "ind&eacute;sirables de se retrouver dans votre boite de r&eacute;ception. Si Maia se trompait, rien " .
                                       "n'est perdu car le mail non d&eacute;livr&eacute; est automatiquement plac&eacute; en quarantaine. La zone de " .
                                       "quarantaine est directement accessible depuis cette page afin de vous permettre de " .
                                       "r&eacute;cup&eacute;rer un courriel mal identifi&eacute; ou de confirmer que le pourriel suspect&eacute; en est bien " .
                                       "un. Il vous permet aussi d'aider le filtre &agrave; apprendre de ses erreurs en indiquant les " .
                                       "faux n&eacute;gatifs (spams/pourriels consid&eacute;r&eacute;s &agrave; tort comme des courriels sains (Ham))" .
                                       "en les marquant depuis la zone de cache des courriels sains, zone dans laquelle sont " .
                                       "stock&eacute;s les messages r&eacute;cents consid&eacute;r&eacute;s comme sains";
    
    $lang['text_welcome_intro'] = "<P>Participez &agrave; la lutte contre les messages ind&eacute;sirables avec Maia Mailguard. " .
                                  "Les messages indiqu&eacute;s dans la zone du bas vous permettent d'apprendre &agrave; Maia la diff&eacute;rence " .
                                  "entre courriels sains (courriels ou Ham) et les pourriels (messages ind&eacute;sirables ou Spam). " .
                                  "Merci de prendre un peu de temps pour v&eacute;rifier que tous les messages sont correctement " .
                                  "identifi&eacute;s ; si vous n'avez pas le temps de le faire, il vaut mieux d&eacute;truire les messages " .
                                  "plut&ocirc;t que de les identifier n'importe comment.<P>" .
                                  "Gardez &agrave; l'esprit que Maia va informer d'autres services antispams lorsque vous confirmez " .
                                  "un spam. En effectuant ceci consciencieusement, vous aiderez &agrave; lutter contre ce fl&eacute;au." ;
                                  
    $lang['text_welcome_current_level'] = "Niveau de protection actuel:";
     
    $lang['text_welcome_custom_level'] = "**Le niveau actuel de protection a &eacute;t&eacute; d&eacute;fini dans les param&egrave;tres personnalis&eacute;s :<br> ".
                                         "Utilisez l'&eacute;cran de Param&eacute;trage pour les mettre &agrave; jour ou choisissez un niveau " .
                                         "pr&eacute;d&eacute;fini dans la liste.";

    $lang['text_welcome_spam_blocked'] = "pourriels ont &eacute;t&eacute; bloqu&eacute;s pour vous";
    $lang['text_welcome_virus_blocked'] = "virus ont &eacute;t&eacute; bloqu&eacute;s pour vous";
    $lang['text_welcome_spam_blocked_system'] = "pourriels ont &eacute;t&eacute; bloqu&eacute;s globalement pour le syst&egrave;me";
    $lang['text_welcome_virus_blocked_system'] = "virus ont &eacute;t&eacute; bloqu&eacute;s globalement pour le syst&egrave;me";
    $lang['button_delete_all_items'] = "Supprimer tous les messages";
    $lang['button_change_protection'] = "Changer le niveau";
    
    $lang['radio_protection'] = array(  'off'       => "D&eacute;sactiv&eacute;",
		 								'low'       => "Faible",
     									'medium'    => "Moyen",
										'high'      => "&Eacute;lev&eacute;",
										'custom'    => "Personnalis&eacute;");
    
    $lang['banner_subtitle'] = "Bienvenue";
    
    $lang['text_cache_spam'] = "Vous avez <b>%d</b> pourriels (Spam) &agrave; confirmer.  <br>Cliquez <a href=\"%s\">ici</a> pour " .
                               "confirmer ou pour r&eacute;cup&eacute;rer un message bloqu&eacute; &agrave; tort (faux positif).";
    $lang['text_cache_virus'] = "Vous avez <b>%d</b> courriels infect&eacute;s par un virus.  <br>Cliquez <a href=\"%s\">ici</a> pour " .
                                "confirmer ou pour r&eacute;cup&eacute;rer un message bloqu&eacute; &agrave; tort";
    $lang['text_cache_banned'] = "Vous avez <b>%d</b> courriels contenant des fichiers bloqu&eacute;s (interdits).  <br>Cliquez " .
                                 "<a href=\"%s\">ici</a> pour les supprimer ou pour r&eacute;cup&eacute;rer un message bloqu&eacute; &agrave; tort.";
    $lang['text_cache_header'] = "Vous avez <b>%d</b> courriels contenant des entes invalides. <br>Cliquez <a href=\"%s\">" .
                                 "ici</a> pour les effacer ou pour r&eacute;cup&eacute;rer un message bloqu&eacute; &agrave; tort.";
    $lang['text_cache_ham'] = "Vous avez <b>%d</b> courriels dans le cache des courriels sains. <br>Cliquez <a href=\"%s\">" .
                              "ici</a> pour les confirmer ou pour indiquer un pourriel non bloqu&eacute; (faux n&eacute;gatif).";
    $lang['action_ham_cache']   = "Confirmer/Infirmer";
    $lang['action_spam_cache']  = "Confirmer/R&eacute;cup&eacute;rer";
    $lang['action_virus_cache'] = "Supprimer/R&eacute;cup&eacute;rer";
    $lang['action_banned_cache'] = "Supprimer/R&eacute;cup&eacute;rer";
    $lang['action_header_cache'] = "Supprimer/R&eacute;cup&eacute;rer";
    
?>
