<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    //$lang['banner_subtitle'] =  "Domain Mail Filter Defaults";

    // Table headers
    $lang['header_domain'] =  "Domain";
    $lang['header_admins'] =  "Domain Administrators";
    $lang['header_revoke'] =  "Revoke";
    $lang['header_admin_name'] =  "Administrator";
    $lang['header_add_administrator'] =  "Add Administrator";
    $lang['header_transport'] = "Set SMTP Transport Host";

    // Text labels
    $lang['text_yes'] =  "Yes";
    $lang['text_no'] =  "No";
    $lang['text_virus_scanning'] =  "Virus Scanning";
    $lang['text_enabled'] =  "Enabled";
    $lang['text_disabled'] =  "Disabled";
    $lang['text_quarantined'] =  "Quarantined";
    $lang['text_discarded'] =  "Discarded";
    $lang['text_labeled'] =  "Labeled";
    $lang['text_detected_viruses'] =  "Detected viruses should be...";
    $lang['text_spam_filtering'] =  "Spam Filtering";
    $lang['text_detected_spam'] =  "Detected spam should be...";
    $lang['text_prefix_subject'] =  "Add a prefix to the subjects of spam";
    $lang['text_add_spam_header'] =  "Add X-Spam: Headers when Score is";
    $lang['text_consider_mail_spam'] =  "Consider mail 'Spam' when Score is";
    $lang['text_quarantine_spam'] =  "Quarantine Spam when Score is";
    $lang['text_kill_spam'] =  "Discard (without Quarantine) Spam when Score is";
    $lang['text_attachment_filtering'] =  "Attachment Type Filtering";
    $lang['text_mail_with_attachments'] =  "Mail with dangerous attachments should be...";
    $lang['text_bad_header_filtering'] =  "Bad Header Filtering";
    $lang['text_mail_with_bad_headers'] =  "Mail with bad headers should be...";
    $lang['text_settings_updated'] =  "Your mail filter defaults have been updated.";
    $lang['text_system_default'] =  "System Default";
    $lang['text_no_admins'] =  "No administrators have been selected for this domain.";
    $lang['text_no_available_admins'] =  "No users are available to administer this domain.";
    $lang['text_administrators_added'] =  "The new administrator(s) have been added to this domain.";
    $lang['text_admins_revoked'] =  "The selected administrators' privileges have been revoked.";
    $lang['text_cache_ham_question'] =  "Should non-spam items be cached?";
    $lang['text_enable_user_autocreation'] =  "Enable user auto-creation?";
    $lang['text_domain_theme'] = "Default theme for this domain?";
    $lang['text_routing_domain'] = "Routing domain name (example.com)";
    $lang['text_transport'] = "Transport Host";
    $lang['text_transport_error'] = "Error setting transport: %s";
    $lang['text_transport_set'] = "Transport has been updated";
    $lang['text_invalid_transport_form'] = "Invalid form for transport request";

    // Buttons
    $lang['button_reset'] =  "Reset";
    $lang['button_update_domain'] =  "Update This Domain's Defaults";
    $lang['button_revoke'] =  "Revoke Privileges for Marked Administrators";
    $lang['button_grant'] =  "Grant Administrator Privileges";
    $lang['button_transport'] =  "Set SMTP Transport";


    // Links
    $lang['link_domain_settings'] =  "Return to Domain Settings";
    $lang['link_admin_domains'] =  "Return to the Domain Administration Menu";

    //tabs
    $lang['tab_domain_settings'] = "Thresholds";
    $lang['tab_misc_settings'] = "Misc";
    $lang['tab_grant_admin'] = "Grant Admin";
    $lang['tab_revoke_admin'] = "Revoke Admin";
    $lang['tab_change_login'] = "Change Login";
    $lang['tab_addresses'] = "Addresses";
    $lang['tab_transport'] = "Domain Transport";
?>
