<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Report Spam";

    // Table headers
    $lang['header_suspected_ham'] =  "Unconfirmed Non-spam";
    $lang['header_ham_cache_contents'] =  "Non-spam Cache Contents";

    // Text messages
    $lang['text_item'] =  "Item";
    $lang['text_items'] =  "Items";
    $lang['text_score'] =  "Score";
    $lang['text_received'] =  "Received";
    $lang['text_from'] =  "From";
    $lang['text_to'] =  "To";
    $lang['text_spam'] =  "Spam?";
    $lang['text_ham'] =  "Non-spam?";
    $lang['text_delete'] =  "Delete";
    $lang['text_report'] =  "Spam!";
    $lang['text_subject'] =  "Subject";
    $lang['text_no_subject'] =  "no subject";
    $lang['text_empty'] =  "Your non-spam cache is empty.";
    $lang['text_updated'] =  "Your non-spam cache has been updated.";
    $lang['text_of'] =  "of";
    $lang['text_ham_confirmed'] =  "%d unconfirmed non-spam items were confirmed";
    $lang['text_spam_reported'] =  "%d unconfirmed non-spam items were reported as spam";
    $lang['text_ham_deleted'] =  "%d unconfirmed non-spam items were deleted";
    $lang['text_message_resent'] = "%d message(s) were (re)delivered and left in the message cache";
    $lang['text_suspected_ham_item'] =  "Unconfirmed Non-spam Item";
    $lang['text_suspected_ham_items'] =  "Unconfirmed Non-spam Items";

    // Buttons
    $lang['button_confirm_ham'] =  "ALL Items in this List are Non-spam";
    $lang['button_confirm'] =  "Confirm the Status of these Items";
    $lang['button_delete_all_cached_items'] =  "Delete ALL Cached Items";

    // Link text
    $lang['link_prev'] =  "Prev";
    $lang['link_next'] =  "Next";
    $lang['link_report_spam'] =  "Return to Non-spam Cache Menu";
    $lang['link_welcome'] = "Return to Welcome Page";

?>
