<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Banner subtitle
    $lang['banner_subtitle'] =  "Allow/Block Address Settings";

    // Text messages
    $lang['text_address_to_add'] =  "E-mail address to add (wildcards: * and ?)";
    $lang['text_lists_updated'] =  "Your Allow/Block settings have been updated.";
    $lang['text_wblist_error'] = "There was an error updating your Allow/Block settings.";
    $lang['text_wb_deleted'] = 'The address rule has been removed and will be filtered normally.';
    $lang['text_wb_address_changed'] = "The email address was already in the list; It has been updated.";
    $lang['text_wb_address_added'] = "The address has been added.";
    $lang['text_wb_bypass'] = "Add filtering exception for address:";
    $lang['text_wb_bypass_list'] = "The following addresses are always:";
    $lang['text_enter_address'] = "Please enter an address first.";
    $lang['text_submit_by_click'] = "Please submit the form by clicking one of 'Allow' or 'Block'";
    $lang['text_blocked_by_domain'] = 'The following addresses have been set by your domain administrator.';
    $lang['text_blocked_by_system'] = 'The following addresses have been set by your system administrator.';
    
    // Radio buttons
    $lang['text_allow'] =  "Allow";
    $lang['text_block'] =  "Block";
    $lang['text_remove'] =  "Remove";
    $lang['text_blocked'] = "Blocked";
    $lang['text_allowed'] = "Allowed";
    $lang['text_allow_address'] = "Allow Address";
    $lang['text_block_address'] = "Block Address";
    $lang['text_remove_rule'] = "Remove Rule";

    // Table column headers
    $lang['header_address'] =  "Address";
    $lang['header_domain'] = "Domain";
?>
