<?php
    /*
     * $Id: adminusers.php,v 1.1.2.2 2004/09/10 16:17:31 dmorton Exp $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle']          = "Administration: Benutzer";

    // Table headers
    $lang['header_users_menu']        = "Benutzer";
    $lang['header_add_email']         = "Neue E-Mail-Adresse/Alias hinzufügen";
    $lang['header_link_email']        = "E-Mail-Adresse/Alias verknüpfen";
    $lang['header_delete_email']      = "Lösche E-Mail-Adresse/Alias";
    $lang['header_delete_user']       = "Lösche Benutzer";

    // Text messages
    $lang['text_lookup_user']         = "Benutzerdetails";
    $lang['text_wildcard']            = "Platzhalter";
    $lang['text_new_email']           = "Neue E-Mail-Adresse/Alias hinzufügen";
    $lang['text_email']               = "E-Mail-Adresse/Alias";
    $lang['text_user']                = "Benutzerkonto";
    $lang['text_delete_email']        = "E-Mail-Adresse/Alias";
    $lang['text_address_linked']      = "Verknüpfe %s zu Benutzer %s.";
    $lang['text_address_not_linked']  = "Kann keine E-Mail-Adresse mit Benutzerkonten verknüpfen.";
    $lang['text_address_added']       = "E-Mail-Adresse %s wurde hinzugefügt.";
    $lang['text_address_not_added']   = "E-Mail-Adresse %s konnte nicht hinzugefügt werden.";
    $lang['text_address_deleted']     = "Die markierten E-Mail-Adressen wurden gelöscht.";
    $lang['text_address_not_deleted'] = "Eine oder mehrere der markierten E-Mail-Adressen konnten nicht gelöscht werden.";
    $lang['text_user_found']          = "%ld Benutzer gefunden";
    $lang['text_user_not_found']      = "Keine Benutzer, die Ihrer Suche entsprechen, gefunden.";
    $lang['text_user_deleted']        = "Die markierten Benutzer wurden gelöscht.";
    $lang['text_user_not_deleted']    = "Ein oder mehrere der markierten Benutzerkonten konnten nicht gelöscht werden.";
    $lang['text_email_subject']       = "Willkommen zu Maia Mailguard";
    $lang['text_email_from']          = "Maia Mailguard";
    $lang['text_no_users']            = "Keine Benutzer verfügbar";
    $lang['text_no_addresses']        = "Keine E-Mail-Adressen verfügbar";


    // Buttons
    $lang['button_lookup']            = "Benutzer finden";
    $lang['button_add_email']         = "Neue E-Mail-Adresse/Alias hinzufügen";
    $lang['button_link_email']        = "E-Mail-Adresse/Alias verknüpfen";
    $lang['button_delete_email']      = "Lösche E-Mail-Adresse/Alias";
    $lang['button_delete_user']       = "Lösche Benutzer";

    // Links
    $lang['link_admin_menu']          = "Zurück zum Administrationsmenü";
    $lang['link_users_menu']          = "Zurück zum Benutzermenü";
?>