<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle']                       = "Administration: Systemkonfiguration";

    // Table header
    $lang['header_system_menu']                    = "Systemkonfiguration";
    $lang['header_charts']                         = "Charts";
    $lang['header_reminders']                      = "Aufbewahrungszeit für Zwischenspeicher &amp; Quarantäne Erinnerungs-E-Mail";
    $lang['header_authentication']                 = "Authentifizierung";
    $lang['header_virus_info']                     = "Vireninformationen";
    $lang['header_display']                        = "Anzeige";
    $lang['header_paths']                          = "Pfade &amp; Ports";
    $lang['header_bandwidth']                      = "Bandbreitenermittlung";
    $lang['header_stats_reporting']                = "Statistiken &amp; Reports";

    // Text labels
    $lang['text_yes']                              = "Ja";
    $lang['text_no']                               = "Nein";
    $lang['text_accept']                           = "Akzeptiert";
    $lang['text_reject']                           = "Zurückgewiesen";
    $lang['text_enable_user_autocreation']         = "Benutzerkonten automatisch erstellen?";
    $lang['text_internal_auth']                    = "Automatisch Kennwörter für neue Benutzerkonten generieren?";
    $lang['text_enable_false_negative_management'] = "Verwaltung von falschen Negativen?";
    $lang['text_enable_stats_tracking']            = "Statistiken aktivieren?";
    $lang['text_enable_virus_scanning']            = "VirenScan aktivieren?";
    $lang['text_enable_spam_filtering']            = "Spamfilter aktivieren?";
    $lang['text_enable_banned_files_checking']     = "Auf verbotene E-Mail-Anhänge prüfen?";
    $lang['text_enable_bad_header_checking']       = "Nach 'Bad Headers' (defekten Kopfzeilen) suchen?";
    $lang['text_enable_spamtraps']                 = "Benutzerkonten für Spamfallen zulassen?";
    $lang['text_enable_charts']                    = "Graphische Charts aktivieren?";
    $lang['text_enable_address_linking']         = "Benutzern das verknüpfen von E-Mail-Adressen mit Ihren Konten erlauben?";
    $lang['text_enable_username_changes']          = "Dürfen Benutzer ihren Benutzernamen ändern?";
    $lang['text_enable_privacy_invasion']          = "Dürfen Administratoren die E-Mails der Benutzer lesen?";
    $lang['text_system_default_user_is_local']     = "Soll der Standard-Systembenutzer (@.) nur lokale Empfänger verwalten?";
    $lang['text_user_virus_scanning']              = "Erlaube Benutzern das aktivieren/deaktivieren des VirenScans?";
    $lang['text_user_spam_filtering']              = "Erlaube Benutzern das aktivieren/deaktivieren des Spamfilters?";
    $lang['text_user_banned_files_checking']       = "Erlaube Benutzern das aktivieren/deaktivieren des Filters für verbotene Anhänge?";
    $lang['text_user_bad_header_checking']         = "Erlaube Benutzern das aktivieren/deaktivieren des 'Bad Header' Filters?";
    $lang['text_size_limit']                       = "max. Größe der E-Mails (Bytes):";
    $lang['text_oversize_policy']                  = "Übergroße E-Mails werden ...";
    $lang['text_admin_email']                      = "Kontaktadresse des Administrators:";
    $lang['text_smtp_server']                      = "Downstream SMTP server (MTA-TX):";
    $lang['text_smtp_port']                        = "Downstream SMTP Port:";
    $lang['text_key_file']                         = "Encryption Key Datei (optional):";
    $lang['text_newuser_template_file']            = "E-Mail-Vorlage für neue Benutzer:";
    $lang['text_chart_ham_colour']                 = "Farbe für das Anzeigen von bestätigtem Kein-Spam:";
    $lang['text_chart_spam_colour']                = "Farbe für das Anzeigen von bestätigtem Spam:";
    $lang['text_chart_virus_colour']               = "Farbe für das Anzeigen von Viren:";
    $lang['text_chart_fp_colour']                  = "Farbe für das Anzeigen von falschen Positiven:";
    $lang['text_chart_fn_colour']                  = "Farbe für das Anzeigen von falschen Negativen:";
    $lang['text_chart_suspected_ham_colour']       = "Farbe für das Anzeigen von verdächtigem Kein-Spam:";
    $lang['text_chart_suspected_spam_colour']      = "Farbe für das Anzeigen von verdächtigem Spam:";
    $lang['text_chart_wl_colour']                  = "Farbe für das Anzeigen von E-Mails der Whitelist:";
    $lang['text_chart_bl_colour']                  = "Farbe für das Anzeigen von E-Mails der Blacklist:";
    $lang['text_chart_background_colour']          = "Farbe für den Chart Hintergrund:";
    $lang['text_chart_font_colour']                = "Farbe für die Chart Schriften:";
    $lang['text_chart_autogeneration_interval']    = "Automatische Chart Generierung nach (Minuten):";
    $lang['text_expiry_period']                    = "Aufbewahrungszeit für E-Mails in der Quarantäne (Tage):";
    $lang['text_ham_cache_expiry_period']          = "Aufbewahrungszeit für Kein-Spam im Zwischenspeicher (Tage):";
    $lang['text_reminder_threshold_count']         = "Erinnerungs-E-Mail senden ab (E-Mails):";
    $lang['text_reminder_threshold_size']          = "Erinnerungs-E-Mail senden ab (Größe):";
    $lang['text_reminder_template_file']           = "Erinnerungs-E-Mail Vorlage:";
    $lang['text_reminder_login_url']               = "Maia Anmelde URL für E-Mail-Erinnerung:";
    $lang['text_banner_title']                     = "Top-Banner Titel:";
    $lang['text_use_icons']		           = "Symbole in der Toolbar zeigen?";
    $lang['text_use_logo']                         = "Soll das Logo im Top-Banner gezeigt werden?";
    $lang['text_logo_file']                        = "Bilddatei für das Banner:";
    $lang['text_logo_alt_text']                    = "Text für das Top-Banner Logo:";
    $lang['text_logo_url']                         = "URL für den Link das Top-Banners:";
    $lang['text_virus_info_url']                   = "URL Vorlage für Vireninformationen:";
    $lang['text_virus_lookup']                     = "Virennamen sollen ersetzt werden durch:";
    $lang['text_none']                             = "Keine (keine Lookups)";
    $lang['text_google']                           = "Google Suche";
    $lang['text_fprot']                            = "F-Prot";
    $lang['text_fsecure']                          = "F-Secure";
    $lang['text_fsecurejp']                        = "F-Secure Japan";
    $lang['text_sophos']                           = "Sophos";
    $lang['text_nod32']                            = "NOD32";
    $lang['text_norman']                           = "Norman Virus Control";
    $lang['text_trend']                            = "Trend Micro";
    $lang['text_symantec']                         = "Symantec";
    $lang['text_mcafee']                           = "McAfee VirusScan";
    $lang['text_currency_label']                   = "Währungssymbol:";
    $lang['text_bandwidth_cost']                   = "Monatliche Bandbreite kostet pro Gigabyte:";
    $lang['text_enable_stats_reporting']           = "Sollen die Statistiken reportet werden?";
    $lang['text_primary_report_server']            = "Primärer Reporter-Server:";
    $lang['text_primary_report_port']              = "Port des primären Reporter-Servers:";
    $lang['text_secondary_report_server']          = "Sekundärer Reporter-Server:";
    $lang['text_secondary_report_port']            = "Port des sekundären Reporter-Servers:";
    $lang['text_reporter_sitename']                = "Name Ihrer Seite:";
    $lang['text_reporter_username']                = "Ihre Maia Reporter ID:";
    $lang['text_reporter_password']                = "Ihr Maia Reporter Passwort:";

    // Buttons
    $lang['button_submit']                         = "Aktualisiere Einstellungen";
    $lang['button_restore']                        = "Formular zurücksetzen";

    // Links
    $lang['link_admin_menu']                       = "Zurück zum Administrationsmenü";
?>