<?php
    /*
     * $Id: welcome.php,v 1.1.2.4 2004/02/12 17:38:30 dmorton Exp $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    
     $lang['text_welcome_greeting'] = "Willkommen zu Maia Mailguard!";
     $lang['text_welcome_first_time'] = "Willkommen zu Maia Mailguard. Sie melden sich zum ersten Mal an. Bitte lesen Sie diesen Text komplett durch, da er helfen soll, das Spamaufkommen zu verringern.<P> Um den Spamschutz sofort zu aktivieren, wählen Sie einen Schutzlevel, wie oben aufgeführt, aus und klicken Sie auf \"Level ändern\".  Der Level \"Hoch\" ist sicher und wird empfohlen.<P>Maia Mailguard kann Ihre E-Mails filtern und nahezu alle unerwünschten E-Mails von Ihrem Posteingang fernhalten. Sollte dem System ein Fehler unterlaufen, sind die betroffenen E-Mails nicht verloren. Maia sichert Ihre E-Mails in einem Quarantänebereich, der auch von dieser Seite aus erreichbar ist. Von dort aus können die E-Mails erneut zugestellt oder als SPAM gemeldet werden. Zusätzlich besteht die Möglichkeit, eine E-Mail, die fälschlicherweise als \"gut\" erkannt wurde, vom Kein-Spam-Zwischenspeicher aus als SPAM zu melden und damit den Filter zu \"trainieren\". Im Kein-Spam-Zwischenspeicher finden Sie für eine (vom Administrator) einstellbare Zeit die E-Mails, die vom Filter als \"gut\" eingestuft wurden.";
     $lang['text_welcome_intro'] = "Ergreifen Sie Maßnahmen gegen den Angriff unerwünschter E-Mails mit Maia Mailgard.  Falls im Bereich \"Inhalt des Zwischenspeichers\" E-Mails aufgeführt sind, können Sie Maia trainieren, damit die Erkennung zwischen \"guten\" (Kein-Spam) und \"schlechten\" (SPAM) E-Mails besser funktioniert. Bitte nehmen Sie sich die Zeit, die E-Mails entsprechend einzuordnen/als SPAM zu melden. Sollten Sie sich diese Zeit nicht nehmen wollen, löschen Sie die E-Mails aus Ihrem Zwischenspeicher/Quarantäne anstatt sie falsch einzuordnen.<p> Bitte beachten Sie, dass Ihr Training einem firmenweiten Filter zugute kommt. Wenn Sie diesen \"Meldeprozess\" für SPAM/Kein-Spam immer durchführen, helfen Sie mit, Ihre und unsere Postfächer \"sauber\" zu halten. Vielen Dank!";    
     $lang['text_welcome_current_level'] = "Aktueller Schutzlevel:";
     $lang['text_welcome_custom_level'] = "**Benutzerlevel sind aktiv:<br>Änderungen im Einstellungsmenü durchführen oder eine der oben aufgeführten Voreinstellungen nutzen.";

     $lang['text_welcome_spam_blocked'] = "SPAM-E-Mails an Sie wurden blockiert";
     $lang['text_welcome_virus_blocked'] = "Viren an Sie wurden blockiert";
     $lang['text_welcome_spam_blocked_system'] = "Spam-E-Mails systemweit blockiert";
     $lang['text_welcome_virus_blocked_system'] = "Viren systemweit blockiert";
     $lang['button_delete_all_items'] = "Alle E-Mails löschen";
     $lang['button_change_protection'] = "Level ändern";
     $lang['radio_protection'] = array( 'off'    => "Aus",
                                        'low'    => "Niedrig",
					'medium' => "Mittel",
					'high'   => "Hoch",
					'custom' => "Benutzerdefiniert"); 
     $lang['banner_subtitle'] = "Willkommen";
     $lang['text_cache_spam'] = "Sie haben <b>%d</b> E-Mails in Ihrem Spam-Zwischenspeicher.  <br>Klicken Sie <a href=\"%s\">hier</a> um diese zu melden, oder eine versehentlich blockierte E-Mail erneut zuzustellen.";
     $lang['text_cache_virus'] = "Sie haben <b>%d</b> E-Mails in Ihrem Viren-Zwischenspeicher.  <br>Klicken Sie <a href=\"%s\">hier</a> um diese zu löschen, oder eine versehentlich blockierte E-Mail erneut zuzustellen.";
     $lang['text_cache_banned'] = "Sie haben <b>%d</b> E-Mails im Zwischenspeicher für verbotene Dateianhänge.  <br>Klicken Sie <a href=\"%s\">hier</a> um diese zu löschen, oder eine versehentlich blockierte E-Mail erneut zuzustellen.";
     $lang['text_cache_header'] = "Sie haben <b>%d</b> E-Mails in Ihrem Zwischenspeicher für defekte Kopfzeilen.  <br>Klicken Sie <a href=\"%s\">hier</a> um diese zu löschen, oder eine versehentlich blockierte E-Mail erneut zuzustellen.";
     $lang['text_cache_ham'] = "Sie haben <b>%d</b> E-Mails in Ihrem Kein-Spam-Zwischenspeicher.  <br>Klicken Sie <a href=\"%s\">hier</a> um den Filter zu trainieren, oder diese E-Mail als Spam zu melden.";
     $lang['action_ham_cache']   = "Melden/Bestätigen";
     $lang['action_spam_cache']  = "Melden/erneut zustellen";
     $lang['action_virus_cache'] = "Löschen/erneut zustellen";
     $lang['action_banned_cache'] = "Löschen/erneut zustellen";
     $lang['action_header_cache'] = "Löschen/erneut zustellen";
    
    
