<?php
    /*
     * $Id: adminhelp.php 631 2005-05-03 19:19:22Z jleaver $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Amministrazione: Aiuto";

    // Table header
    $lang['header_help_menu'] =  "Aiuto";

    // Users
    $lang['adminhelp_find_users'] =  "<b>%s</b> per facilitare le tue ricerche nel database usa " .
                                 "utenti il cui nome sia un modello di ricerca.  Il carattere '*' " .
                                 "serve come metacarattere e può essere il sostituto di zero o più " .
                                 "altri caratteri, ad esempio \"ja*n\" sta per \"jan\" " .
                                 "così come \"jason\".  La ricerca è case-sensitive, quindi \"jan\" " .
                                 "è differente da \"Jan\".  L'amministratore del dominio sarà l'unico " .
                                 "in graddo di trovare i dati degli utenti che hanno un indirizzo e-mail " .
                                 "nel dominio che controllano.";

    $lang['adminhelp_add_email_address'] =  "<b>%s</b> ti permette di aggiungere un nuovo indirizzo " .
                                        "e-mail nel database. Questo implica la creazione di un nuovo utente " .
                                        "inoltre , ogni indirizzo e-mail deve avere per forza un \"proprietario\" " .
                                        "Il nome del nuovo utente sarà collegato all'indirizzo e-mail. " .
                                        "Se stai utilizzando l'autenticazione POP3 o IMAP " .
                                        "l'e-mail che hai fornito deve combaciare con il dominio " .
                                        "di routing del tuo server di posta; " .
                                        "Maia può fare questo automaticamente, se tu hai " .
                                        "fornito qui un indirizzo e-mail \"normale\".";

    $lang['adminhelp_link_email_address'] =  "<b>%s</b> permette di collegare un indirizzo e-mail " .
                                         "ad un utente esistente.  Un indirizzo e-mail può essere " .
                                         "collegato ad un solo utente, quindi facendo un nuovo collegamento " .
                                         "si rompe il vecchio collegamento.  Se il precedente propietario " .
                                         "rimane senza un indirizzo e-mail, il suo account utente " .
                                         "verrà rimosso automaticamente.  L'indirizzo e-mail verrà " .
                                         "trasferito al nuovo proprietario dell'account.  Se il precedente " .
                                         "proprietario è stato rimosso dal processo, tutti i beni " .
                                         "come statistiche, liste bianche e nere, e " .
                                         "ogni email ed oggetti presenti negli archivi di quarantena per tale  " .
                                         "utente verrà uniti con quelli del nuovo proprietario.";

    $lang['adminhelp_delete_email_address'] =  "<b>%s</b> permette di rimuovere un indirizzo e-mail dal " .
                                           "sistema.  Non puoi con questa funzione cancellare l'email " .
                                           "principale dell'utente; se vuoi cancellare " .
                                           "l'email principale, devi prima fornire un'altra " .
                                           "email principale per l'utente.  Questo avviene per salvaguardare " .
                                           "l'errata cancellazione del solo indirizzo email dell'utente " .
                                           "Se vuoi rimuovere l'utente completamente, usa " .
                                           "<b>%s</b>, qui sotto.";

    $lang['adminhelp_delete_user'] =  "<b>%s</b> permette di rimuovere un utente dal sistema, " .
                                  "con tutti i suoi dati, statistiche, liste bianche, liste nere, " .
                                  "e ogni oggetto ed email presenti nell'archivio quarantena di questo utente. " .
                                  "Questo implica anche la rimozione dell'indirizzo e-mail associato a questo " .
                                  "utente.  Nota che se <b>%s</b> è abilitato, verranno creati nuovi utenti " .
                                  "alla ricezone di email indirizzate ad utenti non esistenti, " .
                                  "la cancellazione di un utente non elimina la possibilità " .
                                  "che questo utente venga ricreato.";

    $lang['adminhelp_impersonate'] =  "<b>%s</b> è l'elenco dei risultati della tua ricerca, e da " .
                                  "la possibilità di \"impersonare\" ogni utente della lista. " .
                                  "Quando clicchi sul nome dell'utente della lista, tu \"diventi\" " .
                                  "quell'utente, come se ti fossi loggato con le sue credenziali. " .
                                  "Questo è abilitato per poter vedere Maia con gli occhi dell'utente per poterlo aiutare" .
                                  "a risolvere i suoi problemi. Per terminare l'utilizzo di un altro utente, clicca su " .
                                  "%s nella barra e tornerai all tua identità.";

    // Domains
    $lang['adminhelp_domain_administration'] =  "<b>%s</b> è l'elenco dei domini su cui hai " .
                                            "i privilegi amministrativi.  Il dominio @. " .
                                            "controlla le impostazioni predefinite del sistema, e " .
                                            "non può essere cancellato.  Con impostazioni per altri " .
                                            "domini puoi configurare le opzioni prdefinite per " .
                                            "gli indirizzi in quel dominio.  Gli utenti " .
                                            "possono, ovviamente, sovrascrivere queste impostazioni.";

    $lang['adminhelp_add_domain'] =  "<b>%s</b> permette al amministratore di aggiungere un nuovo dominio " .
                                 "al sistema, creandolo con le stesse impostazioni del dominio  " .
                                 "predefinito del sistema (@.).  Per assegnare gli amministratori " .
                                 "al nuovo dominio appena creato, o per modificare le sue impostazioni predefinite " .
                                 "seleziona il dominio dalla lista descritta qui sopra.";

    $lang['adminhelp_domain_settings'] =  "<b>%s</b> mostra le correnti impostazioni predefinte per il " .
                                      "dominio selezionato.  Queste sono le stesse impostazioni che un utente " .
                                      "ha sul proprio indirizzo e-mail eccetto il fatto che questo caso " .
                                      "puoi solo impostare i valori prestabiliti che verranno assegnati ad un " .
                                      "nuovo indirizzo e-mail creato nel " .
                                      "dominio.  Gli Utenti possono sovrascrivere le proprie impostazioni prestabilite " .
                                      "per il proprio indirizzo.  Vedi la pagina %s impostazioni utente per " .
                                      "maggiori dettagli.";

    $lang['adminhelp_administrators'] =  "<b>%s</b> mostra l'elenco degli amministratori per questo " .
                                     "dominio e , se esiste, abilita il super amministratore a " .
                                     "revocare i privilegi amministrativi al singolo amministratore o " .
                                     "tutti quelli presenti.  Il super amministratore, ovviamente, " .
                                     "può amministratre <i>tutti</i> i domini e i suoi privilegi non possono " .
                                     "essere revocati (eccetto manualmante entrando nel sistema " .
                                     "utilizzando il suffisso \"&amp;super=unregister\" ).";

    $lang['adminhelp_add_administrator'] =  "<b>%s</b> mostra l'elenco di tutti gli utenti del " .
                                        "sistema che non sono amministratori o super amministratori del dominio stesso " .
                                        "Il supera amministratore può far diventare ognuno di questi utenti " .
                                        "amministratore del proprio dominio.  Gli Utenti possono amministrare " .
                                        "diversi domini solo se il super amministratore assegna loro " .
                                        "i privilegi per farlo, allo stesso modo un dominio può avere " .
                                        "molteplici amministratori.";

    // Virus Aliases
    $lang['adminhelp_virus_aliases'] =  "<b>%s</b> è l'elenco degli alias dei virus e dei virus attuali a cui " .
                                    "fanno riferimento.  Tu puoi cancellare ogni alias " .
                                    "in ogni momento, comunque così facendo non renderai nuovamente un alias " .
                                    "un virus reale, o ripristinare le sue precedenti " .
                                    "statistiche.";


    $lang['adminhelp_add_virus_alias'] =  "<b>%s</b> potete utilizzare il nome di un virus com alias per  " .
                                      "un'altro virus.  Questa opzione aiuta la gestione delle statistiche" .
                                      "dei virus quando nel tuo sistema usi più virus " .
                                      "scanner.  Da quando ogni venditore di antivirus ha una propria " .
                                      "convenzione sui nomi dei virus, eseguire scansioni multiple dei virus " .
                                      "può generare voci duplicate nel database (e.g. Worm.Klez.H e " .
                                      "Worm/Klez-H@MM).  Utilizzando questo virus come alias per un'altro " .
                                      "Maia capisce di contrggiarli come lo stesso.";

    // Languages
    $lang['adminhelp_languages'] =  "<b>%s</b> è l'elenco di tutte le lingue supportate installate " .
                                "nella versione di Maia Mailguard.  La lingua predefinita " .
                                "(Inglese) è sempre presente nella lista e non può essere " .
                                "disinstallata.";

    $lang['adminhelp_install_languages'] =  "<b>%s</b> ti abilita a rendere disponibili altre lingue " .
                                        "per gli utenti.  Prima comunque devi installare " .
                                        "i file della lingua nella cartella ./locale/ usando le due " .
                                        "lettere della codifica ISO-639 (en, fr, de, etc.). " .
                                        "Una volta installati i file puoi vedere la nuova lingua " .
                                        "in questa lista.";

    // System Configuration
    $lang['adminhelp_enable_user_autocreation'] =  "<b>%s</b> permette a Maia di creare un nuovo utente ogni volta " .
                                               "in cui si riceve un email per un utente locale non ancora registrato " .
                                               "nel database di Maia.  Il nome utente è impostato inizialmente " .
                                               "come l'indirizzo e-mail , può essere poi sostituito con il proprio  " .
                                               "nome la prima volta che accedi a Maia. " .
                                               "Le impostazioni iniziali per questo utente vengono prese direttamente " .
                                               "dal dominio predefinito (basato sul dominio dell'indirizzo e-mail) " .
                                               "se disponibile, oppure dalle impostazioni predefinite del sistema. " .
                                               "Se questa opzione è disabilitata l'utente può essere creato solamente " .
                                               "quando un utente entra in Maia.  Questa opzione deve essere usata con cautela, " .
                                               "comunque assicurati chje il tuo mail server sia protetto contro " .
                                               "gli attacchi che utilizzano i dizionari di parole prima di abilitare " .
                                               "questa opzione. Ad ogni modo se vedi che c'è un grosso quantitativo di nuovi  " .
                                               "utenti creati in breve tempo, significa che uno spammer sta utilizzando " .
					       "il tuo server per provare un nuovo indirizzo!";

    $lang['adminhelp_internal_auth'] =  "<b>%s</b> dice a Maia di generare una password casuale di 8 caratteriom per un nuovo " .
                                    "utente e mandare via e-mail le credenziali temporanee per l'acesso.  L'utente può " .
                                    "entrare con queste credenziali e modificarle tramite la pagina " .
                                    "delle impostazioni personali.";

    $lang['adminhelp_enable_false_negative_management'] =  "<b>%s</b> puoi abilitare o disabilitare l'archivio per il " .
                                                       "non-spam , che è il meccanismo con cui Maia's segnala i " .
                                                       "falsi negativi (i.e. spam that made it past " .
                                                       "the filters as non-spam by mistake).  Segnalando i falsi " .
                                                       "negativi e \"confermando\" le email non-spam migliori " .
                                                       "l'accuratezza dei filtri spam di Maia's, devi decidere quindi se " .
                                                       "abilitare questa opzione evitando di risparmiare quindi " .
                                                       "spazio per l'archivio non-spam.  Note che puoi " .
                                                       "controllare la scadenza del tuo archivio non-spam " .
                                                       "per aiutarti controlla le caratteristiche richieste per il salvataggio " .
                                                       "<b>%s</b> per maggiori dettagli.";

    $lang['adminhelp_enable_stats_tracking'] =  "<b>%s</b> puoi abilitare o disabilitare il sistema interno di generazione " .
                                            "di statistiche di Maia.  Molti siti propabilmente vogliono " .
                                            "questa opzione abilitata ma preferiscono prendere le proprie " .
                                            "statistiche dai file log con altri programmi, " .
                                            "puoi quindi disabilitare questa funzione qui e " . 
					    "salvagurdare le risorse utilizzate dal tuo sistema.";

    $lang['adminhelp_enable_virus_scanning'] =  "<b>%s</b> puoi abilitare o disabilitare globalmente " .
                                            "il controllo antivirus e altre forme di malware sulle email.";

    $lang['adminhelp_user_virus_scanning'] =  "<b>%s</b> puoi decidere quale utente può abilitare o disabilitare " .
                                          "la scansione dei virus.";

    $lang['adminhelp_enable_spam_filtering'] =  "<b>%s</b> puoi abilitare o disabilitare globalmente il controllo " .
                                            "dello spam sulle e-mail.";

    $lang['adminhelp_user_spam_filtering'] =  "<b>%s</b> puoi decidere quale utente può abilitare o disabilitare " .
                                          "il filtraggio dello spam.";

    $lang['adminhelp_enable_banned_files_checking'] =  "<b>%s</b> puoi abilitare o disabilitare globalmente il controllo " .
                                                   "dei file file vietati sulle e-mail.";

    $lang['adminhelp_user_banned_files_checking'] =  "<b>%s</b> puoi decidere quale utente può abilitare o disabilitare " .
                                                 "il controllo sui file vietati.";

    $lang['adminhelp_enable_bad_header_checking'] =  "<b>%s</b> puoi abilitare o disabilitare globalmente il controllo " .
                                                 "delle intestazioni invalide sulle e-mail.";

    $lang['adminhelp_user_bad_header_checking'] =  "<b>%s</b> puoi decidere quale utente può abilitare o disabilitare " .
                                               "il controllo sulle intestazioni invalide.";

    $lang['adminhelp_enable_spamtraps'] =  "<b>%s</b> puoi globalmente abilitare o disabilitare l'utente " .
                                       "prendi spam, il quale può essere utilizzato per confermare lo spam ad un " .
                                       "indirizzo prestabilito.  Questa opzione deve essere usata con cautela " .
                                       "facendo attenzione al fatto che l'utente prendi spam sia istruito a dovere " .
                                       "non inviando e-mail legittime a questo indirizzo " .
                                       "L'obiettivo dell'utente prendi spam è quello di fornire un indirizzo automatico, " .
                                       "quindi non bisogna mai utilizzare l'indirizzo prendi spam per inviare " .
                                       "o ricevere e-mail legittime.  Una volta marchiato da Maia com " .
                                       "prendi spam l'indirizzo non riceverò nai le email che arrivano " .
                                       "a quell'indirizzo per quell'indirizzo ma tutti i messaggi verranno " .
                                       "trattati come spam confermato da segnalare.  Se non ti fidi che i tuoi " .
                                       "utenti utilizzino questa opzione responsabilmente puoi disabilitarla " .
                                       "globalmente qui.";

    $lang['adminhelp_enable_address_linking'] =  "<b>%s</b> puoi controllare se gli utenti collegano " .
                                             "molteplici indirizzi e-mail ad un singolo utente.  Spesso " .
                                             "questo è disabilitato, tuttavia, l'amministratore può collegare " .
                                             "gli indirizzi per gli utenti dalla pagina dell'amministrazione utenti.";

    $lang['adminhelp_enable_username_changes'] =  "<b>%s</b> puoi controllare se gli utenti cambiano " .
                                              "nome utente.  Possono farlo solo viene utilizzata l'autenticazione " .
                                              "interna di Maia.";

    $lang['adminhelp_enable_privacy_invasion'] =  "<b>%s</b> puoi verificare se l'amministratore può " .
                                              "vedere l'elenco delle mail in quarantena e non-spam degli utenti " .
                                              "e può leggere tali mail.  In molte situazioni questo può essere " .
                                              "disabilitato per rispettare la privacy degli utenti, ma se nella tua " .
                                              "Politica aziendale della Privacy richiede che tu possa controllare " .
                                              "le email degli utenti, puoi abilitare questa opzione.";

    $lang['adminhelp_system_default_user_is_local'] =  "<b>%s</b> determina se l'utente predefinito del sistema " .
                                                   "(@.) corrisponde solamente agli indirizzi e-mail locali, o " .
                                                   "se posso applicare la stessa cosa anche per gli indirizzi non locali. " .
                                                   "Se permetti che l'utente predefinito del sistema prenda anche " .
                                                   "gli indirizzi non locali, potrai prendere la posta in uscita in  " .
                                                   "questo account.  Molti siti vogliono che si impostato su <b>Si</b>.";

    $lang['adminhelp_size_limit'] =  "<b>%s</b> specifica la larghezza massima dei file " .
                                 "che vorrai controllare tramite appositi filtri.  Nota che le opzioni " .
                                 "del tuo database devono essere corrette (e.g. il " .
                                 "<b>max_allowed_packet</b> parametro di MySQL deve essere uguale al valore " .
                                 "della larghezza massima specificata).";

    $lang['adminhelp_oversize_policy'] =  "<b>%s</b> determina cosa vuoi che succeda se degli oggetti " .
                                      "suoerano il limite specificato.  Se vuoi settare questa opzione su <b>%s</b>, gli " .
                                      "oggetti più grandi passerranno sempre il filtro; se vuoi " .
                                      "settare questa opzione su <b>%s</b>, gli oggetti fuori dimensione verranno rigettati " .
                                      "con un messaggio dove verrà indicato il motivo di tale respinta.";

    $lang['adminhelp_installation_directory'] =  "<b>%s</b> specifica il percorso (assoluto) della cartella " .
                                             "dove gli script PHP di Maia sono installati. " .
                                             "Questo è utilizzato da Maia per decidere dove cercare " .
                                             "i file delle lingue ed altre risorse installabili.";

    $lang['adminhelp_amavisd_conf'] =  "<b>%s</b> specifica il percorso del tuo file amavisd.conf file, il quale " .
                                   "contiene le informazioni di configurazione per amavisd-new ";

    $lang['adminhelp_admin_email'] =  "<b>%s</b> imposta l'indirizzo e-mail che l'utente utilizza per " .
                                  "contattare l'amministratore per assistenza.";

    $lang['adminhelp_smtp_server'] =  "<b>%s</b> imposta il nome o l'indirizzo IP del Server di posta SMTP Maia " .
                                  "utilizzato per reindirizzare le email di quarantena o le email allarmi " .
                                  "agli utenti.";

    $lang['adminhelp_smtp_port'] =  "<b>%s</b> imposta il numero della porta del server di posta SMTP Maia utilizzato " .
                                "per per reindirizzare le email di quarantena o le email allarmi agli utenti. " .
                                "La port SMTP standard è la 25, ma in un sistema con due MTA strutturato con una porta " .
                                "\"input\" o \"upstream\" (MTA-RX) e una porta \"output\" o " .
                                "\"downstream\" (MTA-TX), dovrai utilizzare la porta MTA-TX che solitamente, " .
                                "è la 10025.";

    $lang['adminhelp_key_file'] =  "<b>%s</b> specifica il file (incluso il percorso completo, a meno che sia relativo " .
                               "alla tua cartella di installazione di Maia) che contiene la chiav di cifratura Blowfish " .
                               "per il tuo sito.  Puoi lasciare vuoto questo campo se non vuoi  " .
                               "criptare le email nel databse di Maia.  Per creare una nuova chiave usa lo script " .
                               "<b>generate-key.pl</b> e salva l'output in un file.";

    $lang['adminhelp_newuser_template_file'] =  "<b>%s</b> specifica il file(incluso il percorso completo, " .
                                            "a meno che sia relativo alla cartella di installazione di Maia) che " .
                                            "Maia utilizza come modello per generare  " .
                                            "la lettera di benvenuto per i nuovi utenti se viene utilizzata  " .
                                            "l'autenticazione interna di Maia.  Il modello " .
                                            "può contenere i seguenti placeholders: " .
                                            "<font color=\"red\">%%%%LOGIN%%%%</font>, " .
                                            "<font color=\"red\">%%%%PASSWORD%%%%</font>, " .
                                            "<font color=\"red\">%%%%LOGINURL%%%%</font>, and " .
                                            "<font color=\"red\">%%%%ADMINEMAIL%%%%</font>.";

    $lang['adminhelp_expiry_period'] =  "<b>%s</b> imposta il numero di giorni in cui il sospetto spam deve rimanere " .
                                    "nell'area quarantena prima di essere automaticamente scaduto.  Nota " .
                                    "che quando un utente \"conferma\" lo spam, lo spam confermato viene processato " .
                                    "e cancellato immediatamente, quindi questa impostazione è molto importante " .
                                    "per pulire l'area quarantena di utenti poco diligenti.";

    $lang['adminhelp_ham_cache_expiry_period'] =  "<b>%s</b> imposta il numero di giorni in cui il sospetto non-spam deve rimanere " .
                                              "nell'archivio non-spam prima di essere automaticamente scaduto. " .
                                              "Nota che quando un utente \"conferma\" il non-spam, " .
                                              "il non-spam confermato viene processato e cancellato immediatamente, " .
                                              "quindi questa impostazione è molto importante per pulire l'archivio " .
                                              "non-spam di utenti poco diligenti.";

    $lang['adminhelp_reminder_threshold_count'] =  "<b>%s</b> definisce il punto in cui l'email allarme " .
                                               "viene spedita all'utente, basandosi sul numero totale di oggetti " .
                                               "presenti nell'area quarantena.  Quando ci sono molti oggetti nell'area " .
                                               "quarantena dell'utente, l'email allarma lo avvisa " .
                                               "che deve prendere una decisione urgente su questi oggetti.";
    
    $lang['adminhelp_reminder_threshold_size'] =  "<b>%s</b> definisce il punto in cui l'email allarme " .
                                               "viene spedita all'utente, basandosi sulla dimensione totale degli oggetti " .
                                               "presenti nell'area quarantena.  Quando gli oggetti nell'area " .
                                               "quarantena dell'utente sono di notevole dimensione (bytes) , l'email allarma lo avvisa " .
                                               "che deve prendere una decisione urgente su questi oggetti.";

    $lang['adminhelp_reminder_template_file'] =  "<b>%s</b> specifica il file (incluso il percorso completo, " .
                                             "a meno che non sia riferito alla cartella di installazione di Maia) che " .
                                             "Maia può utilizzare come modello per generare l'email allarme " .
                                             "Questo modello supporta i seguenti placeholders: " .
                                             "<font color=\"red\">%%%%VIRUSCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%SPAMCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%BANNEDCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%HEADERCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%VIRUSSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%SPAMSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%BANNEDSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%HEADERSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%MAIAURL%%%%</font>, " .
                                             "<font color=\"red\">%%%%ADMINEMAIL%%%%</font>, " .
                                             "<font color=\"red\">%%%%EXPIRYPERIOD%%%%</font>, " .
                                             "<font color=\"red\">%%%%OLDESTITEMTTL%%%%</font>, e " .
                                             "<font color=\"red\">%%%%OLDESTITEMAGE%%%%</font>.";

    $lang['adminhelp_reminder_login_url'] =  "<b>%s</b> imposta l'indirizzo URL a cui l'utente viene reindirizzato " .
                                         "nell'email allarme che riceve, tramite cui può entrare urgentemente nel sistema " .
                                         "e gestire la propria quarantena/archivio.  Normalmente è impostata la home page " .
                                         "di Maia del tuo sistema.";

    $lang['adminhelp_banner_title'] =  "<b>%s</b> imposta la larghezza dei caratteri con cui appare " .
                                   "il banner posto in alto nella home page di Maia.";

    $lang['adminhelp_use_icons'] =  "<b>%s</b> puoi abilitare o disabilitare le icone grafiche " .
                                "nella barra di tutte le pagine di.  Se disabiliti queste icone, " .
                                "verrà utilizzato solo il testo per descrivere l'operazione.";

    $lang['adminhelp_use_logo'] =  "<b>%s</b> puoi abilitare o disabilitare la visualizzazione del logo " .
                               "di Maia nel banner a sinistra di tutte le pagine Maia.";

    $lang['adminhelp_logo_file'] =  "<b>%s</b> imposta il percorso (relativo alla tua installazione Maia) " .
                                "del file che contiene il logo da utilizzare.";

    $lang['adminhelp_logo_alt_text'] =  "<b>%s</b> imposta un testo alternativo che può essere associato al logo " .
                                    "nel caso venga utilizzato un browser non grafico.";

    $lang['adminhelp_logo_url'] =  "<b>%s</b> imposta l'indirizzo URL a cui i visitatori vengono indirizzati " .
                               "cliccando sul logo.  Se è vuoto non verrà creato nessun collegamento.";

    $lang['adminhelp_virus_info_url'] =  "<b>%s</b> puoi specificare l'URL con il quale Maia fornisce informazioni " .
                                     "circa i virus agli utenti che hanno effettuato l'accesso al sistema. " .
                                     "The placeholder \"%%%%VIRUSNAME%%%%\" viene sostituiti con il nome " .
                                     "del virus attuale, che è stato trovato dal tuo virus scanner.  Se usi " .
                                     "un solo virus scanner, prova a cercare sul sito del produttore del tuo antivirus " .
                                     "dove vengono inserite le descrizioni dei virus nel loro database.  L'elenco " .
                                     "di diversi indirizzi lo puoi trovare sul sito di Maia Mailguard. " .
                                     "Se utilizzi molteplici virus scanner, è più conveniente usare google " .
                                     "per cercare le informazioni che ti interessano.";

    $lang['adminhelp_virus_lookup'] =  "<b>%s</b> dice a Maia come riscrivere il nome dei virus dopo aver " .
                                   "consultato il sito del tuo produttore di antivirus.  Il tuo virus " .
                                   "scanner può aver trovato \"Worm.Sobig.F\", ma sul sito del tuo produttore " .
                                   "di antivirus può essere richiesto il nome \"worm_sobig_f\" o qualcosa di simile " .
                                   "nel loro indirizzo di ricerca.  Diversi specifici produttore riscrivono le regole " .
                                   "loro fornite con un opzione per fare in modo che nessuno debba riscrivere il " .
                                   "nome del virus.  Molto probabilmente tu sceglierai questa impostazione che corrisponde " .
                                   "a <b>%s</b> impostazione qui sopra.";

    $lang['adminhelp_currency_label'] =  "<b>%s</b> specifica a Maia il simbolo che deve utilizzare " .
                                     "per rappresntare la valuta locale, quando viene rapprentato il costo nelle statistiche. " .
                                     "Può esser un espplicito carattere (es. \"\$\") o una stringa (es. \"\$CDN\"), " .
                                     "o un codice HTML (es. \"&amp;euro;\", \"&amp;yen;\", etc.).";

    $lang['adminhelp_bandwidth_cost'] =  "<b>%s</b> è il costo mensile di un gigabyte di traffico registrato " .
                                     "nel tuo sito, espresso nella tua valuta locale " .
                                     "Questo abilita Maia ad effettuare un controllo della banda per te " .
                                     "ed a stimare quanto costa per te un email.";

    $lang['adminhelp_enable_stats_reporting'] =  "<b>%s</b> imposta Maia per segnalare le statistiche mail " .
                                             "filtrate per data provenienti da spam confermato verso un server " .
                                             "di segnalazioni, quindi Maia è un efficiente sistema di tracciabilità " .
                                             "su larga scala e la partecipazione di altri utenti può " .
                                             "solo che esser eun beneficio per gli utenti Maia.  Le statistiche " .
                                             "possono essere segnalate in sito vuoto aggregato, senza nessuna " .
                                             "informazione personale e senza nessuna email spedita presente.  Il " .
                                             "server di segnalazioni è interessante solo per le statisctiche di sistema, " .
                                             "per le statistiche relative alle regole innescate di SpamAssassin, e " .
                                             "agli indirizzi IP di chi ha inviato lo spam confermato e i virus, " .
                                             "which are used to score IP addresses on a time-weighted " .
                                             "basis according to the amount of spam and malware that " .
                                             "originates from those addresses.  Questo elenco continuamente " .
                                             "aggiornato con i nuovi punteggi pervenuti dalle regole degli  " .
                                             "altri utenti Mai. In oltre c'è un ulteriore opzione(sperimentale) " .
                                             "che permette la tracciabilità di quanto spesso le regole di SpamAssassin " .
                                             "ottengano non-spam rispetto allo spam (confermato dai tuoi utenti) " .
                                             "permettendo al punteggio di ogni regola venga redistribuito in modo regolare sulla base ";

    $lang['adminhelp_primary_report_server'] =  "<b>%s</b> imposta il nome o l'indirizzo IP del server " .
                                            "principale di segnalazione Maia.  Solitamente questo è il sito " .
                                            "di segnalazione ufficiale di  Maia Mailguard , in cui sono presenti " .
                                            "i report raccolti dalle varie installazioni di Maia nel mondo.";

    $lang['adminhelp_primary_report_port'] =  "<b>%s</b> imposta il numero della porta del server di segnalazione principale " .
                                          "di Maia.  Le segnalazioni Maia sono molto sicure quando vengono effettuate " .
                                          "utilizzando una connessione protetta SSL, quindi spesso la porta utilizzata " .
                                          "è quella del server web HTTPS (443 è lo standard).";

    $lang['adminhelp_secondary_report_server'] =  "<b>%s</b> imposta il nome o l'indirizzo IP di un server di " .
                                              "segnalazioni secondario di Maia se presente.  La segnalazione viene " .
                                              "spedita al server principale e quindi se presente, viene inviata al server " .
                                              "secondario.  Questo permette all'organizzazione di operare con dei server di segnalazione " .
                                              "proprietari dove si possono orgnizzare i report suddividendoli per ufficio, azienda, etc... ";

    $lang['adminhelp_secondary_report_port'] =  "<b>%s</b> imposta il numero della porta del server di segnalazione secondario " .
                                            "di Maia.  Le segnalazioni Maia sono molto sicure quando vengono effettuate " .
                                            "utilizzando una connessione protetta SSL, quindi spesso la porta utilizzata " .
                                            "è quella del server web HTTPS (443 è lo standard).";

    $lang['adminhelp_reporter_sitename'] =  "<b>%s</b> imposta il nome del tuo sistema (normalmente è il nome " .
                                        "della tua organizzazione) questo può comparire nel'elenco delle " .
                                        "segnalazioni Maia.";

    $lang['adminhelp_reporter_username'] =  "<b>%s</b> imposta il nome utente (Reporter ID) che il tuo script per le " .
                                        "segnalazioni Maia utilizza per autentiarsi con il server di segnalazioni.  Per " .
                                        "registrare un ID per le segnalazioni per il tuo sistema, vai alla pagina %s ";

    $lang['adminhelp_reporter_registration'] =  "Registrazione Segnalazioni Maia";

    $lang['adminhelp_reporter_password'] =  "<b>%s</b> imposta la password che il tuo script per le segnalzioni Maia " .
                                        "utilizza per autenticarsi al server di segnalazioni.  Deve corrispondere " .
                                        "a quella impostata quando hai registrato il tuo Maia " .
                                        "Reporter ID.";

    $lang['adminhelp_enable_charts'] =  "<b>%s</b> puoi abilitare o disabilitare i grafici in Maia " .
                                    "Per utilizzare i grafici ovviamente devi abilitare l'opzione <b>%s</b>. " .
				    "Puoi scegliere di avere i grafici dinamicamente ogni volta lo richiedi o " .
                                    "che vengano generati in base a dei tempi stabiliti e vengano spediti all'utente " .
                                    "come pagina statica.  Guarda <b>%s</b> per maggiori informazioni.";

    $lang['adminhelp_chart_ham_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare il " .
                                       "non-spam confermato(e-mail legittime) nei grafici.";

    $lang['adminhelp_chart_spam_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare lo " .
                                       "spam confermato nei grafici.";
    
    $lang['adminhelp_chart_virus_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare i " .
                                       "virus e altre forme di malware nei grafici.";

    $lang['adminhelp_chart_fp_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare i " .
                                       "falsi positivi nei grafici.";

    $lang['adminhelp_chart_fn_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare i " .
                                       "falsi negativi nei grafici.";

    $lang['adminhelp_chart_suspected_ham_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare i " .
                                       "non-spam non confermati nei grafici.";

    $lang['adminhelp_chart_suspected_spam_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare lo " .
                                       "spam sospetto nei grafici.";

    $lang['adminhelp_chart_wl_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare i " .
                                       "mittenti delle liste bianche nei grafici.";

    $lang['adminhelp_chart_bl_colour'] =  "<b>%s</b> specifica il colore utilizzato per rappresentare i " .
                                       "mittenti delle liste nere nei grafici.";

    $lang['adminhelp_chart_background_colour'] =  "<b>%s</b> specifica il colore di sfondo utilizzato nei grafici.";

    $lang['adminhelp_chart_font_colour'] =  "<b>%s</b> specifica il colore dei caratteri che appaiono nei grafici.";

    $lang['adminhelp_chart_autogeneration_interval'] =  "<b>%s</b> puoi specificare il tempo (in minuti) " .
                                                    "dopo il quale il grafico viene aggiornato automaticamente.  Se " .
                                                    "lo imposti a 0, questa opzione è disabilitata, " .
                                                    "e i grafici vengono generati dinamicamente, tramite " .
                                                    "ogni richiesta dell'utente.  in un sistema molto trafficato " .
                                                    "ha senso auto generare i grafici ad intervalli regolari " .
                                                    "e mostrare agli utenti grafici statici, in quanto " .
                                                    "generare i grafici dinamicamente richiede un grosso utilizzo " .
                                                    "delle risorse del sistema che può rallentare notevolmente la velocità " .
                                                    "del tuo sistema.";




    // Statistics
    $lang['adminhelp_reset_stats'] =  "<b>%s</b> abilita l'amministratore al reset dei contatori delle statistiche " .
                                  "di Maia inclusi i contatori dei virus, delle regole di SpamAssassin e delle statistiche " .
                                  "delle email.  Questo non avrà effetto per le statistiche relative al non-spam non confermato " .
                                  "o spam sospetto q comunque verrà utilizzato direttamente per calcolare gli oggetti presenti " .
                                  "negli archivi/area Quarantena.";



?>
