<?php
    /*
     * $Id: adminsystem.php 631 2005-05-03 19:19:22Z jleaver $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Amministrazione: Configurazione del Sistema";

    // Table header
    $lang['header_system_menu'] =  "Configurazione del Sistema";
    $lang['header_charts'] =  "Grafici";
    $lang['header_reminders'] =  "Archivio Scadenze & Allarmi Quarantena";
    $lang['header_authentication'] =  "Autenticazione";
    $lang['header_virus_info'] =  "Informazioni Virus";
    $lang['header_display'] =  "Mostra";
    $lang['header_paths'] =  "Percorsi & Porte";
    $lang['header_bandwidth'] =  "Gestione Banda";
    $lang['header_stats_reporting'] =  "Statistiche Segnalazioni";

    // Text labels
    $lang['text_yes'] =  "Si";
    $lang['text_no'] =  "No";
    $lang['text_accept'] =  "Accettato";
    $lang['text_reject'] =  "Respinto";
    $lang['text_enable_user_autocreation'] =  "Abilita auto-creazione degli utenti?";
    $lang['text_internal_auth'] =  "Password automatica per i nuovi utenti?";
    $lang['text_enable_false_negative_management'] =  "Abilito tracciamento dei falsi negativi?";
    $lang['text_enable_stats_tracking'] =  "Abilito tracciamento delle statistiche?";
    $lang['text_enable_virus_scanning'] =  "Abilito scansione virus?";
    $lang['text_enable_spam_filtering'] =  "Abilito filtraggio spam?";
    $lang['text_enable_banned_files_checking'] =  "Abilito controllo file vietati?";
    $lang['text_enable_bad_header_checking'] =  "Abilito controllo per intestazioni mail non valide?";
    $lang['text_enable_spamtraps'] =  "Abilita la presa dello spam da parte degli utenti?";
    $lang['text_enable_charts'] =  "Abilito grafici?";
    $lang['text_enable_address_linking'] =  "Permetti agli utenti di collegare indirizzi e-mail ai loro utenti?";
    $lang['text_enable_username_changes'] =  "Permetti agli utenti di cambiare il loro nome utente?";
    $lang['text_enable_privacy_invasion'] =  "Permetti agli amministratori di leggere le e-mail degli utenti?";
    $lang['text_system_default_user_is_local'] =  "Permetti solo al'utente predefinito (@.) di prendere l'email della casella locale?";
    $lang['text_user_virus_scanning'] =  "Permetti agli utenti di abilitare/disabilitare la scansione virus?";
    $lang['text_user_spam_filtering'] =  "Permetti agli utenti di abilitare/disabilitare il filtraggio dello spam?";
    $lang['text_user_banned_files_checking'] =  "Permetti agli utenti di abilitare/disabilitare il controllo file vietati?";
    $lang['text_user_bad_header_checking'] =  "Permetti agli utenti di abilitare/disabilitare il controllo delle intesazioni e-mail non valide?";
    $lang['text_size_limit'] =  "Limite massimo per e-Mail (bytes):";
    $lang['text_oversize_policy'] =  "Le email oltre il limite deveono essere...";
    $lang['text_admin_email'] =  "Contatto e-mail dell'amministratore:";
    $lang['text_smtp_server'] =  "Downstream SMTP server (MTA-TX):";
    $lang['text_smtp_port'] =  "Numero porta Downstream SMTP:";
    $lang['text_key_file'] =  "File chiave criptata (opzionale):";
    $lang['text_newuser_template_file'] =  "File modello per l'email spedita ai nuovi utenti:";
    $lang['text_chart_ham_colour'] =  "Colore da utilizzare per visualizzare il non-spam confermato:";
    $lang['text_chart_spam_colour'] =  "Colore da utilizzare per visualizzare lo spam confermato:";
    $lang['text_chart_virus_colour'] =  "Colore da utilizzare per visualizzare i virus:";
    $lang['text_chart_fp_colour'] =  "Colore da utilizzare per visualizzare i falsi positivi:";
    $lang['text_chart_fn_colour'] =  "Colore da utilizzare per visualizzare i falsi negativi:";
    $lang['text_chart_suspected_ham_colour'] =  "Colore da utilizzare per visualizzare il non-spam non confermato:";
    $lang['text_chart_suspected_spam_colour'] =  "Colore da utilizzare per visualizzare lo spam sospetto:";
    $lang['text_chart_wl_colour'] =  "Colore da utilizzare per visualizzare gli oggetti nelle liste bianche:";
    $lang['text_chart_bl_colour'] =  "Colore da utilizzare per visualizzare gli oggetti nelle liste nere:";
    $lang['text_chart_background_colour'] =  "Colore da utilizzare per lo sfondo dei grafici:";
    $lang['text_chart_font_colour'] =  "Colore da utilizzare per i caratteri dei grafici:";
    $lang['text_chart_autogeneration_interval'] =  "Intervallo per l'auto-creazione dei grafici (minuti):";
    $lang['text_expiry_period'] =  "Periodo di scadenza per le email in quarantena (giorni):";
    $lang['text_ham_cache_expiry_period'] =  "Periodo di scadenza per gli archivi non-spam (giorni):";
    $lang['text_reminder_threshold_count'] =  "Soglia per E-mail allarme (oggetti):";
    $lang['text_reminder_threshold_size'] =  "Soglia per E-mail allarme (dimensione):";
    $lang['text_reminder_template_file'] =  "File modello E-mail allarme:";
    $lang['text_reminder_login_url'] =  "Indirizzo URL Maia nelle e-mail allarme:";
    $lang['text_banner_title'] =  "Titolo della sezione in alto alla pagina:";
    $lang['text_use_icons'] =  "Mostra le icone nella sezione barra degli strumenti?";
    $lang['text_use_logo'] =  "Mostra il logo nella sezione in alto della pagina?";
    $lang['text_logo_file'] =  "File immagine utilizzato come logo:";
    $lang['text_logo_alt_text'] =  "Testo alternativo per il l'immagine del logo:";
    $lang['text_logo_url'] =  "URL al quale è collegato il logo:";
    $lang['text_virus_info_url'] =  "URL per le informazioni circa i virus:";
    $lang['text_virus_lookup'] =  "Regole per la riscrittura dei nomi dei virus:";
    $lang['text_none'] =  "Nessuno (nessuna ricerca)";
    $lang['text_google'] =  "Ricerca Google";
    $lang['text_fprot'] =  "F-Prot";
    $lang['text_fsecure'] =  "F-Secure";
    $lang['text_fsecurejp'] =  "F-Secure Japan";
    $lang['text_sophos'] =  "Sophos";
    $lang['text_nod32'] =  "NOD32";
    $lang['text_norman'] =  "Norman Virus Control";
    $lang['text_trend'] =  "Trend Micro";
    $lang['text_symantec'] =  "Symantec";
    $lang['text_mcafee'] =  "McAfee VirusScan";
    $lang['text_currency_label'] =  "Simbolo valuta:";
    $lang['text_bandwidth_cost'] =  "Costo mensile di un gigabyte di banda:";
    $lang['text_enable_stats_reporting'] =  "Abilito le segnalazioni delle statistiche del sito?";
    $lang['text_primary_report_server'] =  "Server di segnalazione statistiche primario:";
    $lang['text_primary_report_port'] =  "Numero porta server di segnalazione principale:";
    $lang['text_secondary_report_server'] =  "Server di segnalazione statistiche secondario:";
    $lang['text_secondary_report_port'] =  "Numero porta server di segnalazione secondario:";
    $lang['text_reporter_sitename'] =  "Nome del tuo sito:";
    $lang['text_reporter_username'] =  "Il Reporter ID per il tuo sistema Maia:";
    $lang['text_reporter_password'] =  "la password di segnalazione per il tuo sistema:";

    // Buttons
    $lang['button_submit'] =  "Aggiorna Impostazioni";
    $lang['button_restore'] =  "Resetta il Form";

    // Links
    $lang['link_admin_menu'] =  "Ritorna al menù amministrazione";
?>
