<?php
    /*
     * $Id: adminusers.php 293 2004-09-07 17:34:55Z jleaver $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Amministrazione: Utenti";

    // Table headers
    $lang['header_users_menu'] =  "Utenti";
    $lang['header_add_email'] =  "Aggiungi nuova Email/Alias";
    $lang['header_link_email'] =  "Collegamento E-mail/Alias";
    $lang['header_delete_email'] =  "Cancella E-mail/Alias";
    $lang['header_delete_user'] =  "Cancella Utenti";

    // Text messages
    $lang['text_lookup_user'] =  "Cerca utente";
    $lang['text_wildcard'] =  "metacarattere";
    $lang['text_new_email'] =  "Nuovo E-mail/alias";
    $lang['text_email'] =  "Indirizzi E-mail/alias";
    $lang['text_user'] =  "Utente";
    $lang['text_delete_email'] =  "Indirizzi E-mail/alias";
    $lang['text_address_linked'] =  "Collega %s all'utente %s.";
    $lang['text_address_not_linked'] =  "Impossibile collegare uno o più indirizzi agli utenti.";
    $lang['text_address_added'] =  "L'indirizzo %s è stato aggiunto.";
    $lang['text_address_not_added'] =  "L'indirizzo %s NON può essere aggiunto.";
    $lang['text_address_deleted'] =  "L'email selezionata è stata cancellata.";
    $lang['text_address_not_deleted'] =  "Uno o più indirizzi selezionati NON può essere cancellato.";
    $lang['text_user_found'] =  "%ld Utenti Trovati";
    $lang['text_user_not_found'] =  "Nessun utente corrisponde alla ricerca effettuata.";
    $lang['text_user_deleted'] =  "L'utente selezionato è stato cancellato.";
    $lang['text_user_not_deleted'] =  "Uno o più utenti selezionati NON può essere cancellato.";
    $lang['text_email_subject'] =  "Benvenuto a Maia Mailguard";
    $lang['text_email_from'] =  "Maia Mailguard";
    $lang['text_no_users'] =  "Nessun Utente è disponibile";
    $lang['text_no_addresses'] =  "Nessun indirizzo e-mail è disponibile";


    // Buttons
    $lang['button_lookup'] =  "Trova Utenti";
    $lang['button_add_email'] =  "Aggiungi Nuovo E-mail/Alias";
    $lang['button_link_email'] =  "Collega E-mail/Alias";
    $lang['button_delete_email'] =  "Cancella E-mail/Alias";
    $lang['button_delete_user'] =  "Cancella Utenti";

    // Links
    $lang['link_admin_menu'] =  "Ritorna al menù Amministrazione";
    $lang['link_users_menu'] =  "Ritorna al menù Utenti";
?>
