<?php
    /*
     * $Id: quarantine.php 631 2005-05-03 19:19:22Z jleaver $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Area Quarantena";

    // Table headers
    $lang['header_spam'] =  "Sospetto Spam";
    $lang['header_viruses'] =  "Viruses/Malware";
    $lang['header_banned_files'] =  "File Allegati Vietati";
    $lang['header_bad_headers'] =  "Intestazioni Mail Invalide";
    $lang['header_quarantine_contents'] =  "Quarantine Contents";

    // Text labels
    $lang['text_item'] =  "Oggetto";
    $lang['text_items'] =  "Oggetti";
    $lang['text_score'] =  "Punteggio";
    $lang['text_received'] =  "Ricevuti";
    $lang['text_from'] =  "Da";
    $lang['text_to'] =  "A";
    $lang['text_ham'] =  "Non-spam?";
    $lang['text_spam'] =  "Spam?";
    $lang['text_rescue'] =  "Non-spam!";
    $lang['text_delete'] =  "Cancella";
    $lang['text_subject'] =  "Oggetto";
    $lang['text_virus'] =  "Virus";
    $lang['text_file_name'] =  "Nome File";
    $lang['text_no_subject'] =  "senza oggetto";
    $lang['text_empty'] =  "La tua area quarantena è vuota.";
    $lang['text_updated'] =  "La tua area quarantena è stata aggiornata.";
    $lang['text_of'] =  "di";
    $lang['text_spam_confirmed'] =  "%d oggetti di spam sospetto sono stati confermati";
    $lang['text_spam_rescued'] =  "%d oggetti di spam sospetto sono stati recuperati";
    $lang['text_spam_deleted'] =  "%d oggetti di sospetto spam sono stati cancellati";
    $lang['text_viruses_rescued'] =  "%d di oggetti virus/malware sono stati recuperati";
    $lang['text_viruses_deleted'] =  "%d di oggetti virus/malware sono stati cancellati";
    $lang['text_attachments_rescued'] =  "%d oggetti con file allegati vietati sono stati recuperati";
    $lang['text_attachments_deleted'] =  "%d oggetti con file allegati vietati sono stati cancellati";
    $lang['text_headers_rescued'] =  "%d e-mail corrotte sono state recuperate";
    $lang['text_headers_deleted'] =  "%d e-mail corrotte sono state cancellate";
    $lang['text_suspected_spam_item'] =  "Oggetto Sospetto spam";
    $lang['text_suspected_spam_items'] =  "Oggetti Sospetto spam";
    $lang['text_virus_item'] =  "Oggetto Virus/Malware";
    $lang['text_virus_items'] =  "Oggetti Virus/Malware";
    $lang['text_banned_file_item'] =  "Allegato file vietato";
    $lang['text_banned_file_items'] =  "Allegati file vietati";
    $lang['text_bad_header_item'] =  "E-mail corrotta";
    $lang['text_bad_header_items'] =  "E-mail corrotte";


    // Button text
    $lang['button_confirm_spam'] =  "TUTTI gli oggetti nella lista sono Spam";
    $lang['button_delete_viruses'] =  "Cancella questi Virus";
    $lang['button_delete_attachments'] =  "Cancella questi File";
    $lang['button_delete_headers'] =  "Cancella queste e-mail corrotte";
    $lang['button_confirm'] =  "Conferma lo stato di questi oggetti";
    $lang['button_delete_all_items'] =  "Cancella TUTTI gli oggetti in quarantena";

    // Link text
    $lang['link_prev'] =  "Prec";
    $lang['link_next'] =  "Succ";
    $lang['link_quarantine'] =  "Ritorna al menù Quarantena";
    $lang['link_welcome']  = "Ritorna alla pagina di Benvenuto";

?>
