<?php
    /*
     * $Id: settings.php 734 2005-07-20 01:22:39Z dmorton $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Settaggio filtraggio mail";

    // Table headers
    $lang['header_addresses'] =  "Indirizzi E-mail";
    $lang['header_miscellaneous'] =  "Settaggi vari";
    $lang['header_address'] =  "Indirizzo";
    $lang['header_login_info'] =  "Credenziali accesso";

    // Text messages
    $lang['text_username'] =  "Nome utente";
    $lang['text_email_address'] =  "Indirizzo E-mail";
    $lang['text_password'] =  "Password";
    $lang['text_reminders'] =  "Invia promemoria mail in quarantena?";
    $lang['text_charts'] =  "Visualizza grafici?";
    $lang['text_yes'] =  "Si";
    $lang['text_no'] =  "No";
    $lang['text_virus_scanning'] =  "Verifica virus";
    $lang['text_enabled'] =  "Abilitato";
    $lang['text_disabled'] =  "Disabilitato";
    $lang['text_quarantined'] =  "Messe in quarantena";
    $lang['text_labeled'] =  "Segnate";
    $lang['text_discarded'] =  "Scartate";
    $lang['text_detected_viruses'] =  "Le mail con virus devono essere...";
    $lang['text_spam_filtering'] =  "Filtraggio SPAM";
    $lang['text_detected_spam'] =  "Le mail di SPAM devono essere...";
    $lang['text_prefix_subject'] =  "Aggiungere un prefisso all'oggetto della mail";
    $lang['text_add_spam_header'] =  "Aggiungi header X-Spam quando il punteggio e'";
    $lang['text_consider_mail_spam'] =  "Considerare una mail SPAM quando il punteggio e'";
    $lang['text_quarantine_spam'] =  "Mettere in quarantena per spam quando il punteggio e'";
    $lang['text_kill_spam'] =  "Scarate mail di Spam (senza quarantena) quando il punteggio e'";
    $lang['text_attachment_filtering'] =  "Filtraggio tipi allegati";
    $lang['text_mail_with_attachments'] =  "Mail con allegati pericolosi devono essere...";
    $lang['text_bad_header_filtering'] =  "Filtraggio Bad Header";
    $lang['text_mail_with_bad_headers'] =  "Le mail con bad headers devono essere...";
    $lang['text_settings_updated'] =  "Le tue configurazioni dei filtri sono state salvate";
    $lang['text_address_added'] =  "L'Indirizzo %s e' stato collegato al tuo account.";
    $lang['text_login_failed'] =  "Autenticazione fallita per '%s'.";
    $lang['text_primary'] =  "Indirizzo principale";
    $lang['text_no_addresses_linked'] =  "nessun indirizzo e' stato collegato con questo account";
    $lang['text_new_primary_email'] =  "%s e' il tuo indirizzo E-Mail principale";
    $lang['text_language'] =  "Lingua visualizzata";
    $lang['text_charset'] =  "Character Set visualizzato";
    $lang['text_theme']	= "Tema";
    $lang['text_spamtrap'] =  "E' un account spam-trap?";
    $lang['text_auto_whitelist'] =  "Aggiungi il mittente di mail recuperate nella whitelist?";
    $lang['text_items_per_page'] =  "Numero di mail da mostrare per pagina";
    $lang['text_digest_interval'] = "Intervallo invio mail promemoria? (-1 per disattivare, in minuti, 1 giorno = 1440)";
    $lang['text_new_login_name'] =  "Nuovo Username";
    $lang['text_new_password'] =  "Nuova Password";
    $lang['text_confirm_new_password'] =  "Confermi la nuova password";
    $lang['text_login_name_empty'] =  "Uno username e' richiesto.";
    $lang['text_login_name_not_allowed'] =  "I nomi utenti non possono iniziare con '@'.";
    $lang['text_password_empty'] =  "Bisogna inserire una password e' la sua conferma.";
    $lang['text_password_mismatch'] =  "la password e la sua conferma non corrispondono.";
    $lang['text_login_name_exists'] =  "Il nome utente richiesto e' gia' stato preso da un'altro utente.";
    $lang['text_password_updated'] =  "la tua password e' stata cambiata.";
    $lang['text_credentials_updated'] =  "Il tuo nome utente e la tua password sono state cambiate.";
    $lang['text_truncate_subject'] =  "Limitazione lunghezza soggetto (in caratteri)";
    $lang['text_truncate_email'] =  "Limitazione lunghezza mail (in caratteri)";

    // Buttons
    $lang['button_add_email_address'] =  "Aggiungi indirizzi E-Mail";
    $lang['button_reset'] =  "Reset";
    $lang['button_update_misc'] =  "Aggiorna settaggi vari";
    $lang['button_update_address'] =  "Aggiorna i settaggi per la tua casella di posta";
    $lang['button_update_all_addresses'] =  "Aggiorna i settaggi di tutte le caselle";
    $lang['button_make_primary'] =  "Rendi primario";
    $lang['button_change_login_info'] =  "Aggiorna credenziali di accesso";

    // Links
    $lang['link_settings'] =  "Ritorna alla pagina dei settaggi";
?>
