<?php
    /*
     * $Id: welcome.php 631 2005-05-03 19:19:22Z jleaver $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Benvenuto a Maia Mailguard!";
    $lang['text_welcome_first_time'] = "Benvenuto a Maia Mailguard. Vedo che è la prima volta che effettui l'accesso. Per favore leggi tutto il messaggio, dovrebbe aiutarti a capire
                                        l'importanza della tua partecipazione al blocco dello spam.<P>
                                        Prima di tutto, abilita la protezione allo spam velocemente, basta scegliere uno dei livelli proposti qui sotto e quindi clicca su \"Cambia Livello\".  Il livello \"alto\" è perfettamento sicuro ed è quello raccomandato.
                                        <P>Maia Mailguard può filtrare le tue email a può bloccare molti dei messaggi non desiderati che arrivano nella tua posta in entrata.  Se commette un errore , comunque, non tutto è perduto.
                                        Maia può tenere in quarantena le tue email, rendendole accessibili da questa pagina, per essere \"recuperate\", o \"segnalate\" da utenti autorizzati.  Inoltre ti puoi aiutare ad istruire i filtrei quando pezzi di spam non vengono filtrati
                                        segnalando dal tuo \"archivio non-spam\" - una serie di email recenti considerate delle buone email.";
    $lang['text_welcome_intro'] = "<p>Utilizza subito Maia Mailguard per bloccare la posta indesiderata.  Quando un' e-mail è presente nel pannello qui sotto tu puoi
                                    istruire Maia circa le differnze tra le buone email (non-spam) e le mail indesiderate(spam).  Per favore dedice del tempo affinchè tu sia sicuro che  
                                    tutti gli oggetti vengano correttamente segnalati; se non hai tempo per fare ciò, per favore cancella tutti tutti gli oggetti che hai segnalato non correttamente.<p>
                                    Tieni a mente, Maia può segnalare gli oggetti confermati come spam ad altri servizi o alle autorità. Continuando con il processo di segnalazione, 
                                    puoi aiutare la guerra contro lo spam.";
    $lang['text_welcome_current_level'] = "Livello di protezione corrente:"; 
    $lang['text_welcome_custom_level'] = "**Livelli personalizzati in uso:<br>Utilizza la sessione impostazioni per gestire, o scegliere un livello prestabilito.";
    $lang['header_cache_contents'] = "Indice Archivi";
    
    $lang['text_suspected_spam_item']= "Sospetto Spam:";
    $lang['text_suspected_ham_item'] = "Non-spam non confermato:";
    $lang['text_virus_item'] =  "Virus/Malware:";
    $lang['text_banned_file_item'] =  "File Vietati:";
    $lang['text_bad_header_item'] =  "E-mail Corrotte:";
    
    $lang['text_welcome_spam_blocked'] = "SPAM bloccati per te";
    $lang['text_welcome_virus_blocked'] = "Virus bloccati per te";
    $lang['text_welcome_spam_blocked_system'] = "Spam bloccati per tutto il sistema";
    $lang['text_welcome_virus_blocked_system'] = "Virus  bloccati per tutto il sistema";
    $lang['button_delete_all_items'] = "Cancella tutti gli oggetti";
    $lang['button_change_protection'] = "Cambia Livello";
    
    $lang['radio_protection'] = array(  'off' => "Disattivato",
		 								'low' => "Basso",
     									'medium' => "Medio",
										'high' => "Alto",
										'custom' => "Personalizzato");
    
    $lang['banner_subtitle'] = "Benvenuto";
    
    $lang['text_cache_spam'] = "Tu hai <b>%d</b> oggetti nel tuo archivio spam.  <br>Clicca <a href=\"%s\">qui</a> per segnalarli, o per recuperare il messaggio che per errore è stato bloccato.";
    $lang['text_cache_virus'] = "Tu hai <b>%d</b> oggetti nel tuo archivio virus.  <br>Clicca <a href=\"%s\">qui</a> per cancellarli, o per recuperare il messaggio che per errore è stato bloccato.";
    $lang['text_cache_banned'] = "Tu hai <b>%d</b> oggetti nel tuo archivio file vietati.  <br>Clicca <a href=\"%s\">qui</a> per cancellarli, o per recuperare un messaggio che per errore è stato bloccato.";
    
    $lang['text_cache_header'] = "Tu hai <b>%d</b> oggetti nel tuo archivio cattive-intestazioni.  <br>Clicca <a href=\"%s\">qui</a> per cancellarli, o per recuperare un messaggio che per errore è stato bloccato.";
    $lang['text_cache_ham'] = "Tu hai <b>%d</b> oggetti nel tuo archivio non-spam.  <br>Clicca <a href=\"%s\">qui</a> per aiutare l'addestramento del filtro, o per segnalare un messaggio spam che è andato perso.";
    $lang['action_ham_cache']   = "Segnala/Conferma";
    $lang['action_spam_cache']  = "Segnala/Recupera";
    $lang['action_virus_cache'] = "Cancella/Recupera";
    $lang['action_banned_cache'] = "Cancella/Recupera";
    $lang['action_header_cache'] = "Cancella/Recupera";
