<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Spam jelentés";

    // Table headers
    $lang['header_suspected_ham'] =  "Nem igazolt Nem-spam";
    $lang['header_ham_cache_contents'] =  "Kézbesített Nem-spam levelek";

    // Text messages
    $lang['text_item'] =  "Levél";
    $lang['text_items'] =  "Levelek";
    $lang['text_score'] =  "Pont";
    $lang['text_received'] =  "Érkezett";
    $lang['text_from'] =  "Feladó";
    $lang['text_to'] =  "Címzett";
    $lang['text_spam'] =  "Spam?";
    $lang['text_ham'] =  "Nem-spam?";
    $lang['text_delete'] =  "Törlés";
    $lang['text_report'] =  "Spam!";
    $lang['text_subject'] =  "Tárgy";
    $lang['text_no_subject'] =  "nincs tárgya";
    $lang['text_empty'] =  "An Ön nem-spam listája még üres.";
    $lang['text_updated'] =  "Az Ön nem-spam listája frissítésre került.";
    $lang['text_of'] =  "/";
    $lang['text_ham_confirmed'] =  "%d eddig nem igazolt kézbesített nem-spam levél most igazolva";
    $lang['text_spam_reported'] =  "%d eddig nem igazolt kézbesített nem-spam levél most SPAM-nek jelentve (hibásan kedvezményezett)";
    $lang['text_ham_deleted'] =  "%d eddig nem igazolt nem-spam levél törölve";
    $lang['text_suspected_ham_item'] =  "Nem igazolt Nem-spam levél";
    $lang['text_suspected_ham_items'] =  "Nem igazolt Nem-spam levelek";

    // Buttons
    $lang['button_confirm_ham'] =  "MINDEN levél ezen a listán Nem-spam";
    $lang['button_confirm'] =  "Igazolom ezen levelek Állapotát";
    $lang['button_delete_all_cached_items'] =  "MINDEN listázott levél törlése";

    // Link text
    $lang['link_prev'] =  "Előző";
    $lang['link_next'] =  "Következő";
    $lang['link_report_spam'] =  "Vissza a kézbesített Nem-spam levelek listájához";
    $lang['link_welcome'] = "Vissza a főoldalra";

?>
