<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Mail Filter Settings";

    // Table headers
    $lang['header_addresses'] =  "E-mail címek";
    $lang['header_miscellaneous'] =  "Egyéb beállítások";
    $lang['header_address'] =  "Cím";
    $lang['header_login_info'] =  "Login Credentials";

    // Text messages
    $lang['text_username'] =  "Felhasználó";
    $lang['text_email_address'] =  "E-mail cím";
    $lang['text_password'] =  "Jelszó";
    $lang['text_reminders'] =  "Küldjön karantén emlékeztető e-mail-eket?";
    $lang['text_charts'] =  "Készítsen grafikus elemzéseket?";
    $lang['text_yes'] =  "Igen";
    $lang['text_no'] =  "Nem";
    $lang['text_virus_scanning'] =  "Vírus ellenőrzés";
    $lang['text_enabled'] =  "Bekapcsolva";
    $lang['text_disabled'] =  "Kikapcsolva";
    $lang['text_quarantined'] =  "Karanténezze";
    $lang['text_labeled'] =  "Cimkézze";
    $lang['text_discarded'] =  "Eldobja";
    $lang['text_detected_viruses'] =  "Felismert vírusokat ...";
    $lang['text_spam_filtering'] =  "Spam szűrés";
    $lang['text_detected_spam'] =  "Felismert spam-eket...";
    $lang['text_prefix_subject'] =  "Tegyen előjelzést a spam levelek tárgysorába";
    $lang['text_add_spam_header'] =  "Jelezze X-Spam: fejléccel ha a pontszám";
    $lang['text_consider_mail_spam'] =  "Tekintse 'Spam' levélnek ha a pontszám";
    $lang['text_quarantine_spam'] =  "Karanténezés az adott pontszám felett";
    $lang['text_kill_spam'] =  "Eldobja a Spam levelet (karanténezés nélkül) ha a pontszám";
    $lang['text_attachment_filtering'] =  "Csatolmány típusra szűrés";
    $lang['text_mail_with_attachments'] =  "Veszélyes csatolmányú levelek...";
    $lang['text_bad_header_filtering'] =  "Hibás fejlécű levelek szűrése";
    $lang['text_mail_with_bad_headers'] =  "A hibás fejlécű levelek...";
    $lang['text_settings_updated'] =  "Az Ön levél szűrés beállításait frissítettük.";
    $lang['text_address_added'] =  "Cím %s hozzárendelve az Ön felhasználói nevéhez.";
    $lang['text_login_failed'] =  "Azonosítási hiba '%s'-ho(ö)z.";
    $lang['text_primary'] =  "Elsődleges cím";
    $lang['text_no_addresses_linked'] =  "Nincs cím rendelve ehhez a felhasználóhoz.";
    $lang['text_new_primary_email'] =  "%s mostantól az Ön elsődleges e-mail címe.";
    $lang['text_language'] =  "Megjelenítés nyelve";
    $lang['text_charset'] =  "Megjelenítés karakter táblája";
    $lang['text_theme']	= "Téma";
    $lang['text_spamtrap'] =  "Ez egy spam-trap felhasználó?";
    $lang['text_auto_whitelist'] =  "A visszavett levelek feladóinak fehérlistára helyezése?";
    $lang['text_items_per_page'] =  "Az egy oldalon listázott bejegyzések száma?";
    $lang['text_digest_interval'] = "Email összefoglaló intervalluma? (órában, 0 a kikapcsoláshoz)";
    $lang['text_new_login_name'] =  "Új felhasználó";
    $lang['text_new_password'] =  "Új jelszó";
    $lang['text_confirm_new_password'] =  "Ismételt új jelszó";
    $lang['text_login_name_empty'] =  "Egy felhasználó név kötelező.";
    $lang['text_login_name_not_allowed'] =  "A felhasználónév nem kezdődhet '@' jellel.";
    $lang['text_password_empty'] =  "A jelszó vagy az ismétlés hiányzik.";
    $lang['text_password_mismatch'] =  "A jelszó és az ismétlés nem azonos.";
    $lang['text_login_name_exists'] =  "A kért felhasználó már valaki más használja.";
    $lang['text_password_updated'] =  "Az Ön jelszava megváltozott.";
    $lang['text_credentials_updated'] =  "Az Ön felhasználó neve és jelszava megváltozott.";

    // Buttons
    $lang['button_add_email_address'] =  "Plusz E-Mail cím";
    $lang['button_reset'] =  "Stornó";
    $lang['button_update_misc'] =  "Egyéb beállítások mentése";
    $lang['button_update_address'] =  "Beállítás mentése Erre a címre";
    $lang['button_update_all_addresses'] =  "Beállítás mentése MINDEN címre";
    $lang['button_make_primary'] =  "Legyen elsődleges";
    $lang['button_change_login_info'] =  "Update Login Credentials";

    // Links
    $lang['link_settings'] =  "Vissza a személyes beállításokhoz";
?>
