<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Beheer: Systeem configuratie";

    // Table header
    $lang['header_system_menu'] =  "Systeem Configuratie";
    $lang['header_charts'] =  "Grafieken";
    $lang['header_reminders'] =  "Cache Verloop & Quarantaine Herinneringen"; //
    $lang['header_authentication'] =  "Authenticatie";
    $lang['header_virus_info'] =  "Virus Informatie";
    $lang['header_display'] =  "Display"; //
    $lang['header_paths'] =  "Paden & Poorten"; //
    $lang['header_bandwidth'] =  "Bandbreedte Beheer"; //
    $lang['header_stats_reporting'] =  "Site Statistiek Rapportage"; //

    // Text labels
    $lang['text_yes'] =  "Ja";
    $lang['text_no'] =  "Nee";
    $lang['text_accept'] =  "Aanvaard";
    $lang['text_reject'] =  "Geweigerd";
    $lang['text_enable_user_autocreation'] =  "Toestaan auto-aanmaak van gebruikers accounts?";
    $lang['text_internal_auth'] =  "Automatisch passwoorden toekennen aan nieuwe accounts?";
    $lang['text_enable_false_negative_management'] =  "Bijhouden van false negatives aanzetten?";
    $lang['text_enable_stats_tracking'] =  "Bijhouden statistieken aanzetten?";
    $lang['text_enable_virus_scanning'] =  "Aanzetten virus scannen?";
    $lang['text_enable_spam_filtering'] =  "Aanzetten spam filteren?";
    $lang['text_enable_banned_files_checking'] =  "Checen op geweigerde exetensies?";
    $lang['text_enable_bad_header_checking'] =  "Checken op malafide headers?";
    $lang['text_enable_spamtraps'] =  "spam-trap accounts aanzetten?";
    $lang['text_enable_charts'] =  "Grafieken aanzetten?";
    $lang['text_enable_address_linking'] =  "Gebruikers toestaan e-mail adressen aan hun account te koppelen?";
    $lang['text_enable_username_changes'] =  "Gebruikers toestaan hun gebruikersnaam aan te passen?";
    $lang['text_enable_privacy_invasion'] =  "Beheerders toestaan mail van gebruikers te laten lezen?";
    $lang['text_system_default_user_is_local'] =  "Moet het standaard account (@.) uitsluitend mail van lokale begunstigden opslaan?";
    $lang['text_user_virus_scanning'] =  "Gebruikers toestaan de virusscanner individueel aan/uit te zetten?";
    $lang['text_user_spam_filtering'] =  "Gebruikers toestaan de spam filter individueel aan/uit te zetten?";
    $lang['text_user_banned_files_checking'] =  "Gebruikers toestaan het checken op uitgesloten extensies aan/uit te zetten?";
    $lang['text_user_bad_header_checking'] =  "Gebruikers toestaan de controle op malafide headers aan/uit te zetten?";
    $lang['text_size_limit'] =  "E-Mail omvanglimiet (bytes):";
    $lang['text_oversize_policy'] =  "Te grote e-mails moeten worden...";
    $lang['text_admin_email'] =  "Beheerders' e-mail adres:";
    $lang['text_smtp_server'] =  "Downstream SMTP server (MTA-TX):";
    $lang['text_smtp_port'] =  "Downstream SMTP poort nummer:";
    $lang['text_key_file'] =  "Encryptie sleutelbestand (optioneel):";
    $lang['text_newuser_template_file'] =  "Sjabloonbestand voor e-mail verstuurd aan nieuwe gebruikers:";
    $lang['text_chart_ham_colour'] =  "Kleur voor het tonen van bevestigde non-spam:";
    $lang['text_chart_spam_colour'] =  "Kleur voor het tonen van bevestigde spam:";
    $lang['text_chart_virus_colour'] =  "Kleur voor het tonen van virussen:";
    $lang['text_chart_fp_colour'] =  "Kleur voor het tonen van false positives:";
    $lang['text_chart_fn_colour'] =  "Kleur voor het tonen van false negatives:";
    $lang['text_chart_suspected_ham_colour'] =  "Kleur voor het tonen van vermeende non-spam:";
    $lang['text_chart_suspected_spam_colour'] =  "Kleur voor het tonen van vermeende spam:";
    $lang['text_chart_wl_colour'] =  "Kleur voor het tonen van whitelist items:";
    $lang['text_chart_bl_colour'] =  "Kleur voor het tonen van blacklist items:";
    $lang['text_chart_background_colour'] =  "Kleur voor grafiek achtergronden:";
    $lang['text_chart_font_colour'] =  "Kleur voor grafiek lettertypen:";
    $lang['text_chart_autogeneration_interval'] =  "Interval tussen het automatisch genereren van grafieken (in minuten):";
    $lang['text_expiry_period'] =  "Verloopperiode van mail in quarantaine (dagen):";
    $lang['text_ham_cache_expiry_period'] =  "Verloopperiode voor opgeslagen non-spam (dagen):";
    $lang['text_reminder_threshold_count'] =  "Ondergrens voor herinnerings e-mail (aantal):";
    $lang['text_reminder_threshold_size'] =  "Ondergrens voor herinnerings e-mail (omvang in bytes):";
    $lang['text_reminder_template_file'] =  "Sjabloonbestand voor herinnerings e-mail:";
    $lang['text_reminder_login_url'] =  "Maia inlog URL voor herinnerings e-mails:";
    $lang['text_banner_title'] =  "Paginatop balk titel:";
    $lang['text_use_icons'] =  "Toon iconen in de toolbar?";
    $lang['text_use_logo'] =  "Toon een logo in de bovenste balk?";
    $lang['text_logo_file'] =  "Afbeelding te gebruiken als logo:";
    $lang['text_logo_alt_text'] =  "Alternatieve tekst voor bij het logo plaatje:";
    $lang['text_logo_url'] =  "URL waar het logo naar moet doorlinken:";
    $lang['text_virus_info_url'] =  "URL sjabloon voor virus informatie:";
    $lang['text_virus_lookup'] =  "Virusnaam herschrijfregels:";
    $lang['text_none'] =  "Geen (geen lookups)";
    $lang['text_google'] =  "Google Search";
    $lang['text_fprot'] =  "F-Prot";
    $lang['text_fsecure'] =  "F-Secure";
    $lang['text_fsecurejp'] =  "F-Secure Japan";
    $lang['text_sophos'] =  "Sophos";
    $lang['text_nod32'] =  "NOD32";
    $lang['text_norman'] =  "Norman Virus Control";
    $lang['text_trend'] =  "Trend Micro";
    $lang['text_symantec'] =  "Symantec";
    $lang['text_mcafee'] =  "McAfee VirusScan";
    $lang['text_currency_label'] =  "Valuta symbool:";
    $lang['text_bandwidth_cost'] =  "Maandelijkse bandbreedte kosten per gigabyte:";
    $lang['text_enable_stats_reporting'] =  "Rapportage van statistieken aanzetten?";
    $lang['text_primary_report_server'] =  "Primaire stats rapporterende server:";
    $lang['text_primary_report_port'] =  "Poort nummer voor primaire rapporterende server:";
    $lang['text_secondary_report_server'] =  "Secundaire stats rapporterende server:";
    $lang['text_secondary_report_port'] =  "Poort nummer voor secundaire rapporterende server:";
    $lang['text_reporter_sitename'] =  "Naam van uw site:";
    $lang['text_reporter_username'] =  "Uw Maia Reporter's ID:";
    $lang['text_reporter_password'] =  "Uw Maia Reporter's wachtwoord:";

    // Buttons
    $lang['button_submit'] =  "Instellingen Opslaan";
    $lang['button_restore'] =  "Formulier Terugzetten";

    // Links
    $lang['link_admin_menu'] =  "Terug naar het Beheerdersmenu";
?>
