<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Domein Mail Filter Standaarden";

    // Table headers
    $lang['header_domain'] =  "Domein";
    $lang['header_admins'] =  "Domein Beheerders";
    $lang['header_revoke'] =  "Intrekken";
    $lang['header_admin_name'] =  "Beheerder";
    $lang['header_add_administrator'] =  "Voeg Beheerder Toe";

    // Text labels
    $lang['text_yes'] =  "Ja";
    $lang['text_no'] =  "Nee";
    $lang['text_virus_scanning'] =  "Virusscanner";
    $lang['text_enabled'] =  "Ingeschakeld";
    $lang['text_disabled'] =  "Uitgeschakeld";
    $lang['text_quarantined'] =  "In Quarantaine zetten";
    $lang['text_discarded'] =  "Weggooien";
    $lang['text_labeled'] =  "Markeren";
    $lang['text_detected_viruses'] =  "Actie voor berichten met virussen";
    $lang['text_spam_filtering'] =  "Spamfilter";
    $lang['text_detected_spam'] =  "Gedetecteerde spam moet worden...";
    $lang['text_prefix_subject'] =  "Voeg voorlooptekst aan onderwerp bij spam";
    $lang['text_add_spam_header'] =  "Voeg X-Spam: Headers toe bij een score";
    $lang['text_consider_mail_spam'] =  "Beschouw mail als 'spam' bij een score";
    $lang['text_quarantine_spam'] =  "Plaats mail in quarantaine bij een score";
    $lang['text_attachment_filtering'] =  "Bijlage-type filter";
    $lang['text_mail_with_attachments'] =  "Mail met een gevaarlijke extensie moet worden...";
    $lang['text_bad_header_filtering'] =  "Filteren op Malafide Headers";
    $lang['text_mail_with_bad_headers'] =  "Mail met malafide headers moet worden...";
    $lang['text_settings_updated'] =  "Uw mail filter standaarden zijn geupdate.";
    $lang['text_system_default'] =  "Systeemstandaard";
    $lang['text_no_admins'] =  "Geen beheerders zijn aan dit domein toegekend.";
    $lang['text_no_available_admins'] =  "Geen gebruikers zijn beschikbaar om dit domein te beheren.";
    $lang['text_administrators_added'] =  "De nieuwe beheerder(s) is/zijn toegevoegd aan dit domein.";
    $lang['text_admins_revoked'] =  "De geselecteerder gebruikers is het beheerdersrecht ontnomen.";
    $lang['text_cache_ham_question'] =  "Moeten non-spam mails bewaard worden in de cache?";
    $lang['text_enable_user_autocreation'] =  "Schakel het automatisch aanmaken van gebruikers aan?";
    $lang['text_enable_user_autocreation'] =  "Automatisch aanmaken van gebruikers inschakelen?";
    $lang['text_domain_theme'] = "Standaard sjabloon voor dit domein?";

    // Buttons
    $lang['button_reset'] =  "Herstel";
    $lang['button_update_domain'] =  "Update dit domein";
    $lang['button_revoke'] =  "Ontneem beheerdersrecht voor geselecteerde gebruikers";
    $lang['button_grant'] =  "Ken beheerdersrechten toe";

    // Links
    $lang['link_domain_settings'] =  "Terug naar Domeininstellingen";
    $lang['link_admin_domains'] =  "Terug naar de beheerdersmenu van domeinen";
?>
