<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Quarantaine omgeving";

    // Table headers
    $lang['header_spam'] =  "Vermeende Spam";
    $lang['header_viruses'] =  "Virussen/Malware";
    $lang['header_banned_files'] =  "Gebannen bijlagen";
    $lang['header_bad_headers'] =  "Malifide Mail Headers";
    $lang['header_quarantine_contents'] =  "Quarantaine Inhoud";

    // Text labels
    $lang['text_item'] =  "Berichten";
    $lang['text_items'] =  "Berichten";
    $lang['text_score'] =  "Score";
    $lang['text_received'] =  "Ontvangen";
    $lang['text_from'] =  "Van";
    $lang['text_to'] =  "Aan";
    $lang['text_ham'] =  "Non-Spam?";
    $lang['text_spam'] =  "Spam?";
    $lang['text_rescue'] =  "Non-Spam!";
    $lang['text_delete'] =  "Verwijder";
    $lang['text_subject'] =  "Onderwerp";
    $lang['text_virus'] =  "Virus";
    $lang['text_file_name'] =  "Bestandsnaam";
    $lang['text_no_subject'] =  "geen onderwerp";
    $lang['text_empty'] =  "Uw quarantaine omgeving is leeg.";
    $lang['text_updated'] =  "Uw quarantaine omgeving is geupdate.";
    $lang['text_of'] =  "van";
    $lang['text_spam_confirmed'] =  "%d vermeende spam berichten zijn bevestigd";
    $lang['text_spam_rescued'] =  "%d vermeende spam berichten zijn hersteld";
    $lang['text_spam_deleted'] =  "%d vermeende spam berichten zijn verwijderd";
    $lang['text_viruses_rescued'] =  "%d virus/malware berichten zijn hersteld";
    $lang['text_viruses_deleted'] =  "%d virus/malware berichten zijn verwijderd";
    $lang['text_attachments_rescued'] =  "%d geweigerde bijlagen zijn hersteld";
    $lang['text_attachments_deleted'] =  "%d geweigerde bijlagen zijn verwijderd";
    $lang['text_headers_rescued'] =  "%d e-mails met malafide headers zijn hersteld";
    $lang['text_headers_deleted'] =  "%d e-mails met malafide headers zijn verwijderd";
    $lang['text_suspected_spam_item'] =  "Vermeende Spambericht";
    $lang['text_suspected_spam_items'] =  "Vermeende Spamberichten";
    $lang['text_virus_item'] =  "Virus/Malware Bericht";
    $lang['text_virus_items'] =  "Virus/Malware Berichten";
    $lang['text_banned_file_item'] =  "Geweigerde bijlage";
    $lang['text_banned_file_items'] =  "Geweigerde bijlagen";
    $lang['text_bad_header_item'] =  "Bericht met malafide headers";
    $lang['text_bad_header_items'] =  "Berichten met malafide headers";


    // Button text
    $lang['button_confirm_spam'] =  "ALLE Berichten in deze lijst zijn Spam";
    $lang['button_delete_viruses'] =  "Verwijder deze Virussen";
    $lang['button_delete_attachments'] =  "Verwijder deze Bestanden";
    $lang['button_delete_headers'] =  "Verwijder deze Corrupte E-mails";
    $lang['button_confirm'] =  "Bevestig de Status van deze Berichten";
    $lang['button_delete_all_items'] =  "verwijder ALLE Quarantainee berichten";

    // Link text
    $lang['link_prev'] =  "Vorige";
    $lang['link_next'] =  "Volgende";
    $lang['link_quarantine'] =  "Terug naar Quarantaine Menu";
    $lang['link_welcome'] = "Keer terug naar beginscherm";

?>
