<?php
    // Перевод на русский язык: Айзятуллен Рамиль, http://www.arg.su, argo-uln@yandex.ru
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Администрирование: настройка системы";

    // Table header
    $lang['header_system_menu'] =  "Настройка системы";
    $lang['header_charts'] =  "Графики";
    $lang['header_reminders'] =  "Период хранения в кеше & Порог напоминаний карантина";
    $lang['header_authentication'] =  "Авторизация";
    $lang['header_virus_info'] =  "Информация о вирусах";
    $lang['header_display'] =  "Экран";
    $lang['header_paths'] =  "Пути и порты";
    $lang['header_bandwidth'] =  "Пропускная способность учетной записи";
    $lang['header_stats_reporting'] =  "Отправка отчетов на сайт статистики";

    // Text labels
    $lang['text_yes'] =  "Да";
    $lang['text_no'] =  "Нет";
    $lang['text_accept'] =  "Принято";
    $lang['text_reject'] =  "Отброшено";
    $lang['text_enable_user_autocreation'] =  "Включить автосоздание пользователей?";
    $lang['text_internal_auth'] =  "Включить автосоздание паролей?";
    $lang['text_enable_false_negative_management'] =  "Включить слежение ложных срабатываний?";
    $lang['text_enable_stats_tracking'] =  "Включить отслеживание статистики?";
    $lang['text_enable_virus_scanning'] =  "Включить антивирусное сканирование?";
    $lang['text_enable_spam_filtering'] =  "Включить фильтрацию спама?";
    $lang['text_enable_banned_files_checking'] =  "Включить проверку недозволенных вложений?";
    $lang['text_enable_bad_header_checking'] =  "Включить проверку ощибочных заголовков?";
    $lang['text_enable_spamtraps'] =  "Включить учетку ловушка спама?";
    $lang['text_enable_charts'] =  "Включить графические диаграммы?";
    $lang['text_enable_address_linking'] =  "Разрешить пользователям привязывать почтовые адреса к своим учетным записям?";
    $lang['text_enable_username_changes'] =  "Разрешить лпользователю изменять свой логин?";
    $lang['text_enable_privacy_invasion'] =  "Разрешить администратору просматривать письма пользователей?";
    $lang['text_system_default_user_is_local'] =  "Системный пользователь поумолчанию (@.) может получать письма для локальных получателей?";
    $lang['text_user_virus_scanning'] =  "Разрешить пользователям вкл/выключать проверку на вирусы?";
    $lang['text_user_spam_filtering'] =  "Разрешить пользователям вкл/выключать проверку на спам?";
    $lang['text_user_banned_files_checking'] =  "Разрешить пользователям вкл/выключать проверку запрещенных вложений?";
    $lang['text_user_bad_header_checking'] =  "Разрешить пользователям вкл/выключать проверку ошибочных заголовков?";
    $lang['text_size_limit'] =  "Лимит размера письма (в байтах):";
    $lang['text_oversize_policy'] =  "Письма превысившие максимальный размер должны быть...";
    $lang['text_admin_email'] =  "Почтовый адрес администратора:";
    $lang['text_smtp_server'] =  "Получаюший SMTP сервер (MTA-TX):";
    $lang['text_smtp_port'] =  "Получающий SMTP порт:";
    $lang['text_key_file'] =  "Ключ шифрования (опционально):";
    $lang['text_newuser_template_file'] =  "Шаблон файла для отправки новому пользователю:";
    $lang['text_chart_ham_colour'] =  "Цвет для отображения подтвержденного неспама:";
    $lang['text_chart_spam_colour'] =  "Цвет для отображения подтвержденного спама:";
    $lang['text_chart_virus_colour'] =  "Цвет для отображения вирусов:";
    $lang['text_chart_fp_colour'] =  "Цвет для отображения ложные срабатывания:";
    $lang['text_chart_fn_colour'] =  "Цвет для отображения подозрений на спам:";
    $lang['text_chart_suspected_ham_colour'] =  "Цвет для отображения непедтвержденного не спама:";
    $lang['text_chart_suspected_spam_colour'] =  "Цвет для отображения подозрение на спам:";
    $lang['text_chart_wl_colour'] =  "Цвет для отображения белого списка:";
    $lang['text_chart_bl_colour'] =  "Цвет для отображения черного списка:";
    $lang['text_chart_background_colour'] =  "Цвет для отображения фона графиков:";
    $lang['text_chart_font_colour'] =  "Цвет для отображения шрифтов диаграмм:";
    $lang['text_chart_autogeneration_interval'] =  "Интервал автогенерации графиков (в минутах):";
    $lang['text_expiry_period'] =  "Период хранения для карантина (дней):";
    $lang['text_ham_cache_expiry_period'] =  "Период хранения для не спам кеша (days):";
    $lang['text_reminder_threshold_count'] =  "Почтовый порог напоминания (писем):";
    $lang['text_reminder_threshold_size'] =  "Почтовый порог напоминания (размер):";
    $lang['text_reminder_template_file'] =  "Шаблон письма напоминания:";
    $lang['text_reminder_login_url'] =  "http ссылка Maia для почтового напоминания:";
    $lang['text_banner_title'] =  "Верхний заголовок страницы:";
    $lang['text_use_icons'] =  "Показывать иконки в меню?";
    $lang['text_use_logo'] =  "Показывать логотип в заголовке страницы?";
    $lang['text_logo_file'] =  "Файл, используемый как логотип:";
    $lang['text_logo_alt_text'] =  "Альтернативный текст для логотипа:";
    $lang['text_logo_url'] =  "Ссылка на картинке логотипе:";
    $lang['text_virus_info_url'] =  "Ссылка шаблон на информацию о вирусе:";
    $lang['text_virus_lookup'] =  "Правила перезаписи названия вируса:";
    $lang['text_none'] =  "Не определено (не искать)";
    $lang['text_google'] =  "Поиск Google";
    $lang['text_fprot'] =  "F-Prot";
    $lang['text_fsecure'] =  "F-Secure";
    $lang['text_fsecurejp'] =  "F-Secure Japan";
    $lang['text_sophos'] =  "Sophos";
    $lang['text_nod32'] =  "NOD32";
    $lang['text_norman'] =  "Norman Virus Control";
    $lang['text_trend'] =  "Trend Micro";
    $lang['text_symantec'] =  "Symantec";
    $lang['text_mcafee'] =  "McAfee VirusScan";
    $lang['text_currency_label'] =  "Текущее обозначение денежной единицы:";
    $lang['text_bandwidth_cost'] =  "Месячная полоса пропускания в гигабайтах:";
    $lang['text_enable_stats_reporting'] =  "Включить отчет о статистике сайта?";
    $lang['text_primary_report_server'] =  "Основной сервер статистики:";
    $lang['text_primary_report_port'] =  "Порт основного сервера статистики:";
    $lang['text_secondary_report_server'] =  "Дополнительный сервер статистики:";
    $lang['text_secondary_report_port'] =  "Порт дополнительного сервера статистики:";
    $lang['text_reporter_sitename'] =  "Имя вашего сервера:";
    $lang['text_reporter_username'] =  "Ваш Maia Reporter ID:";
    $lang['text_reporter_password'] =  "Ваш reporter пароль:";

    // Buttons
    $lang['button_submit'] =  "Обновить настройки";
    $lang['button_restore'] =  "Сбросить";

    // Links
    $lang['link_admin_menu'] =  "Return to the Administration Menu";
?>
