<?php
    // Перевод на русский язык: Айзятуллен Рамиль, http://www.arg.su, argo-uln@yandex.ru
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Menu items
    $lang['menu_welcome'] = "Добро пожаловать";
    $lang['menu_stats'] =  "Статистика";
    $lang['menu_settings'] =  "Настройки";
    $lang['menu_whiteblacklist'] =  "Белый/Черный Список";
    $lang['menu_quarantine'] =  "Карантин";
    $lang['menu_report'] =  "Отчет о спаме";
    $lang['menu_admin'] =  "Администратор";
    $lang['menu_help'] =  "Помощь";
    $lang['menu_logout'] =  "Выход";

    // Text messages
    $lang['text_version'] =  "Версия";
    $lang['text_all_users'] =  "все пользователи";
    $lang['text_day'] =  "День";
    $lang['text_efficiency'] =  "Эффективность";
    $lang['text_sensitivity'] =  "Чувствительность";
    $lang['text_specificity'] =  "Специфика";
    $lang['text_ppv'] =  "PPV";
    $lang['text_npv'] =  "NPV";
    $lang['text_false_positive'] =  "Ложное срабатывание";
    $lang['text_false_negative'] =  "Пропущенный спам";
    $lang['powered_by'] = "Поддержка Maia Mailguard - http://www.maiamailguard.com";
    
    $lang['text_truncate_subject'] = "Обрезать не email строку до: (символов)";
    $lang['text_truncate_email'] = "Обрезать email строку до: (символов)";

    // Links
    $lang['link_systemwide'] =  "Просмотр системной статистики";
    $lang['link_personal'] =  "Просмотр персональной статистики";
    $lang['link_viruses'] =  "Просмотр статистики вирусов";
    $lang['link_rules'] =  "Просмотр статистики правил SpamAssassin";

    // Table headers
    $lang['header_score'] =  "Баллы";
    $lang['header_count'] =  "Счетчик";
    $lang['header_size'] =  "Размер";
    $lang['header_min'] =  "Мин";
    $lang['header_max'] =  "Макс";
    $lang['header_average'] =  "Средний";
    $lang['header_bandwidth'] =  "Полоса пропускания";
    $lang['header_percent'] =  "Процент";
    $lang['header_cost'] =  "Стоимость";
    $lang['header_items'] =  "Письмо";
    $lang['header_type'] =  "Тип письма";
    $lang['header_user'] =  "Статистика для пользователя: %s";
    $lang['header_systemwide'] =  "Статистика для всех пользователей";
    $lang['header_spam_score'] =  "Баллы";
    $lang['header_rule_triggered'] =  "Сработавшее правило";
    $lang['header_explanation'] =  "Объяснение";

    $lang['array_header'] =  array("ham"            => "Подтвержденный не спам",
                                      "suspected_ham"  => "Неподтвержденный не спам",
                                      "suspected_spam" => "Подозрение на спам",
                                      "spam"           => "Подтвержденный спам",
                                      "virus"          => "Вирусы",
                                      "fp"             => "Ложные срабатывания",
                                      "fn"             => "Пропущенный спам",
                                      "wl"             => "Белый список",
                                      "bl"             => "Черный список",
                                      "bad_header"     => "Некорректные заголовки",
                                      "banned_file"    => "Запрещенные вложения",
                                      "oversized"       => "Негабаритные письма");

    $lang['array_count'] =  array("ham"            => "Подтверждение на не спам принято",
                                      "suspected_ham"  => "Неподтвержденный не спам принят",
                                      "suspected_spam" => "Подозреваемый спам в карантин",
                                      "spam"           => "Подтверждение на спам принято",
                                      "virus"          => "Вирусы - принято",
                                      "fp"             => "Сообщения не распознаные как спам",
                                      "fn"             => "Сообщения нераспознаные как не спам",
                                      "wl"             => "Сообщения полученные от отправителей из белого списка",
                                      "bl"             => "Сообщения полученные от отправителей из черного списка",
                                      "bad_header"     => "Сообщения с некорректными почтовыми заголовками",
                                      "banned_file"    => "Сообщения с недозволенными вложениями",
                                      "oversized"      => "Сообщения превышающие лимит на размер");

    $lang['array_arrivals'] =  array("ham"            => "Полученный не спам",
                                      "suspected_ham"  => "Полученный неподтвержденный не спам",
                                      "suspected_spam" => "Полученный подозреваемый спам",
                                      "spam"           => "Полученный подтвержденный спам",
                                      "virus"          => "Полученные вирусы",
                                      "fp"             => "Полученнные ложные срабатывания",
                                      "fn"             => "Ошибки пропущенный спам",
                                      "wl"             => "Полученные из белого списка",
                                      "bl"             => "Полученные из черного списка",
                                      "bad_header"     => "Полученные с плохими заголовками",
                                      "banned_file"    => "Полученные с запрещенными вложениями",
                                      "oversized"      => "Полученные с превышением лимита на размер");

    $lang['array_highest_score'] =  array("ham"            => "Максимальное количество баллов для неспама",
                                      "suspected_ham"  => "Максимальное количество баллов для неподтвержденного неспама",
                                      "suspected_spam" => "Максимальное количество баллов для подозрения на спам",
                                      "spam"           => "Максимальное количество баллов для спам",
                                      "virus"          => "",
                                      "fp"             => "Максимальное количество баллов для ложное стабатывание",
                                      "fn"             => "Максимальное количество баллов для пропущенный спам",
                                      "wl"             => "",
                                      "bl"             => "",
                                      "bad_header"     => "",
                                      "banned_file"    => "",
                                      "oversized"      => "");

    $lang['array_lowest_score'] =  array("ham"            => "Минимальное количество баллов для для неспама",
                                      "suspected_ham"  => "Минимальное количество баллов для неподтвержденного неспама",
                                      "suspected_spam" => "Минимальное количество баллов для подозрения на спам",
                                      "spam"           => "Минимальное количество баллов для спам",
                                      "virus"          => "",
                                      "fp"             => "Минимальное количество баллов для ложное стабатывание",
                                      "fn"             => "Минимальное количество баллов для пропущенный спам",
                                      "wl"             => "",
                                      "bl"             => "",
                                      "bad_header"     => "",
                                      "banned_file"    => "",
                                      "oversized"      => "");

    $lang['array_average_score'] =  array("ham"            => "Среднее количество баллов для для неспама",
                                      "suspected_ham"  => "Среднее количество баллов для неподтвержденного неспама",
                                      "suspected_spam" => "Среднее количество баллов для подозрения на спам",
                                      "spam"           => "Среднее количество баллов для спам",
                                      "virus"          => "",
                                      "fp"             => "Среднее количество баллов для ложное стабатывание",
                                      "fn"             => "Среднее количество баллов для пропущенный спам",
                                      "wl"             => "",
                                      "bl"             => "",
                                      "bad_header"     => "",
                                      "banned_file"    => "",
                                      "oversized"      => "");

    $lang['array_largest_size'] =  array("ham"            => "Максимальное количество писем с неспамом",
                                      "suspected_ham"  => "Максимальное количество писем с неподтвержденным не спамом",
                                      "suspected_spam" => "Максимальное количество писем с подозрением на спам",
                                      "spam"           => "Максимальное количество писем со спамом",
                                      "virus"          => "Максимальное количество писем с вирусами",
                                      "fp"             => "Максимальное количество писем ложные срабатывания",
                                      "fn"             => "Максимальное количество писем пропущенным спамом",
                                      "wl"             => "Максимальное количество писем из белого списка",
                                      "bl"             => "Максимальное количество писем из черного списка",
                                      "bad_header"     => "Максимальное количество писем с плохими заголовками",
                                      "banned_file"    => "Максимальное количество писем с запрещенными вложениями",
                                      "oversized"      => "Максимальное количество писем с превышением размера");

    $lang['array_smallest_size'] =  array("ham"            => "Минимальное количество писем с неспамом",
                                      "suspected_ham"  => "Минимальное количество писем с неподтвержденным не спамом",
                                      "suspected_spam" => "Минимальное количество писем с подозрением на спам",
                                      "spam"           => "Минимальное количество писем со спамом",
                                      "virus"          => "Минимальное количество писем с вирусами",
                                      "fp"             => "Минимальное количество писем ложные срабатывания",
                                      "fn"             => "Минимальное количество писем пропущенным спамом",
                                      "wl"             => "Минимальное количество писем из белого списка",
                                      "bl"             => "Минимальное количество писем из черного списка",
                                      "bad_header"     => "Минимальное количество писем с плохими заголовками",
                                      "banned_file"    => "Минимальное количество писем с запрещенными вложениями",
                                      "oversized"      => "Минимальное количество писем с превышением размера");

    $lang['array_average_size'] =  array("ham"            => "Среднее количество писем с неспамом",
                                      "suspected_ham"  => "Среднее количество писем с неподтвержденным не спамом",
                                      "suspected_spam" => "Среднее количество писем с подозрением на спам",
                                      "spam"           => "Среднее количество писем со спамом",
                                      "virus"          => "Среднее количество писем с вирусами",
                                      "fp"             => "Среднее количество писем ложные срабатывания",
                                      "fn"             => "Среднее количество писем пропущенным спамом",
                                      "wl"             => "Среднее количество писем из белого списка",
                                      "bl"             => "Среднее количество писем из черного списка",
                                      "bad_header"     => "Среднее количество писем с плохими заголовками",
                                      "banned_file"    => "Среднее количество писем с запрещенными вложениями",
                                      "oversized"      => "Среднее количество писем с превышением размера");

    $lang['array_bandwidth'] =  array("ham"            => "Неспам полоса",
                                      "suspected_ham"  => "Полоса неподтвержденного неспама",
                                      "suspected_spam" => "Полоса с подозрением на спам",
                                      "spam"           => "Полоса со спамом",
                                      "virus"          => "Полоса с вирусами",
                                      "fp"             => "Полоса писем с ложными срабатываниями",
                                      "fn"             => "Полоса писем с пропущенным спамом",
                                      "wl"             => "Полоса писем из белого списка",
                                      "bl"             => "Полоса писем из черного списка",
                                      "bad_header"     => "Полоса писем с плохими заголовками",
                                      "banned_file"    => "Полоса писем с запрещенными вложениями",
                                      "oversized"      => "Полоса писем с превышением размера");

    $lang['array_cost'] =  array("ham"            => "Цена неспам полосы",
                                      "suspected_ham"  => "Цена полосы неподтвержденного неспама",
                                      "suspected_spam" => "Цена полосы с подозрением на спам",
                                      "spam"           => "Цена полосы со спамом",
                                      "virus"          => "Цена полосы с вирусами",
                                      "fp"             => "Цена полосы писем с ложными срабатываниями",
                                      "fn"             => "Цена полосы писем с пропущенным спамом",
                                      "wl"             => "Цена полосы писем из белого списка",
                                      "bl"             => "Цена полосы писем из черного списка",
                                      "bad_header"     => "Цена полосы писем с плохими заголовками",
                                      "banned_file"    => "Цена полосы писем с запрещенными вложениями",
                                      "oversized"      => "Цена полосы писем с превышением размера");

    $lang['array_percentage'] =  array("ham"            => "В процентах от всей полученной почты",
                                      "suspected_ham"  => "В процентах от всей полученной почты",
                                      "suspected_spam" => "В процентах от всей полученной почты",
                                      "spam"           => "В процентах от всей полученной почты",
                                      "virus"          => "В процентах от всей полученной почты",
                                      "fp"             => "В процентах от всей полученной почты",
                                      "fn"             => "В процентах от всей полученной почты",
                                      "wl"             => "В процентах от всей полученной почты",
                                      "bl"             => "В процентах от всей полученной почты",
                                      "bad_header"     => "В процентах от всей полученной почты",
                                      "banned_file"    => "В процентах от всей полученной почты",
                                      "oversized"      => "В процентах от всей полученной почты");
?>
