<?php
    // Перевод на русский язык: Айзятуллен Рамиль, http://www.arg.su, argo-uln@yandex.ru
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Настройки доменного почтового фильтра";

    // Table headers
    $lang['header_domain'] =  "Домен";
    $lang['header_admins'] =  "Администратор домена";
    $lang['header_revoke'] =  "Отменить";
    $lang['header_admin_name'] =  "Администратор";
    $lang['header_add_administrator'] =  "Добавить администратора";

    // Text labels
    $lang['text_yes'] =  "Да";
    $lang['text_no'] =  "Нет";
    $lang['text_virus_scanning'] =  "Проверка вирусов";
    $lang['text_enabled'] =  "Включено";
    $lang['text_disabled'] =  "Отключено";
    $lang['text_quarantined'] =  "Карантин";
    $lang['text_discarded'] =  "Отброшено";
    $lang['text_labeled'] =  "Помечено";
    $lang['text_detected_viruses'] =  "Обнаруженные вирусы могут быть...";
    $lang['text_spam_filtering'] =  "Проверка на спам";
    $lang['text_detected_spam'] =  "Обнаруженный спам может быть...";
    $lang['text_prefix_subject'] =  "Добавить префикс спам в тему";
    $lang['text_add_spam_header'] =  "Добавить заголовок X-Spam: баллов ";
    $lang['text_consider_mail_spam'] =  "Считать письмо спамом если баллов";
    $lang['text_quarantine_spam'] =  "Поместить спам в карантин если баллов";
    $lang['text_kill_spam'] =  "Отбросить (без карантина) спам если баллов";
    $lang['text_attachment_filtering'] =  "Проверять типы вложений";
    $lang['text_mail_with_attachments'] =  "Письмо с опасным вложением может быть...";
    $lang['text_bad_header_filtering'] =  "Проверка некорректных заголовков";
    $lang['text_mail_with_bad_headers'] =  "Письма с некорректными заголовками могут быть...";
    $lang['text_settings_updated'] =  "Настройки почтового фильтра обновлены.";
    $lang['text_system_default'] =  "Системные настройки";
    $lang['text_no_admins'] =  "Не выбран администратор для данного домена.";
    $lang['text_no_available_admins'] =  "Нет доступных пользователей для управления этим доменом.";
    $lang['text_administrators_added'] =  "Новый(е) администратор(ы) добавлены к этому домену.";
    $lang['text_admins_revoked'] =  "Привилегии для выбранных администраторов отменены.";
    $lang['text_cache_ham_question'] =  "Сохранять ли сообщения в неспам кеш?";
    $lang['text_enable_user_autocreation'] =  "Включить автосоздание пользователя?";
    $lang['text_domain_theme'] = "Тема по умолчанию для этого домена?";

    // Buttons
    $lang['button_reset'] =  "Сброс";
    $lang['button_update_domain'] =  "Обновить настройки по умолчанию для этого домена";
    $lang['button_revoke'] =  "Отменить привилегии для выбранных администраторов";
    $lang['button_grant'] =  "Предоставить привилегии администратора";

    // Links
    $lang['link_domain_settings'] =  "Вернуться к настройкам домена";
    $lang['link_admin_domains'] =  "Вернуться в меню администратора домена";
?>
