<?php
    // Перевод на русский язык: Айзятуллен Рамиль, http://www.arg.su, argo-uln@yandex.ru
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Карантин";

    // Table headers
    $lang['header_spam'] =  "Подозрение на спам";
    $lang['header_viruses'] =  "Вирусы";
    $lang['header_banned_files'] =  "Запрещенные типы вложений";
    $lang['header_bad_headers'] =  "Некорректные почтовые заголовки";
    $lang['header_quarantine_contents'] =  "Сообщения в карантине";

    // Text labels
    $lang['text_item'] =  "Сообщение";
    $lang['text_items'] =  "Сообщения";
    $lang['text_score'] =  "Баллы";
    $lang['text_received'] =  "Получено";
    $lang['text_from'] =  "От";
    $lang['text_to'] =  "Кому";
    $lang['text_ham'] =  "Не спам?";
    $lang['text_spam'] =  "Спам?";
    $lang['text_rescue'] =  "Не спам!";
    $lang['text_delete'] =  "Удалить";
    $lang['text_subject'] =  "Тема";
    $lang['text_virus'] =  "Вирус";
    $lang['text_file_name'] =  "Имя файла";
    $lang['text_no_subject'] =  "без темы";
    $lang['text_empty'] =  "Ваш карантин пуст.";
    $lang['text_updated'] =  "Ваш карантин обновлен.";
    $lang['text_of'] =  "отключить";
    $lang['text_spam_confirmed'] =  "%d подозрение на спам подтверждено";
    $lang['text_spam_rescued'] =  "%d подозрение на спам не подтверждено, сообщение восстановлено";
    $lang['text_spam_deleted'] =  "%d подозреваемые на спам сообщения удалены";
    $lang['text_viruses_rescued'] =  "%d вирусное сообщение восстановлено";
    $lang['text_viruses_deleted'] =  "%d вирусное сообщение удалено";
    $lang['text_attachments_rescued'] =  "%d файл с запрещенным вложением восстановлен";
    $lang['text_attachments_deleted'] =  "%d файл с запрещенным вложением удален";
    $lang['text_headers_rescued'] =  "%d поврежденное письмо восстановлено";
    $lang['text_headers_deleted'] =  "%d поврежденное письмо удалено";
    $lang['text_suspected_spam_item'] =  "Сообщение подозреваемое на спам";
    $lang['text_suspected_spam_items'] =  "Сообщения подозреваемые на спам";
    $lang['text_virus_item'] =  "Сообщение с вирусом";
    $lang['text_virus_items'] =  "Сообщения с вирусом";
    $lang['text_banned_file_item'] =  "Файл с запрещенным вложением";
    $lang['text_banned_file_items'] =  "Файлы с запрещенными вложениями";
    $lang['text_bad_header_item'] =  "Поврежденное письмо";
    $lang['text_bad_header_items'] =  "Повлежденные письма";
    $lang['text_rescue_error'] = "Не могу восстановить письмо: ";

    // Button text
    $lang['button_confirm_spam'] =  "ВСЕ сообщения в этом списке спам";
    $lang['button_delete_viruses'] =  "Удалить ВСЕ вирусы";
    $lang['button_delete_attachments'] =  "Удалить ВСЕ файлы";
    $lang['button_delete_headers'] =  "Удалить все поврежденные письма";
    $lang['button_confirm'] =  "Подтвердить статус этих писем";
    $lang['button_delete_all_items'] =  "Удалить ВСЕ письма в карантине";

    // Link text
    $lang['link_prev'] =  "Предыдущий";
    $lang['link_next'] =  "Следующий";
    $lang['link_quarantine'] =  "Назад в меню карантина";
    $lang['link_welcome']  = "НАзад в добро пожаловать";

?>
