<?php
    // Перевод на русский язык: Айзятуллен Рамиль, http://www.arg.su, argo-uln@yandex.ru
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Настройка почтового фильтра";

    // Table headers
    $lang['header_addresses'] =  "Почтовый адрес";
    $lang['header_miscellaneous'] =  "Дополнительные параметры";
    $lang['header_address'] =  "Адрес";
    $lang['header_login_info'] =  "Реквизиты доступа";

    // Text messages
    $lang['text_username'] =  "Имя пользователя";
    $lang['text_email_address'] =  "Почтовый адрес";
    $lang['text_password'] =  "Пароль";
    $lang['text_reminders'] =  "Отправлять на почту уведомление о карантине?";
    $lang['text_charts'] =  "Показывать графические диаграммы?";
    $lang['text_yes'] =  "Да";
    $lang['text_no'] =  "Нет";
    $lang['text_virus_scanning'] =  "Проверять на вирусы";
    $lang['text_enabled'] =  "Включено";
    $lang['text_disabled'] =  "Отключено";
    $lang['text_quarantined'] =  "В карантине";
    $lang['text_labeled'] =  "Помечено";
    $lang['text_discarded'] =  "Отвергнуть";
    $lang['text_detected_viruses'] =  "Обнаруженные вирусы нужно...";
    $lang['text_spam_filtering'] =  "Проверять на спам";
    $lang['text_detected_spam'] =  "Обнаруженый спам нужно...";
    $lang['text_prefix_subject'] =  "Добавить префикс о спаме в тему сообщения";
    $lang['text_add_spam_header'] =  "Добавить заголовок X-Spam: Header если баллов";
    $lang['text_consider_mail_spam'] =  "Считать письмо 'Спамом' если баллов";
    $lang['text_quarantine_spam'] =  "Помещать спам в карантин если баллов";
    $lang['text_kill_spam'] =  "Отвергнуть спам (без карантина) если баллов";
    $lang['text_attachment_filtering'] =  "Фильтрация по типам вложений";
    $lang['text_mail_with_attachments'] =  "Письма с опасными вложениями нужно...";
    $lang['text_bad_header_filtering'] =  "Фильтрация плохих заголовков";
    $lang['text_mail_with_bad_headers'] =  "Письма с плохими заголовками нужно...";
    $lang['text_settings_updated'] =  "Настройки почтового фильтра обновлены.";
    $lang['text_address_added'] =  "Адрес %s был привязан к вашей учетной записиt.";
    $lang['text_login_failed'] =  "Ошибочная авторизация для '%s'.";
    $lang['text_primary'] =  "Первичный адрес";
    $lang['text_no_addresses_linked'] =  "Нет адресов привязанных к этой учетной записи.";
    $lang['text_new_primary_email'] =  "%s - это ваш основной почтовый адрес.";
    $lang['text_language'] =  "Язык интерфейса ";
    $lang['text_charset'] =  "Кодировка интерфейса ";
    $lang['text_theme']	= "Тема";
    $lang['text_spamtrap'] =  "Это учетная запись для почтовой ловушки?";
    $lang['text_auto_whitelist'] =  "Добавить отправителя спасенной почты в белый список?";
    $lang['text_items_per_page'] =  "Количество писем на одной странице?";
    $lang['text_digest_interval'] = "Интервал просмотра электронной почты? (-1 для отключения, в минутах)";
    $lang['text_domain_digest_interval'] = "Default Email Digest interval? (-1 для отключения, в минутах)";
    $lang['text_new_login_name'] =  "Новое имя пользователя";
    $lang['text_new_password'] =  "Новый пароль";
    $lang['text_confirm_new_password'] =  "Подтверждение пароля";
    $lang['text_login_name_empty'] =  "Требуется имя пользователя.";
    $lang['text_login_name_not_allowed'] =  "Имя пользователя не может начинаться с '@'.";
    $lang['text_password_empty'] =  "Надо ввести пароль и его подтверждение.";
    $lang['text_password_mismatch'] =  "Пароль и подтверждение должны совпадать.";
    $lang['text_login_name_exists'] =  "Имя пользователя уже используется другим пользователем.";
    $lang['text_password_updated'] =  "Пароль изменен.";
    $lang['text_credentials_updated'] =  "Имя пользователя и пароль изменены.";

    // Buttons
    $lang['button_add_email_address'] =  "Добавить почтовый адрес";
    $lang['button_reset'] =  "Сброс";
    $lang['button_update_misc'] =  "Обновить дополнительные параметры";
    $lang['button_update_address'] =  "Обновить настройки для адреса";
    $lang['button_update_all_addresses'] =  "Обновить ВСЕ настройки для адреса";
    $lang['button_make_primary'] =  "Сделать основным";
    $lang['button_change_login_info'] =  "Обновить реквизиты доступа";

    // Links
    $lang['link_settings'] =  "Назад к странице настроек";
?>
