<?php
    // Перевод на русский язык: Айзятуллен Рамиль, http://www.arg.su, argo-uln@yandex.ru
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Добро пожаловать в систему защиты электронной почты Maia Mailguard!";
    $lang['text_welcome_first_time'] = "Добро пожаловать Maia Mailguard. Это ваш первый вход в систему. Прочтите это сообщение полностью, оно поможет вам понять
                                        важность вашего участия в борьбе со спамом.<P>
                                        Для быстрого включения защиты включите быструю защиту, выбрав уровень защиты в меню и нажав \"Change Level\" (изменить уровень).  Рекомендуем выбрать уровень \"high\" (высокий), он совершенно безопасен.
                                        <P>Maia Mailguard проверяет вашу электронную почту и может заблокировать большинство нежелательных писем от попадания в ваш почтовый ящик.  Если система совершит ошибку, все поправимо.
                                        Maia сохраняет в карантине все ваши письма, карантин доступен на этой странице, вы можете \"восстановить\" сообщения, или \"согласиться\" с системой.  Это также позволит обучать фильтр, когда
                                        есть пропущенный спам, он попадает в \"non-spam cache\" (не спам кеш) как хорошие сообщения.";
    $lang['text_welcome_intro'] = "<p>Боритесь с нежелательной почтой вместе с Mailguard.  Постепенно вы обучите 
                                    Maia лучше различать хорошие письма (не спам) и плохие (спам).  Не спешите нажимать кнопки подтверждая 
                                    чего либо; если у вас нет времени, просто удалите все сообщения не отправляя некорректного 
                                    подтверждения.<p>
                                    Maia может сообщать об письмах подтвержденных вами как спам другим сервисам и службам. Если вы примете участие в процессе обнаружения спама, 
                                    вы поможете в войне со спамом.";
    $lang['text_welcome_current_level'] = "Текущий уровень защиты:"; 
    $lang['text_welcome_custom_level'] = "**Использовать другой уровень:<br>Использовать настройки экрана для настройки, или изменения параметров.";
    $lang['header_cache_contents'] = "Кеш сообщений";
    
    $lang['text_suspected_spam_item']= "Подозрение на спам:";
    $lang['text_suspected_ham_item'] = "Неподтвержденный не спам:";
    $lang['text_virus_item'] =  "Вирусы:";
    $lang['text_banned_file_item'] =  "Недозволенные вложения:";
    $lang['text_bad_header_item'] =  "Поврежденные письма:";
    
    $lang['text_welcome_spam_blocked'] = "Спам собщения были заблокированы";
    $lang['text_welcome_virus_blocked'] = "Вирусы заблокированы";
    $lang['text_welcome_spam_blocked_system'] = "Спам заблокирован системой";
    $lang['text_welcome_virus_blocked_system'] = "Вирусы заблокированы системой";
    $lang['button_delete_all_items'] = "Удалить все сообщения";
    $lang['button_change_protection'] = "Изменить уровень";
    
    $lang['radio_protection'] = array(  'off' => "отключить",
		 								'low' => "низкий",
     									'medium' => "средний",
										'high' => "высокий",
										'custom' => "выборочный");
    
    $lang['banner_subtitle'] = "Добро пожаловать";
    
    $lang['text_cache_spam'] = "У вас <b>%d</b> сообщений в кеше спама.  <br>Нажмите ссылку <a href=\"%s\">here</a> для подтверждения, или для получения ошибочно заблокированного письма.";
    $lang['text_cache_virus'] = "У вас <b>%d</b> сообщений в вирусном кеше.  <br>Нажмите ссылку <a href=\"%s\">here</a> для их удаления, или для получения ошибочно заблокированного письма.";
    $lang['text_cache_banned'] = "У вас <b>%d</b> сообщений в кеше запрещенных вложений.  <br>Нажмите ссылку <a href=\"%s\">here</a> для их удаления, или для получения ошибочно заблокированного письма..";
    
    $lang['text_cache_header'] = "У вас <b>%d</b> сообщений в кеше писем с плохими заголовками.  <br>Нажмите <a href=\"%s\">here</a> для их удаления, или для получения ошибочно заблокированного письма.";
    $lang['text_cache_ham'] = "У вас <b>%d</b> сообщений в неспам кеше.  <br>Нажмите <a href=\"%s\">here</a> для обучения фильтра, или если письмо спам сообщения об этом.";
    $lang['action_ham_cache']   = "Сообщить/Подтвердить";
    $lang['action_spam_cache']  = "Сообщить/Спасти";
    $lang['action_virus_cache'] = "Удалить/Спасти";
    $lang['action_banned_cache'] = "Удалить/Спасти";
    $lang['action_header_cache'] = "Удалить/Спасти";
