<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for brugere of Maia Mailguard
     * ("the Software") who wish til support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * til the Maia Mailguard home page.  Users who wish til remove this
     * branding information should contact the copyright owner til obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers til Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly til the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead til this software,
     *       linking directly til the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Administration: System Konfiguration";

    // Table header
    $lang['header_system_menu'] =  "System Konfiguration";
    $lang['header_charts'] =  "Statistikker";
    $lang['header_reminders'] =  "Mappe udløb &amp; Karantæne Reminders";
    $lang['header_authentication'] =  "Godkendelse";
    $lang['header_virus_info'] =  "Virus Information";
    $lang['header_display'] =  "Vis";
    $lang['header_paths'] =  "Stier &amp; Porte";
    $lang['header_bandwidth'] =  "Båndbredde Pris";
    $lang['header_stats_reporting'] =  "System statistik rapportering";

    // Text labels
    $lang['text_yes'] =  "Ja";
    $lang['text_no'] =  "Nej";
    $lang['text_accept'] =  "Accepteres";
    $lang['text_reject'] =  "Afvises";
    $lang['text_enable_user_autocreation'] =  "Aktiver auto-oprettelse af bruger kontoer?";
    $lang['text_internal_auth'] =  "Auto-send adgangskoder til nye kontoer?";
    $lang['text_enable_false_negative_management'] =  "Aktiver opfølgning på falske negativer?";
    $lang['text_enable_stats_tracking'] =  "Aktiver opfølgning på statistikker?";
    $lang['text_enable_virus_scanning'] =  "Aktiver virus scanning?";
    $lang['text_enable_spam_filtering'] =  "Aktiver spam filtrering?";
    $lang['text_enable_banned_files_checking'] =  "Aktiver blokerede fil vedhæftnings checks?";
    $lang['text_enable_bad_header_checking'] =  "Aktiver checks for ukorrekte mail headers?";
    $lang['text_enable_spamtraps'] =  "Aktiver spam-trap kontoer?";
    $lang['text_enable_charts'] =  "Aktiver grafiske statistikker?";
    $lang['text_enable_address_linking'] =  "Tillad brugere at linke e-mail adresser til deres kontoer?";
    $lang['text_enable_username_changes'] =  "Tillad brugere at ændre deres brugernavn?";
    $lang['text_enable_privacy_invasion'] =  "Tillad administratorere at læse brugere' mail?";
    $lang['text_system_default_user_is_local'] =  "Should the System Default user (@.) only catch mail for local recipients?";
    $lang['text_user_virus_scanning'] =  "Tillad brugere at aktivere/deaktivere virus scanning?";
    $lang['text_user_spam_filtering'] =  "Tillad brugere at aktivere/deaktivere spam filtrering?";
    $lang['text_user_banned_files_checking'] =  "Tillad brugere at aktivere/deaktivere blokerede fil vedhæftnings checks?";
    $lang['text_user_bad_header_checking'] =  "Tillad brugere at aktivere/deaktivere checks for ukorrekte mail headers?";
    $lang['text_size_limit'] =  "Mail størrelse grænse (bytes):";
    $lang['text_oversize_policy'] =  "For store mails skal...";
    $lang['text_admin_email'] =  "Administratorens kontakt email:";
    $lang['text_smtp_server'] =  "Downstream SMTP server (MTA-TX):";
    $lang['text_smtp_port'] =  "Downstream SMTP port nummer:";
    $lang['text_key_file'] =  "Krypterings nøglefil (ikke påkrævet):";
    $lang['text_newuser_template_file'] =  "Skabelons email sendt til nye brugere:";
    $lang['text_chart_ham_colour'] =  "Farve der skal bruges ved visning af bekræftet ikke-spam:";
    $lang['text_chart_spam_colour'] =  "Farve der skal bruges ved visning af bekræftet spam:";
    $lang['text_chart_virus_colour'] =  "Farve der skal bruges ved visning af Vira:";
    $lang['text_chart_fp_colour'] =  "Farve der skal bruges ved visning af falske positiver:";
    $lang['text_chart_fn_colour'] =  "Farve der skal bruges ved visning af falske negativer:";
    $lang['text_chart_suspected_ham_colour'] =  "Farve der skal bruges ved visning af ubekræftet ikke-spam:";
    $lang['text_chart_suspected_spam_colour'] =  "Farve der skal bruges ved visning af formodet spam:";
    $lang['text_chart_wl_colour'] =  "Farve der skal bruges ved visning af godkendte afsendere:";
    $lang['text_chart_bl_colour'] =  "Farve der skal bruges ved visning af blokerede afsendere:";
    $lang['text_chart_background_colour'] =  "Farve der skal bruges til statistik baggrunde:";
    $lang['text_chart_font_colour'] =  "Farve der skal bruges til statistik fonte:";
    $lang['text_chart_autogeneration_interval'] =  "Statistik auto-oprettelses interval (minutter):";
    $lang['text_expiry_period'] =  "Udløbs periode for mails i karantæne (dage):";
    $lang['text_ham_cache_expiry_period'] =  "Udløbs periode for gemte ikke-spam mails (dage):";
    $lang['text_reminder_threshold_count'] =  "Maks emails før reminder (emails):";
    $lang['text_reminder_threshold_size'] =  "Maks størrelse før reminder (størrelse):";
    $lang['text_reminder_template_file'] =  "E-mail reminder skabelons fil:";
    $lang['text_reminder_login_url'] =  "Maia login URL til e-mail reminders:";
    $lang['text_banner_title'] =  "Side-top banner titel:";
    $lang['text_use_icons'] =  "Vis ikoner på værktøjslinien?";
    $lang['text_use_logo'] =  "Vis et logo i top banneret?";
    $lang['text_logo_file'] =  "Billedfil til brug som logo:";
    $lang['text_logo_alt_text'] =  "Alternativ tekst til logoet:";
    $lang['text_logo_url'] =  "URL logoet skal linke til:";
    $lang['text_virus_info_url'] =  "URL skabelon til virus information:";
    $lang['text_virus_lookup'] =  "Virus navn omskrivnings regler:";
    $lang['text_none'] =  "Ingen (ingen opslag)";
    $lang['text_google'] =  "Google Search";
    $lang['text_fprot'] =  "F-Prot";
    $lang['text_fsecure'] =  "F-Secure";
    $lang['text_fsecurejp'] =  "F-Secure Japan";
    $lang['text_sophos'] =  "Sophos";
    $lang['text_nod32'] =  "NOD32";
    $lang['text_norman'] =  "Norman Virus Control";
    $lang['text_trend'] =  "Trend Micro";
    $lang['text_symantec'] =  "Symantec";
    $lang['text_mcafee'] =  "McAfee VirusScan";
    $lang['text_currency_label'] =  "Valuta symbol:";
    $lang['text_bandwidth_cost'] =  "Månedlig pris pr gigabyte sendt/modtaget:";
    $lang['text_enable_stats_reporting'] =  "Aktiver rapportering af system statistikker til Maia Mailguard?";
    $lang['text_primary_report_server'] =  "Primær statistik rapporterings server:";
    $lang['text_primary_report_port'] =  "Port nummer til den primære rapporterings server:";
    $lang['text_secondary_report_server'] =  "Alternativ statistik rapporterings server:";
    $lang['text_secondary_report_port'] =  "Port nummer til den alternative rapporterings server:";
    $lang['text_reporter_sitename'] =  "System navn:";
    $lang['text_reporter_username'] =  "Dit systems Maia Reporter ID:";
    $lang['text_reporter_password'] =  "Dit systems Maia Reporter Password:";

    // Buttons
    $lang['button_submit'] =  "Opdater indstillinger";
    $lang['button_restore'] =  "Nulstil";

    // Links
    $lang['link_admin_menu'] =  "Tilbage til administrations menuen";
?>
