<?php
    /*
     * $Id: adminusers.php,v 1.1.1.1.4.3 2004/09/07 17:34:55 jleaver Exp $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Brugere who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Administration: Brugere";

    // Table headers
    $lang['header_users_menu'] =  "Brugere";
    $lang['header_add_email'] =  "Tilføj ny email adresse/alias";
    $lang['header_link_email'] =  "Link email adresse/alias";
    $lang['header_delete_email'] =  "Slet email adresse/alias";
    $lang['header_delete_user'] =  "Slet brugere";

    // Text messages
    $lang['text_lookup_user'] =  "Søg efter bruger";
    $lang['text_wildcard'] =  "wildcard";
    $lang['text_new_email'] =  "Ny email adresse/alias";
    $lang['text_email'] =  "Email adresse/alias";
    $lang['text_user'] =  "Bruger konto";
    $lang['text_delete_email'] =  "Email adresse/alias";
    $lang['text_address_linked'] =  "Linket %s til bruger %s.";
    $lang['text_address_not_linked'] =  "Fejl: Kan ikke linke en eller flere adresser til bruger kontoer.";
    $lang['text_address_added'] =  "Adressen %s er blevet tilføjet.";
    $lang['text_address_not_added'] =  "Adressen %s kunne IKKe blive tilføjet.";
    $lang['text_address_deleted'] =  "Den markerede email adresse er blevet slettet.";
    $lang['text_address_not_deleted'] =  "En eller flere af de markerede adresser kunne IKKE slettes.";
    $lang['text_user_found'] =  "%ld brugere fundet";
    $lang['text_user_not_found'] =  "Der var ingen brugere der matchede dine kriterier.";
    $lang['text_user_deleted'] =  "Den markerede bruger er blevet slettet.";
    $lang['text_user_not_deleted'] =  "En eller flere af de markerede brugere kunne IKKE slettes.";
    $lang['text_email_subject'] =  "Velkommen til Maia Mailguard";
    $lang['text_email_from'] =  "Maia Mailguard";
    $lang['text_no_users'] =  "Der er ingen brugere tilgængelige";
    $lang['text_no_addresses'] =  "Der er ingen email adresse tilgængelige";


    // Buttons
    $lang['button_lookup'] =  "Find brugere";
    $lang['button_add_email'] =  "Tilføj ny email adresse/alias";
    $lang['button_link_email'] =  "Link email adresse/alias";
    $lang['button_delete_email'] =  "Slet email adresse/alias";
    $lang['button_delete_user'] =  "Slet brugere";

    // Links
    $lang['link_admin_menu'] =  "Tilbage til administrations menuen";
    $lang['link_users_menu'] =  "Tilbage til bruger menuen";
?>
