<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Administration: Hjælp";

    // Table header
    $lang['header_help_menu'] =  "Hjælp";

    // Users
    $lang['adminhelp_find_users'] =  "<b>%s</b> giver dig mulighed for at søge i databasen efter brugere, " .
                                 "hvis navn passer til en søgestreng.  Stjernen '*' " .
                                 "kan bruges som et wildcard som kan udgøre ingenting eller andre " .
                                 "bogstaver, f.eks \"ja*n\" vil matche \"jan\" " .
                                 "såvel som \"jason\".  Søgningen er case-sensitive, så \"jan\" " .
                                 "er forskellig fra \"Jan\".  Dom&aelig;ne administratore vil kun " .
                                 "være i stand til at hente data på brugere som har en email adresse " .
                                 "i de domæner de kontrollere.";

    $lang['adminhelp_add_email_address'] =  "<b>%s</b> giver dig mulighed for at tilføje en ny email adresse til " .
                                        "databasen.  Dette vil oprette en ny bruger " .
                                        ", da en email adresse altid skal være \"ejet\" " .
                                        "af en eller anden.  Navnet på den nye bruger, vil blive sat på " .
                                        "email adressen.  Noter, at hvis du benytter POP3 eller IMAP " .
                                        "bruger godkendelse, bliver den email du angiver her blive " .
                                        "omskrevet så den passer til mailserveren's routnings domæne. " .
                                        "Maia gør dette automatisk, så du skal blot skrive " .
                                        "den \"normale\" e-mail adresse her.";

    $lang['adminhelp_link_email_address'] =  "<b>%s</b> giver dig mulighed for at linke en eksisterende email adresse til " .
                                         "en eksisterende bruger konto.  En email adresse kan kun " .
                                         "tilhører een bruger konto, så opretter man et nyt link vil man " .
                                         "ødelægge et andet link.  Hvis den tidligere ejer " .
                                         "ikke har nogen email adresser tilbage, bliver bruger kontoen slettet " .
                                         "automatisk.  Email adressen bliver overført " .
                                         "til den nye ejers konto. Hvis den tidligere ejers " .
                                         "konto bliver slettet på samme tid, bliver " .
                                         "indholdet af den gamle konto--statistikker, godkendte og blokerede afsender " .
                                         "og mails der måtte være i karantæne smeltet sammen med " .
                                         "den nye ejers konto.";

    $lang['adminhelp_delete_email_address'] =  "<b>%s</b> giver dig mulighed for at fjerne en email adresse fra " .
                                           "systemet.  Noter at man ikke kan slette en brugers primære " .
                                           "email adresse på denne måde. Hvis du ønsker at slette " .
                                           "den primære email adresse, skal du først sætte en anden " .
                                           "adresse som primær for brugeren.  Dette er en sikkerheds foranstaltning " .
                                           "så man ikke kommer til at slette en brugers eneste email adresse. " .
                                           "Hvis du ønsker at slette en bruger helt, benyt " .
                                           "<b>%s</b>, herunder.";

    $lang['adminhelp_delete_user'] =  "<b>%s</b> giver dig mulighed for at slette en bruger konto fra systemet, " .
                                  "sammen med alt dens indhold, statistikker, godkendte og blokerede afsendere, " .
                                  "og alle mails i karantæne for brugeren.  Det vil " .
                                  "også slette alle email adresser tilhørende denne bruger konto. " .
                                  "Noter at hvis <b>%s</b> er aktiveret, vil nye brugere " .
                                  "blive oprettet når der kommer email til kontoer der ikke allerede " .
                                  "eksistere, så sletning af en brugerkonto vil ikke forhindre " .
                                  "samme konto i at blive oprettet igen.";

    $lang['adminhelp_impersonate'] =  "<b>%s</b> vises resultatet af din søgning og giver dig mulighed " .
                                  "for at \"overtage\" enhver listet brugers konto. " .
                                  "Når du klikker på et brugernavn på listen, bliver du \"vedkommende\" " .
                                  "som hvis du lige var logget ind som denne bruger. " .
                                  "Dette giver dig mulighed for at se Maia igennem brugerens ønje og hjælpe " .
                                  "vedkommende med at fejlsøge.  For at afslutte \"brugerovertagelsen\", klik på " .
                                  "%s knappen på værktøjslinien og du er igen dig selv.";

    // Domains
    $lang['adminhelp_domain_administration'] =  "<b>%s</b> viser de domæner du har rettighed " .
                                            "til at administrere. @. domænet " .
                                            "kontrollere system standard indstillingerne, og " .
                                            "kan ikke slettes.  Indstillinger for " .
                                            "andre domæner, tillader dig at konfigurere standard " .
                                            "indstillinger for brugere under disse domæner. Brugere " .
                                            "kan, selvfølgelig, selv overskrive disse indstillinger.";

    $lang['adminhelp_add_domain'] =  "<b>%s</b> giver superadministratoren mulighed for at tilføje et nyt domæne " .
                                 "til systemet, oprettet med standard indstillinger, kopieret fra " .
                                 "system standard (@.) domænet.  For at tildele administratore " .
                                 "til det nye domæne, eller indstille dets standard indstillinger " .
                                 "vælg domænet fra listen herover.";

    $lang['adminhelp_domain_settings'] =  "<b>%s</b> viser de nuværende standard indstillinger " .
                                      "for det valgte domæne. Disse er de samme indstillinger som " .
                                      "brugerne har adgang til for deres individuelle email adresser, " .
                                      "bortset fra, at i dette tilfælde sætter du kun standard " .
                                      "indstillinger, som skal gælde for nye adresser i dette domæne. " .
                                      "Brugere kan overskrive disse standard indstillinger for hver email adresse. " .
                                      "Se nærmere på bruger %s siden for flere detajler om disse indstillinger.";

    $lang['adminhelp_administrators'] =  "<b>%s</b> viser de nuværende administratorer for dette " .
                                     "domæne, hvis der er nogen, og tillader superadministratoren at " .
                                     "tilbagekande administrator privilegier fra en enkelt person, " .
                                     "eller flere personer på samme tid. Superadministratoren, kan selvfølgelig, " .
                                     "administrere <i>alle</i> domæner, og kan ikke få sine " .
                                     "privileger tilbagekaldt (bortset fra hvis kan selv " .
                                     "logger ind på  \"&amp;super=unregister\" siden).";

    $lang['adminhelp_add_administrator'] =  "<b>%s</b> viser en liste over alle brugere " .
                                        "på systemet, som ikke allerede er administrator " .
                                        "for dette domæne, og ikke er superadministrator. " .
                                        "Superadministratoren kan give enhver bruger " .
                                        "administrator privilegier for dette domæne. Brugere kan administrere " .
                                        "lige så mange domæner, som superadministratoren giver privilegier til. " .
                                        "Et domæne kan have flere administratorer.";

    // Virus Aliases
    $lang['adminhelp_virus_aliases'] =  "<b>%s</b> lister virus aliaser og det faktiske virus navn. " .
                                    "Du kan slette ethvert af disse aliaser når som helst, " .
                                    "dog, vil dette ikke tilbageføre aliaset til virus navnet, " .
                                    "eller gendanne dets tidligere statistikker.";


    $lang['adminhelp_add_virus_alias'] =  "<b>%s</b> lader dig gøre et virus navn til et alias for " .
                                      "et andet.  Dette hjælper dig med at administrere virus " .
                                      "statistikker hvis dit system benytter mere end een virus " .
                                      "scanner. Eftersom hver antivirus firma har sin egen " .
                                      "virus-navngivnings standard. Ved at køre flere virus scannere " .
                                      "kan det resultere i dubletter (f.eks. Worm.Klez.H og " .
                                      "Worm/Klez-H@MM).  Ved at lave det ene til et alias for det andet, " .
                                      "lærer Maia at tælle dem som den samme virus.";

    // Languages
    $lang['adminhelp_languages'] =  "<b>%s</b> lister alle installerede sprog " .
                                "Maia Mailguard supportere. Standard sproget " .
                                "(Engelsk) er altid tilgængelig, og kan ikke afinstalleres.";

    $lang['adminhelp_install_languages'] =  "<b>%s</b> giver dig mulighed for at " .
                                        "installere et nyt sprog, og gøre det tilgængeligt for dine brugere. Først, skal du dog " .
                                        "installere sproget, under ./locale/ ved brug af " .
                                        "to-bogstavs ISO-639 sprogkode (f.eks en, da, de, etc.). " .
                                        "Så snart filerne er installere, kan du se det nye sprog på listen.";

    // Themes
    $lang['adminhelp_themes'] =  "<b>%s</b> viser det nuværende aktive tema. Du kan gøre temaer utilgængelige " .
                                    "for brugere, ved a tafinstallere dem her.  Være dog opmærksom på at ".
                                    "hvis en bruger samme tema, som det netop afinstallerede, bliver brugeren tvunget tilbage til standard (@.) " .
                                    "temaet. Bemærk også, at temaet der benyttes af system standard (@.) brugeren " .
                                    "ikke kan afinstalleres, da det benyttes til login skærme. For at ændre " .
                                    "temaet på login skærme, ændre blot temaet i system standard (@.) domænets indstillings side.";

    $lang['adminhelp_install_themes'] =  "<b>%s</b> aktivere temaer, der er blevet udpakket i theme mappen.";

    // System Configuration
    $lang['adminhelp_enable_user_autocreation'] =  "<b>%s</b> tillader Maia selv at oprette nye bruger kontoer " .
                                               "når der kommer email til en lokal bruger, som ikke allerede er registreret " .
                                               "i Maia's database.  Brugernavnet bliver automatisk sat til " .
                                               " email adressen, selvom dette dog bliver erstattet af et " .
                                               "ordenligt brugernavn, første gang brugeren logger på Maia. " .
                                               "Indstillingerne for den nye bruger, bliver taget fra system " .
                                               "standar domænet, (eller det domæne mailadressen nu hører under) " .
                                               "hvis det er tilgængeligt. " .
                                               "Hvis denne feature er deaktiveret, bliver brugere kun oprettet " .
                                               "når de logger ind på Maia. Denne feature skal bruges med " .
                                               "forsigtighed, vær dog sikker på at din mailserver er " .
                                               "sikret imod dictionary angreb før du aktivere denne " .
                                               "feature, ellers vil du se en pokkers masse bruger " .
                                               "kontoer blive oprettet, næste gang en spammer, " .
                                               "prober efter email adresser!";
						

    $lang['adminhelp_internal_auth'] =  "<b>%s</b> giver Maia besked på at generere en 8-karakters adgangskode til nye " .
                                    "brugere og emaile deres midlertidige brugernavn og adgangskode ti ldem. Brugere kan " .
                                    "logge på med disse oplysninger og derefter ændre dem i deres personlige indstillings side.";

    $lang['adminhelp_enable_false_negative_management'] =  "<b>%s</b> giver dig mulighed for at aktivere eller deaktivere " .
                                                       "ikke-spam mappen, hvilket er Maia's måde til at fange " .
                                                       "falske negativer (f.eks spam der er smuttet forbi " .
                                                       "filteret som burde være fanget). Ved at rapportere falske " .
                                                       "negativer og \"bekræfte\" ikke-spam forbedre du " .
                                                       "Maia's spam filter, så du bør aktivere denne " .
                                                       "feature med mindre du virkelig ikke kan undvære " .
                                                       "den harddisk plads til ikke-spam mappen. Noter at " .
                                                       "du kan styre for lang tid emails skal gemmes i ikke-spam mappen " .
                                                       "for at styre dette-- se nærmere på " .
                                                       "<b>%s</b>";

    $lang['adminhelp_enable_stats_tracking'] =  "<b>%s</b> lader dig aktivere eller deaktivere Maia's interne " .
                                            "statistik system. De fleste vil sikkert " .
                                            "lade denne feature være aktiveret, men hvis du hellere vil bruge " .
                                            "3. parts software og hente statistikker fra logfiler, kan du deaktivere featuren her, " .
                                            "og spare nogle ressourcer.";

    $lang['adminhelp_enable_virus_scanning'] =  "<b>%s</b> giver dig mulighed for at aktivere eller deaktivere " .
                                            "antivirus scanning af emails og check for skadelig software for hele systemet.";

    $lang['adminhelp_user_virus_scanning'] =  "<b>%s</b> tillader dig at styre om brugerne selv skal kunne aktivere eller deaktivere antivirus scanning af emails.";

    $lang['adminhelp_enable_spam_filtering'] =  "<b>%s</b> giver dig mulighed for at aktivere eller deaktivere " .
                                            "antispam scanning af emails for hele systemet.";

    $lang['adminhelp_user_spam_filtering'] =  "<b>%s</b> tillader dig at styre om brugerne selv skal kunne aktivere eller deaktivere antispam scanning af emails.";

    $lang['adminhelp_enable_banned_files_checking'] =  "<b>%s</b> giver dig mulighed for at aktivere eller deaktivere " .
                                                   "checks for ukorrekte email headere for hele systemet.";

    $lang['adminhelp_user_banned_files_checking'] =  "<b>%s</b> tillader dig at styre om brugerne selv skal kunne aktivere eller deaktivere " .
                                                 "checkning af emails for blokerede filvedhæng.";

    $lang['adminhelp_enable_bad_header_checking'] =  "<b>%s</b> giver dig mulighed for at aktivere eller deaktivere " .
                                                 "checks for ukorrekte email headere.";

    $lang['adminhelp_user_bad_header_checking'] =  "<b>%s</b> tillader dig at styre om brugerne selv skal kunne aktivere eller deaktivere " .
                                               "checkning af emails med ukorrekte headere.";

    $lang['adminhelp_enable_spamtraps'] =  "<b>%s</b> lader dig kunne aktivere eller deaktivere brugen af spam-trap kontoer " .
                                       "for hele systemet, hvilket kan bruges til at bekræfte al email modtaget " .
                                       "på en given email som spam. Denne feature skal bruges med forsigtighed " .
                                       "og med forståelse for hvordan spam-trap adresse skal (og ikke skal) bruges " .
                                       "så der aldrig sendes legitime emails til en spam-trap adresse. " .
                                       "Formået med en spam-trap er at være lokkemad for automatiserede " .
                                       "adresse høstere, brugt af spammere. Så en spam-trap adresse " .
                                       "må aldrig sende eller modtage legitim email. " .
                                       "Så snart en adresse er markeret af Mia som en spam-trap " .
                                       "vil ejeren af spam-trap'en aldrig modtage nogle af de emails der modtages, " .
                                       "det vil blive modtaget som bekræftet spam, og rapporteret som sådan. " .
                                       "Hvis du ikke stoler på dine brugere, til at bruge denne feature fornuftigt, kan du deaktivere " .
                                       "den her for hele sytemet.";

    $lang['adminhelp_enable_address_linking'] =  "<b>%s</b> tillader dig at styre hvor vidt, brugere skal kunne linke " .
                                             "flere email adresser til een brugerkonto. Selvom denne er deaktiveret " .
                                             "kan administratorer dog stadig linke adresser til bruger kontoer " .
                                             "på Bruger Administrations siden.";

    $lang['adminhelp_enable_username_changes'] =  "<b>%s</b> tillader dig at styre hvor vidt, brugere skal kunne " .
                                              "ændre deres brugernavn. Denne feature virker kun når Maias interne bruger " .
                                               "godkendelses metode bliver benyttet.";

    $lang['adminhelp_enable_privacy_invasion'] =  "<b>%s</b> lader dig styre hvor vidt, administratorer kan " .
                                              "vise emails gemt i brugeres karantæne områder, og ikke-spam mapper, " .
                                              "og læse deres emails. I de fleste situationer, bør denne være deaktiveret " .
                                              "af hensyn til brugernes privatliv, men hvis din " .
                                              "organisation's politikker kræver at du skal kunne checke " .
                                              "folks email, kan du aktivere denne feature.";

    $lang['adminhelp_system_default_user_is_local'] =  "<b>%s</b> determines whether the system default user " .
                                                   "(@.) should only match local e-mail addresses, or " .
                                                   "whether non-local addresses should apply as well.  If " .
                                                   "you allow the system default user to apply to non-local " .
                                                   "addresses, you'll catch outbound mail in this user's " .
                                                   "account.  Most sites will want this set to <b>Yes</b>.";

    $lang['adminhelp_size_limit'] =  "<b>%s</b> specificere størrelsen på den største email du vil " .
                                 "checke for virus m.m. Noter venligst af din database konfiguration " .
                                 "måske skal ændres. (f.eks skal " .
                                 "<b>max_allowed_packet</b> parameteren i MySQL være mindst lige så stor som denne indstillings værdi.).";

    $lang['adminhelp_oversize_policy'] =  "<b>%s</b> bestemmer hvad der skal ske med emails der overskrider størrelse grænsen. " .
                                      "Hvis du sætter denne til <b>%s</b>, for store emails " .
                                      "vil de altid blive forwardet igennem til modtagerens postkasse. " .
                                      "Hvis den sættes til <b>%s</b>, så bliver de afvist, med en fejl " .
                                      "meddelse tilbage til afsender, med en forklaring om årsagen.";

    $lang['adminhelp_installation_directory'] =  "<b>%s</b> fortæller (den absolutte) sti til " .
                                             "mappen hvori Maias PHP scripts er installeret. " .
                                             "Dette gør at Maia kan finde sprog filer og andre plugins.";

    $lang['adminhelp_amavisd_conf'] =  "<b>%s</b> fortæller Maia stien til din amavisd.conf fil, som indeholder konfigurationen til amavisd-new.";

    $lang['adminhelp_admin_email'] =  "<b>%s</b> sætter email adressen, som brugere skal benytte til at kontakte administratoren med.";

    $lang['adminhelp_smtp_server'] =  "<b>%s</b> fortæller Maia, hostnavnet eller IP adressen til den SMTP server Maia " .
                                  "skal bruge til at gensende mails fra karantæne området, og sende email remindere til brugerne.";

    $lang['adminhelp_smtp_port'] =  "<b>%s</b> fortæller Maia portnummeret på SMTP serveren som skal bruges til " .
                                "at gensende mails fra karantæne området og sende email reminders til brugerne. " .
                                "Standard SMTP porten er 25, men i et dual-MTA miljø med en " .
                                "\"input\" eller \"upstream\" port (MTA-RX) og en \"output\" eller " .
                                "\"downstream\" port (MTA-TX), vil du skulle bruge MTA-TX porten, " .
                                "som regel er denne 10025.";

    $lang['adminhelp_key_file'] =  "<b>%s</b> fortæller hvilken fil (inklusiv den fulde sti, eller relativ til din " .
                               "Maia installations mappe) som indeholder Blowfish krypterings nøglen " .
                               "til dit system. Du kan efterlade dette felt blankt, hvis du ikke ønsker " .
                               "at kryptere emails i Maia's database. For at generere en krypteringsnøgle, brug " .
                               "<b>generate-key.pl</b> scriptet og gem outputtet i en fil.";

    $lang['adminhelp_newuser_template_file'] =  "<b>%s</b> fortæller hvilken fil (inklusiv den fulde sti, " .
                                            "eller relativ til din Maia installations mappe) som " .
                                            "Maia skal bruge som skabelon når der genereres " .
                                            "velkomst breve til nye brugere, hvis Maia's interne bruger godkendelses system " .
                                            "bliver benyttet. Denne skabelon " .
                                            "kan indeholde følgende variabler: " .
                                            "<font color=\"red\">%%%%LOGIN%%%%</font>, " .
                                            "<font color=\"red\">%%%%PASSWORD%%%%</font>, " .
                                            "<font color=\"red\">%%%%LOGINURL%%%%</font>, og " .
                                            "<font color=\"red\">%%%%ADMINEMAIL%%%%</font>.";

    $lang['adminhelp_expiry_period'] =  "<b>%s</b> sætter antallet af dage, som formodet spam skal gemmes i " .
                                    "karantæne området, inden de automatisk bliver slettet.  Noter " .
                                    "at når brugere \"bekræfter\" spam, bliver det rapporteret, og derefter slettet, " .
                                    "så denne indstilling er blot til at rydde op i karantæne området, hvis brugeren glemmer det.";

    $lang['adminhelp_ham_cache_expiry_period'] =  "<b>%s</b> sætter antallet af dage, som formodet ikke-spam skal gemmes i " .
                                              "ikke-spam mappen, inden det automatisk bliver slettet. " .
                                              "Noter at når brugere \"bekræfter\" ikke-spam, " .
                                              "bliver det bekræftede ikke-spam slettet, så " .
                                              "denne indstilling er blot til at rydde op i karantæne området, hvis brugeren glemmer det.";

    $lang['adminhelp_reminder_threshold_count'] =  "<b>%s</b> fortæller hvor mange emails der skal være til stede i en brugers karantæne " .
                                               "område, inden der bliver sendt en reminder email, så brugeren " .
                                               "bliver gjort opmærksom på mængden, og kan gøre noget ved det.";

    $lang['adminhelp_reminder_threshold_size'] =  "<b>%s</b> fortæller hvor mange (bytes) data der skal være til stede i en brugers karantæne " .
                                              "område, inden der bliver sendt en reminder email, så brugeren " .
                                              "bliver gjort opmærksom på mængden, og kan gøre noget ved det.";

    $lang['adminhelp_reminder_template_file'] =  "<b>%s</b> fortæller hvilken fil (inklusiv den fulde sti, " .
                                             "eller relativ til din Maia installations mappe) som " .
                                             "Maia skal bruge som skabelon til at generere en reminder email. ".
					     "Denne skabelon indeholder følgende variabler: " .
                                             "<font color=\"red\">%%%%VIRUSCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%SPAMCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%BANNEDCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%HEADERCOUNT%%%%</font>, " .
                                             "<font color=\"red\">%%%%VIRUSSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%SPAMSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%BANNEDSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%HEADERSIZE%%%%</font>, " .
                                             "<font color=\"red\">%%%%MAIAURL%%%%</font>, " .
                                             "<font color=\"red\">%%%%ADMINEMAIL%%%%</font>, " .
                                             "<font color=\"red\">%%%%EXPIRYPERIOD%%%%</font>, " .
                                             "<font color=\"red\">%%%%OLDESTITEMTTL%%%%</font>, og " .
                                             "<font color=\"red\">%%%%OLDESTITEMAGE%%%%</font>.";

    $lang['adminhelp_reminder_login_url'] =  "<b>%s</b> fortæller den URL som brugerne skal sendes til " .
                                         "i de reminder emails de modtager, som opfordre dem til at logge ind og rydde op i deres karantæne område. " .
                                         "Dette kan typisk være dit systems Maia login side.";

    $lang['adminhelp_banner_title'] =  "<b>%s</b> sætter den store tekst der viser sig i den øverste række " .
                                   "på banneret på alle Maia's sider.";

    $lang['adminhelp_use_icons'] =  "<b>%s</b> lader dig vælge imellem grafiske ikoner, eller tekst links i værktøjslinien på " .
                                "alle Maia's sider.";

    $lang['adminhelp_use_logo'] =  "<b>%s</b> lader dig vælge imellem og der skal vises et logo i venstre side af banneret på alle Maia's sider.";

    $lang['adminhelp_logo_file'] =  "<b>%s</b> fortæller stien (relativ til din Maia installation) til " .
                                "den fil som indeholder det logo du ønsker at benytte.";

    $lang['adminhelp_logo_alt_text'] =  "<b>%s</b> fortæller den alternative tekst, der skal vises ved brugere der der benytter " .
                                    "ikke-grafiske browsere.";

    $lang['adminhelp_logo_url'] =  "<b>%s</b> fortæller den URL som besøgende bliver sendt til, når de klikker på logoet. " .
                               "Hvis der ikke skrives noget, bliver der ikke linket til noget.";

    $lang['adminhelp_virus_info_url'] =  "<b>%s</b> lader dig give en URL, som Maia skal bruge til at " .
                                     "give brugere mere information om en bestemt virus. " .
                                     "Variablen \"%%%%VIRUSNAME%%%%\" bliver erstattet af den faktiske virus' navn " .
                                     "som der bliver fundet af din antivirus scanner. Hvis du kun benytter " .
                                     "een virus scanner, prøv og find en URL på producentens hjemmeside " .
                                     "hvor der kan søges efter en virus. En liste med nogle af disse URL'er " .
                                     "kan findes på Maia Mailguards hjemmeside. " .
                                     "Hvis du benytter flere virus scannere, kan det være smartere at benytte Googles søge URL istedet for.";

    $lang['adminhelp_virus_lookup'] =  "<b>%s</b> fortæller Maia hvordan virus navne skal omskrives " .
                                   "når de skal slås op på en antivirus producents hjemmeside. Din virusscanner " .
                                   "finder måske \"Worm.Sobig.F\", f.eks, men producentens hjemmeside forventer måske " .
                                   "\"worm_sobig_f\" eller lignende " .
                                   "i dens URL. Et antal af producent-specifikke omskrivnings regler følger med Maia, " .
                                   "sammen med muligheden for slet ikke at omskrive navnene " .
                                   "Du bør benytte en indstilling der passer med " .
                                   "<b>%s</b> indstillingen, herover.";

    $lang['adminhelp_currency_label'] =  "<b>%s</b> lader dig vælge det symbol Maia skal benytte " .
                                     "til at repræsentere din lokale valuta, når den præsentere pris statistikker. " .
                                     "Dette kan være et specifikt karakter (f.eks \"\$\") eller streng (f.eks \"\$CDN\"), " .
                                     "eller en HTML kode (f.eks \"&amp;euro;\", \"&amp;yen;\", m.m.).";

    $lang['adminhelp_bandwidth_cost'] =  "<b>%s</b> er de månedlige pris det koster pr gigabyte trafik " .
                                     "der sendes og modtages, i hvilken som helst valuta. " .
                                     "Det giver Maia mulighed for at holde styr på hvor meget hver type email koster dig.";

    $lang['adminhelp_enable_stats_reporting'] =  "<b>%s</b> lader Maia rapportere mail statistikker og " .
                                             "renset data fra bekræftet spam til en rapport server, " .
                                             "så Maia's effektivitet kan følges " .
                                             "på et større plan, og andre Maia brugere kan få gavn af disse statistikker. " .
                                             "Statistikker bliver kun sendt for hele systemet, " .
                                             "dvs, der bliver ikke sendt specifikke email adresser, eller andre personlige oplysninger. " .
                                             "Rapport serveren, er kun interresseret i system statistikker, såsom " .
                                             "SpamAssassin regel udløsnings statistikker, og " .
                                             "afsender IP adressen på bekræftet spam og virus mails, " .
                                             "som bruges til at score IP adresser alt efter hvor meget " .
                                             "spam og skadelig software der bliver afsendt fra disse adresser. " .
                                             "Denne liste, med dens konstant opdaterede score, giver Maia " .
                                             "brugere en anden ekstern test der kan køres sammen med " .
                                             "SpamAssassin regler. En eksperimentel feature ved dette er " .
                                             "også at følge hvor tit, en SpamAssassin regel bliver udløst, og " .
                                             "om det resulterede i en forkert tagning af en spam mail eller ikke-spam mail, " .
                                             "dette er muligt, ud fra det dine brugere bekræfter som spam " .
                                             "eller ikke-spam, så SA reglerne kan tweakes oftere.";

    $lang['adminhelp_primary_report_server'] =  "<b>%s</b> sætter hostnavnet eller IP adressen på den " .
                                            "primære Maia rapport server. Dette er typisk " .
                                            "den officelle Maia Mailguard rapporterings server, som " .
                                            "samler rapporter fra Maia installationer fra hele verdenen.";

    $lang['adminhelp_primary_report_port'] =  "<b>%s</b> sætter port nummeret til den primære Maia " .
                                          "rapport server. Maia rapporter er mest sikre når de " .
                                          "bliver sendt over en SSL-beskyttet forbindelse, så dette er typisk " .
                                          "serverens HTTPS port (443 er standard).";

    $lang['adminhelp_secondary_report_server'] =  "<b>%s</b> sætter hostnavnet eller IP adressen på en ekstra " .
                                              "Maia rapport server, hvis der er nogen. Rapporter bliver sendt " .
                                              "til den primære rapport server, og også til denne server, hvis " .
                                              "denne indstilling er sat. Dette giver organisationer mulighed " .
                                              "for at køre deres egen rapporterings server " .
                                              "for f.eks at samle statistikker fra forskellige afdelinger.";

    $lang['adminhelp_secondary_report_port'] =  "<b>%s</b> sætter port nummeret til den sekundære Maia " .
                                            "rapporterings server. Maia rapporter er mest sikre når de " .
                                            "bliver sendt over en SSL-beskyttet forbindelse, så dette er typisk " .
                                            "serverens HTTPS port (443 er standard).";

    $lang['adminhelp_reporter_sitename'] =  "<b>%s</b> sætter navnet på din organisation (som regel jeres " .
                                        "firmanavn) som det skal vises på listen over Maia Reportere.";

    $lang['adminhelp_reporter_username'] =  "<b>%s</b> sætter brugernavnet (Reporter ID) som dit Maia rapporterings " .
                                        "script skal bruge til at godkende sig selv overfor rapporterings serveren. For " .
                                        "at registrere et Reporter ID til dit system gå til denne side: %s.";

    $lang['adminhelp_reporter_registration'] =  "Maia Reporter Registrering";

    $lang['adminhelp_reporter_password'] =  "<b>%s</b> sætter adganggskoden  (Reporter password) som dit Maia rapporterings script skal " .
                                        "bruge til at godkende sig selv overfor rapporterings serveren. Dette " .
                                        "skal være den adgangskode du satte da du registrerede dig som Maia Reporter.";

    $lang['adminhelp_enable_charts'] =  "<b>%s</b> lader dig aktivere eller deaktivere Maia's grafiske statistikker. " .
                                    "Før dette kan virke, skal du selvfølgelig aktivere denne indstilling " .
                                    "<b>%s</b>. Du kan vælge at, statistikkerne bliver genereret når de " .
                                    "bliver efterspurgt af en bruger, eller planlagt genereret, og sendt til dine brugere som " .
                                    "statiske sider.  Se <b>%s</b> for flere detajler.";

    $lang['adminhelp_chart_ham_colour'] =  "<b>%s</b> sætter farven, der skal vise bekræftet ikke-spam emails (f.eks legitime emails) i statistikkerne.";

    $lang['adminhelp_chart_spam_colour'] =  "<b>%s</b> sætter farven der skal vise bekræftet spam emails i statistikkerne.";

    $lang['adminhelp_chart_virus_colour'] =  "<b>%s</b> sætter farven der skal vise vira og andre former for skadelig software i statistikkerne.";

    $lang['adminhelp_chart_fp_colour'] =  "<b>%s</b> sætter farven der skal vise falske positiver i statistikkerne.";

    $lang['adminhelp_chart_fn_colour'] =  "<b>%s</b> sætter farven der skal vise falske negativer i statistikkerne.";

    $lang['adminhelp_chart_suspected_ham_colour'] =  "<b>%s</b> sætter farven der skal vise ubekræftet ikke-spam emails i statistikkerne.";

    $lang['adminhelp_chart_suspected_spam_colour'] =  "<b>%s</b> sætter farven der skal vise formodet spam emails i statistikkerne.";

    $lang['adminhelp_chart_wl_colour'] =  "<b>%s</b> sætter farven der skal vise godkendte afsendere i statistikkerne.";

    $lang['adminhelp_chart_bl_colour'] =  "<b>%s</b> sætter farven der skal vise blokerede afsendere i statistikkerne.";

    $lang['adminhelp_chart_background_colour'] =  "<b>%s</b> sætter baggrunds farven der skal bruges i statistikkerne.";

    $lang['adminhelp_chart_font_colour'] =  "<b>%s</b> sætter farven der skal bruges til skrifttypen i statistikkerne.";

    $lang['adminhelp_chart_autogeneration_interval'] =  "<b>%s</b> lader dig bestemme hvor lang tid der skal gå imellem statistik opdateringer (i minutter) " .
                                                    "Hvis du sætter denne til 0, bliver denne feature deaktiveret, " .
                                                    "og statistikker bliver genereret når de bliver efterspurgt af en bruger. På store systemer " .
                                                    "vil det give mening af auto-generere statistikker i et fast interval " .
                                                    "og lade brugerne se statiske statistikker, eftersom " .
                                                    "at generere statistikkerne dynamisk, kræver en del ressourcer " .
                                                    "og kan sløve dit system en hel del.";




    // Statistics
    $lang['adminhelp_reset_stats'] =  "<b>%s</b> lader dig nulstille Maia's statistik tællere, " .
                                  "inklusiv virus tællere, SpamAssassin rule tællere, og mail " .
                                  "statistikker. Dette vil ikke berører statistikkerne for ubekræftet ikke-spam " .
                                  "eller formodet spam, da disse bliver beregnet direkte fra emails i karantæne.";



?>
