<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Domæne mail filtrerings standarder";

    // Table headers
    $lang['header_domain'] =  "Domæne";
    $lang['header_admins'] =  "Domæne Administratorer";
    $lang['header_revoke'] =  "Tilbagekald";
    $lang['header_admin_name'] =  "Administrator";
    $lang['header_add_administrator'] =  "Tilføj Administrator";

    // Text labels
    $lang['text_yes'] =  "Ja";
    $lang['text_no'] =  "Nej";
    $lang['text_virus_scanning'] =  "Virus Scanning";
    $lang['text_enabled'] =  "Aktiveret";
    $lang['text_disabled'] =  "Deaktiveret";
    $lang['text_quarantined'] =  "Sættes i karantæne";
    $lang['text_discarded'] =  "Slettes";
    $lang['text_labeled'] =  "Markeres";
    $lang['text_detected_viruses'] =  "Fundene virsser skal...";
    $lang['text_spam_filtering'] =  "Spam Filtrering";
    $lang['text_detected_spam'] =  "Fundet spam skal...";
    $lang['text_prefix_subject'] =  "Tilføj et præfix til emnet i spammails";
    $lang['text_add_spam_header'] =  "Tilføj X-Spam: Headere når scoren er";
    $lang['text_consider_mail_spam'] =  "Marker mailen som 'Spam' når scoren er";
    $lang['text_quarantine_spam'] =  "Sæt mailen i karantæne når scoren er";
    $lang['text_kill_spam'] =  "Slet (uden karantæne) spam når scoren er";
    $lang['text_attachment_filtering'] =  "Vedhængs type filtrering";
    $lang['text_mail_with_attachments'] =  "Mails med farlige vedhæng skal...";
    $lang['text_bad_header_filtering'] =  "Ukorrekte header filtrering";
    $lang['text_mail_with_bad_headers'] =  "Mails med ukorrekte headere skal...";
    $lang['text_settings_updated'] =  "Dine mail filtrerings standarder er blevet opdateret.";
    $lang['text_system_default'] =  "Standard indstillinger";
    $lang['text_no_admins'] =  "Der er ikke valgt nogen administrator for dette domæne.";
    $lang['text_no_available_admins'] =  "Der er ingen brugere tilgængelige til adminstration under dette domæne.";
    $lang['text_administrators_added'] =  "Der er blevet tilføjet (en) administrator(ere) til dette domæne.";
    $lang['text_admins_revoked'] =  "De(n) valgte administrator(ere)'s privilegier er blevet tilbagekaldt.";
    $lang['text_cache_ham_question'] =  "Skal ikke-spam mails gemmes??";
    $lang['text_enable_user_autocreation'] =  "Aktiver auto-brugeroprettelse?";
    $lang['text_domain_theme'] = "Standard tema for dette domæne?";

    // Buttons
    $lang['button_reset'] =  "Nulstil";
    $lang['button_update_domain'] =  "Opdater dette domænes standarder";
    $lang['button_revoke'] =  "Tilbagekald privilegier for markerede administratorer";
    $lang['button_grant'] =  "Tildel administrator privilegier";

    // Links
    $lang['link_domain_settings'] =  "Tilbage til domæne indstillingerne";
    $lang['link_admin_domains'] =  "Tilbage til domæne administrations menuen";
?>
