<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Mail Filter Indstillinger";

    // Table headers
    $lang['header_addresses'] =  "Email Adresser";
    $lang['header_miscellaneous'] =  "Diverse Indstillinger";
    $lang['header_address'] =  "Adresse";
    $lang['header_login_info'] =  "Brugernavn &amp; Adgangskode";

    // Text messages
    $lang['text_username'] =  "Brugernavn";
    $lang['text_email_address'] =  "Email adresse";
    $lang['text_password'] =  "Adgangskode";
    $lang['text_reminders'] =  "Send karantæne reminder e-mail?";
    $lang['text_charts'] =  "Vis grafiske statistikker?";
    $lang['text_yes'] =  "Ja";
    $lang['text_no'] =  "Nej";
    $lang['text_virus_scanning'] =  "Virus Scanning";
    $lang['text_enabled'] =  "Aktiveret";
    $lang['text_disabled'] =  "Deaktiveret";
    $lang['text_quarantined'] =  "Sættes i karantæne";
    $lang['text_labeled'] =  "Markeres";
    $lang['text_discarded'] =  "Slettes";
    $lang['text_detected_viruses'] =  "Fundene virsser skal...";
    $lang['text_spam_filtering'] =  "Spam Filtrering";
    $lang['text_detected_spam'] =  "Fundet spam skal...";
    $lang['text_prefix_subject'] =  "Tilføj et præfix til emnet i spammails";
    $lang['text_add_spam_header'] =  "Tilføj X-Spam: Headere når scoren er";
    $lang['text_consider_mail_spam'] =  "Marker mail som 'Spam' når scoren er";
    $lang['text_quarantine_spam'] =  "Sæt spammail i karantæne når scoren er";
    $lang['text_kill_spam'] =  "Slet spam (uden karantæne) når scoren er";
    $lang['text_attachment_filtering'] =  "Filvedhængs filtrering";
    $lang['text_mail_with_attachments'] =  "Mails med farlige filvedhæng skal....";
    $lang['text_bad_header_filtering'] =  "Ukorrekt header filtering";
    $lang['text_mail_with_bad_headers'] =  "Mails med ukorrekte headere skal...";
    $lang['text_settings_updated'] =  "Dine mail filtrerings indstillinger er blevet opdateret.";
    $lang['text_address_added'] =  "Adressen %s er blevet linket til din konto.";
    $lang['text_login_failed'] =  "Brugergodkendelse fejlede for '%s'.";
    $lang['text_primary'] =  "Primær adresse";
    $lang['text_no_addresses_linked'] =  "Ingen adresser er blevet linket til din konto.";
    $lang['text_new_primary_email'] =  "%s er nu din primære email adresse.";
    $lang['text_language'] =  "Vis sprog";
    $lang['text_charset'] =  "Vis karaktersæt";
    $lang['text_theme']	= "Tema";
    $lang['text_spamtrap'] =  "Er en spam-trap konto?";
    $lang['text_auto_whitelist'] =  "Tilføj afsendere af reddet emails til dine godkendte afsendere?";
    $lang['text_items_per_page'] =  "Antal emails der skal vises pr side?";
    $lang['text_digest_interval'] = "Email Digest interval? (0 to deactivate, in hours)";
    $lang['text_domain_digest_interval'] = "Default Email Digest interval? (0 to deactivate, in hours)";
    $lang['text_new_login_name'] =  "Nyt brugernavn";
    $lang['text_new_password'] =  "Ny adgangskode";
    $lang['text_confirm_new_password'] =  "Bekræft ny adgangskode";
    $lang['text_login_name_empty'] =  "Der kræves et brugernavn.";
    $lang['text_login_name_not_allowed'] =  "Brugernavne kan ikke starte med '@'.";
    $lang['text_password_empty'] =  "En adgangskode og dets bekræftelse skal angives.";
    $lang['text_password_mismatch'] =  "Adgangskoden og bekræftelsen passer ikke sammen.";
    $lang['text_login_name_exists'] =  "Brugernavnet du har bedt om er allerede i brug.";
    $lang['text_password_updated'] =  "Din adgnagskode er belvet ændret.";
    $lang['text_credentials_updated'] =  "Dit brugernavn og din adgangskode er blevet ændret.";

    // Buttons
    $lang['button_add_email_address'] =  "Tilføj email adresse";
    $lang['button_reset'] =  "Nulstil";
    $lang['button_update_misc'] =  "Opdater diverse indstillinger";
    $lang['button_update_address'] =  "Opdater denne adresses indstillinger";
    $lang['button_update_all_addresses'] =  "Opdater ALLE adressers indstillinger";
    $lang['button_make_primary'] =  "Sæt som primær";
    $lang['button_change_login_info'] =  "Opdater dine brugeroplysninger";

    // Links
    $lang['link_settings'] =  "Tilbage til dine indstillinger";
?>
