<?php
    /*
     * $Id: adminusers.php,v 1.1.2.1 2004/09/07 19:29:05 jleaver Exp $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Administrasjon: Brukere";

    // Table headers
    $lang['header_users_menu'] =  "Brukere";
    $lang['header_add_email'] =  "Legg til ny epost adresse/alias";
    $lang['header_link_email'] =  "Link epost adresse/alias";
    $lang['header_delete_email'] =  "Slett epost adresse/alias";
    $lang['header_delete_user'] =  "Slett brukere";

    // Text messages
    $lang['text_lookup_user'] =  "Finn bruker";
    $lang['text_wildcard'] =  "wildcard";
    $lang['text_new_email'] =  "Ny epost adresse/alias";
    $lang['text_email_subject'] =  "Velkommen til Egroup Mailvask";
    $lang['text_email'] =  "Epost adresse/alias";
    $lang['text_user'] =  "Brukerkonto";
    $lang['text_delete_email'] =  "Epost adresse/alias";
    $lang['text_address_linked'] =  "Linket %s til bruker %s.";
    $lang['text_address_not_linked'] =  "Klarte ikke å linke en eller flere adresser til brukerkontoer.";
    $lang['text_address_added'] =  "Adresse %s har blitt lagt til.";
    $lang['text_address_not_added'] =  "Adresse %s kunne IKKE bli lagt til.";
    $lang['text_address_deleted'] =  "Den valgte epost adresse har blitt slettet.";
    $lang['text_address_not_deleted'] =  "En eller flere av de valgte adressene kunne IKKE bli slettet.";
    $lang['text_user_found'] =  "%ld brukere funnet";
    $lang['text_user_not_found'] =  "Ingen brukere som stemte med ditt søk ble funnet.";
    $lang['text_user_deleted'] =  "De valgte brukerene har blitt slettet.";
    $lang['text_user_not_deleted'] =  "En eller flere av de valgte brukerene kunne IKKE bli slettet.";
    $lang['text_email_subject'] =  "En ny Egroup Mailvask konto har blitt opprettet for deg";
    $lang['text_email_from'] =  "Egroup Mailvask";
    $lang['text_no_users'] =  "Ingen brukere er tilgjengelig";
    $lang['text_no_addresses'] =  "Ingen epost adresser er tilgjengelig";


    // Buttons
    $lang['button_lookup'] =  "Finn brukere";
    $lang['button_add_email'] =  "Legg til ny epost adresse/alias";
    $lang['button_link_email'] =  "Link epost adresse/alias";
    $lang['button_delete_email'] =  "Slett epost adresse/alias";
    $lang['button_delete_user'] =  "Slett brukere";

    // Links
    $lang['link_admin_menu'] =  "Tilbake til Administratjonsmenyen";
    $lang['link_users_menu'] =  "Tilbake til Brukermenyen";
?>
