<?php
    /*
     * $Id: welcome.php 538 2004-12-30 17:50:47Z dmorton $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Velkommen til Maia Mailguard!";
    $lang['text_welcome_first_time'] = "Velkommen til Maia Mailguard. Jeg ser dette er første gange du har logget inn. Vennligst les hele denne beskjed, siden det vil hjelpe deg å forstå
                                        viktigheten av din hjelp for å stoppe spam.<P>
                                        Først: for å skru på spam beskyttelse raskt, velg et nivå nedenfor og klikk på \"Endre nivå\".  Level \"Høy\" er helt trygg og anbefalt.
                                        <P>Maia Mailguard kan filtere din e-post og kan hindre mesteparten av uønsket innhold fra å havne i din innboks.  Hvis den gjør en feil, så er ikke innholdet tapt.
                                        Maia kan sette din e-mail i karantene, tilgjengelig på denne siden, som du kan \"redde\", eller \"rapportere\".  Det gir deg også mulighet til å trene opp filteret
                                        når en spam mail slipper igjennom, ved å fra din \"ham-cache\" - en samling av de siste e-postene som er antatt ønsket e-post.";
    $lang['text_welcome_intro'] = "<p>Ta aksjon mot uønsket e-post med Maia Mailguard.  Når en e-post er listet i rubrikken nederst til høyre så kan du
                                    trene filteret til å se forskjell mellom ønsket e-post (ham) og uønsket e-post (spam).  Ta deg tid for å være sikker på at 
                                    alle meldinger blir rapportert korrekt; hvis du ikke har tid til dette, vennligst slett alle meldingene i stedet for å rapportere dem 
                                    feil.<p>
                                    Husk at Maia kan og vil rapportere meldinger brekftet som spam til andre anti-spam tjenester.  Ved å delta aktivt i rapporteringsprosessen, 
                                    så kan du hjelpe til i kampen mot spam.";
    $lang['text_welcome_current_level'] = "Gjeldene beskyttelsesnivå:"; 
    $lang['text_welcome_custom_level'] = "**Egendefinert nivå er i bruk:<br>Bruk innstillinger siden for å endre, eller velg et forhåndsdefinert nedenfor.";

    $lang['text_welcome_spam_blocked'] = "SPAM meldinger har blitt blokkert for deg";
    $lang['text_welcome_virus_blocked'] = "Viruser har blitt blokkert for deg";
    $lang['text_welcome_spam_blocked_system'] = "Spam meldinger blokkert globalt";
    $lang['text_welcome_virus_blocked_system'] = "Viruser blokkert globalt";
    $lang['button_delete_all_items'] = "Slett alle meldinger";
    $lang['button_change_protection'] = "Endre nivå";
    
    $lang['radio_protection'] = array(  'off' => "Av",
		 								'low' => "Lav",
     									'medium' => "Medium",
										'high' => "Høy",
										'custom' => "Egendefinert");
    
    $lang['banner_subtitle'] = "Velkommen";
    
    $lang['text_cache_spam'] = "Du har <b>%d</b> meldinger i din spam cache.  <br>Klikk <a href=\"%s\">her</a> for å rapportere, eller for å
        redde en melding som ble feilaktig blokkert.";
    $lang['text_cache_virus'] = "Du har <b>%d</b> meldinger i din virus cache.  <br>Klikk <a href=\"%s\">her</a> for å slette, eller for å
        redde en melding som ble feilaktig blokkert.";
    $lang['text_cache_banned'] = "Du har <b>%d</b> meldinger i din sperrede filtyper cache.  <br>Klikk <a href=\"%s\">her</a> for å slette, eller for å
        redde en melding som ble feilaktig blokkert.";
    
    $lang['text_cache_header'] = "Du har <b>%d</b> meldinger i din feil-header cache.  <br>Klikk <a href=\"%s\">her</a> for å slette, eller for å
        redde en melding som ble feilaktig blokkert.";
    $lang['text_cache_ham'] = "Du har <b>%d</b> meldinger i din ham cache.  <br>Klikk <a href=\"%s\">her</a> for å hjelpe til å trene opp filteret, eller
        for å rapportere en spam melding som ble oversett.";
    $lang['action_ham_cache']   = "Rapportere/Bekrefte";
    $lang['action_spam_cache']  = "Rapportere/Redde";
    $lang['action_virus_cache'] = "Slette/Redde";
    $lang['action_banned_cache'] = "Slette/Redde";
    $lang['action_header_cache'] = "Slette/Redde";
    
    

