<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Administration: Systemkonfiguration";

    // Table header
    $lang['header_system_menu'] =  "Systemkonfiguration";
    $lang['header_charts'] =  "Diagram";
    $lang['header_reminders'] =  "Cache-förfallotid &amp; Karantänkomihåg";
    $lang['header_authentication'] =  "Auktorisation";
    $lang['header_virus_info'] =  "Virusinformation";
    $lang['header_display'] =  "Visning";
    $lang['header_paths'] =  "Sökvägar &amp; portar";
    $lang['header_bandwidth'] =  "Bandbreddsberäkning";
    $lang['header_stats_reporting'] =  "Statistikrapportering för sajt";

    // Text labels
    $lang['text_yes'] =  "Ja";
    $lang['text_no'] =  "Nej";
    $lang['text_accept'] =  "Accepteras";
    $lang['text_reject'] =  "Refuseras";
    $lang['text_enable_user_autocreation'] =  "Aktivera automatiskt skapande av nya användarkonton?";
    $lang['text_internal_auth'] =  "Skapa automatiskt lösenord till nya konton?";
    $lang['text_enable_false_negative_management'] =  "Aktivera spårning av falska negativa?";
    $lang['text_enable_stats_tracking'] =  "Aktivera spårning av statistik?";
    $lang['text_enable_virus_scanning'] =  "Aktivera virusskanning?";
    $lang['text_enable_spam_filtering'] =  "Aktivera spam-filtrering?";
    $lang['text_enable_banned_files_checking'] =  "Aktivera kontroll av förbjudna bilagor?";
    $lang['text_enable_bad_header_checking'] =  "Aktivera kontroll av felaktiga brevhuvuden?";
    $lang['text_enable_spamtraps'] =  "Aktivera spam-fångarkonton?";
    $lang['text_enable_charts'] =  "Aktivera grafiska diagram?";
    $lang['text_enable_address_linking'] =  "Tillåt anändarna att länka emejladresser till sina konton?";
    $lang['text_enable_username_changes'] =  "Tillåt användarna att ändra sina användarnamn?";
    $lang['text_enable_privacy_invasion'] =  "Tillåt administratörer att hantera användarnas mejl";
    $lang['text_system_default_user_is_local'] =  "Skall systemets standardanvändare (@.) bara fånga mejl för lokala mottagar?";
    $lang['text_user_virus_scanning'] =  "Tillåt användare att slå på/av virusskanning?";
    $lang['text_user_spam_filtering'] =  "Tillåt användare att slå på/av spam-filtrering?";
    $lang['text_user_banned_files_checking'] =  "Tillåt användare att slå på/av kontroll av förbjudna bilagor?";
    $lang['text_user_bad_header_checking'] =  "Tillåt användare att slå på/av kontroll av felaktiga brevhuvuden?";
    $lang['text_size_limit'] =  "Mejl storleksbegränsning (bytes):";
    $lang['text_oversize_policy'] =  "Mejl som är förstora skall...";
    $lang['text_installation_directory'] =  "Maia installationsmapp:";
    $lang['text_admin_email'] =  "Administratörens emejladress för kontakt:";
    $lang['text_smtp_server'] =  "Nedströms SMTP-server (MTA-TX):";
    $lang['text_smtp_port'] =  "Nedströms SMTP-portnummer:";
    $lang['text_key_file'] =  "Fil för krypteringsnyckel (valfritt):";
    $lang['text_newuser_template_file'] =  "Mallfil för mejl som sänds till nya användare:";
    $lang['text_chart_ham_colour'] =  "Färg för att visa bekräftad icke-spam:";
    $lang['text_chart_spam_colour'] =  "Färg för att visa bekräftad spam:";
    $lang['text_chart_virus_colour'] =  "Färg för att visa virus:";
    $lang['text_chart_fp_colour'] =  "Färg för att visa falska positiva:";
    $lang['text_chart_fn_colour'] =  "Färg för att visa falska negativa:";
    $lang['text_chart_suspected_ham_colour'] =  "Färg för att visa misstänkt icke-spam:";
    $lang['text_chart_suspected_spam_colour'] =  "Färg för att visa misstänkt spam:";
    $lang['text_chart_wl_colour'] =  "Färg för att visa 'white'-listade mejl:";
    $lang['text_chart_bl_colour'] =  "Färg för att visa svartlistade mejl:";
    $lang['text_chart_background_colour'] =  "Färg för att visa diagrambakgrund:";
    $lang['text_chart_font_colour'] =  "Färg för att visa diagramteckensnitt:";
    $lang['text_chart_autogeneration_interval'] =  "Intervall för av diagram (minuter):";
    $lang['text_expiry_period'] =  "Förfallotid för mejl i karantän (dagar):";
    $lang['text_ham_cache_expiry_period'] =  "Förfallotid för mejl i icke-spam-cache (dagar):";
    $lang['text_reminder_threshold_count'] =  "Gräns för komihågmejl (antal):";
    $lang['text_reminder_threshold_size'] =  "Gräns för komihågmejl (storlek):";
    $lang['text_reminder_template_file'] =  "Mallfil för komihågmejl:";
    $lang['text_reminder_login_url'] =  "Maia inloggnings-URL för komihågmejl:";
    $lang['text_banner_title'] =  "Titel i sidhuvudet:";
    $lang['text_use_icons'] =  "Visa ikoner i sidhuvudets verktygsfält?";
    $lang['text_use_logo'] =  "Visa en logga i sidhuvudet?";
    $lang['text_logo_file'] =  "Bildfil att använda som logga:";
    $lang['text_logo_alt_text'] =  "Alternativ text för loggan:";
    $lang['text_logo_url'] =  "URL som loggan länkar till:";
    $lang['text_virus_info_url'] =  "URL-mall för virusinformation:";
    $lang['text_virus_lookup'] =  "Omskrivningsregler för virusnamn:";
    $lang['text_none'] =  "Inga (inga sökningar)";
    $lang['text_google'] =  "Google-sökning";
    $lang['text_fprot'] =  "F-Prot";
    $lang['text_fsecure'] =  "F-Secure";
    $lang['text_fsecurejp'] =  "F-Secure Japan";
    $lang['text_sophos'] =  "Sophos";
    $lang['text_nod32'] =  "NOD32";
    $lang['text_norman'] =  "Norman Virus Control";
    $lang['text_trend'] =  "Trend Micro";
    $lang['text_symantec'] =  "Symantec";
    $lang['text_mcafee'] =  "McAfee VirusScan";
    $lang['text_currency_label'] =  "Valutasymbol:";
    $lang['text_bandwidth_cost'] =  "Bandbredd månadskostnad per gigabyte:";
    $lang['text_enable_stats_reporting'] =  "Aktivera rapportering av sajtstatistik?";
    $lang['text_primary_report_server'] =  "Primär statistikrapporteringsserver:";
    $lang['text_primary_report_port'] =  "Portnummer för primär rapportserver:";
    $lang['text_secondary_report_server'] =  "Sekundär statistikrapporteringsserver:";
    $lang['text_secondary_report_port'] =  "Portnummer för sekundär rapportserver:";
    $lang['text_reporter_sitename'] =  "Namn på din sajt:";
    $lang['text_reporter_username'] =  "Din sajts Maia-rapporterings-ID:";
    $lang['text_reporter_password'] =  "Din sajts Maia-rapporteringslösenord:";

    // Buttons
    $lang['button_submit'] =  "Uppdatera inställningar";
    $lang['button_restore'] =  "Återställ formulär";

    // Links
    $lang['link_admin_menu'] =  "Återvänd till Administrationsmeny";
?>
