<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Domänmejlfilter Standardinställningar";

    // Table headers
    $lang['header_domain'] =  "Domän";
    $lang['header_admins'] =  "Domänadministratörer";
    $lang['header_revoke'] =  "Återkalla";
    $lang['header_admin_name'] =  "Administratör";
    $lang['header_add_administrator'] =  "Lägg till Administratör";

    // Text labels
    $lang['text_yes'] =  "Ja";
    $lang['text_no'] =  "Nej";
    $lang['text_virus_scanning'] =  "Virusskanning";
    $lang['text_enabled'] =  "Aktiverad";
    $lang['text_disabled'] =  "Deaktiverad";
    $lang['text_quarantined'] =  "I karantän";
    $lang['text_discarded'] =  "Kastas";
    $lang['text_labeled'] =  "Namnges";
    $lang['text_detected_viruses'] =  "Detekterade virus skall ...";
    $lang['text_spam_filtering'] =  "Spam-filtrering";
    $lang['text_detected_spam'] =  "Detekterad spam skall ...";
    $lang['text_prefix_subject'] =  "Lägg till prefix till ämnet på mejl innehållande spam";
    $lang['text_add_spam_header'] =  "Lägg till X-Spam: i brevhuvud när poäng är ";
    $lang['text_consider_mail_spam'] =  "Anse mejl som 'Spam' när poängen är ";
    $lang['text_quarantine_spam'] =  "Sätt spam i karantän när pängen är ";
    $lang['text_attachment_filtering'] =  "Bilagetypsfiltrering";
    $lang['text_mail_with_attachments'] =  "Mejl med farliga bilagor skall ...";
    $lang['text_bad_header_filtering'] =  "Filtrering av felaktigt brevhuvud";
    $lang['text_mail_with_bad_headers'] =  "Mejl med felaktigt brevhuvud skall ...";
    $lang['text_settings_updated'] =  "Din standard för mejlfiltrering har uppdaterats.";
    $lang['text_system_default'] =  "Systemstandard";
    $lang['text_no_admins'] =  "Ingen administratör har valts för denna domän.";
    $lang['text_no_available_admins'] =  "Inga användare tillgängliga för att administrera denna domän.";
    $lang['text_administrators_added'] =  "Ny(a) administratör(er) har lagts till i denna domän.";
    $lang['text_admins_revoked'] =  "De valda adminstratörernas rättigheter har återkallats.";
    $lang['text_cache_ham_question'] =  "Skall icke-spam-mejl cache:as?";
    $lang['text_enable_user_autocreation'] =  "Aktivera automatiskt skapande av användarkonton?";
    $lang['text_domain_theme'] = "Standardtema för denna domän?";
 
    
    // Buttons
    $lang['button_reset'] =  "Återställ";
    $lang['button_update_domain'] =  "Uppdatera denna domäns standardinställningar";
    $lang['button_revoke'] =  "Återkalla Administratörsprivilegier för markerade administratörer";
    $lang['button_grant'] =  "Tilldela Administratörsprivilegier";

    // Links
    $lang['link_domain_settings'] =  "Återvänd till Domäninställningarna";
    $lang['link_admin_domains'] =  "Återvänd till Domänadministrationsmenyn";
?>
