<?php
    /*
     * $Id: welcome.php 631 2005-05-03 19:19:22Z jleaver $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Välkommen till Maia Mailguard!";
    $lang['text_welcome_first_time'] = "Välkommen till Maia Mailguard!. Jag ser att det är första gången som du har loggat in. Var snäll och läs detta meddelande från början till slut eftersom det hjälper dig förstå
                                        nödvändigheten av ditt deltagande i att stoppa spammet.<P>
                                        Först av allt, för att aktivera spam-skyddet snabbt, välj en nivå nedan och klicka på \"Byt nivå\".  \"Hög\" nivå är säkert och rekommenderat.
                                        <P>Maia Mailguard kan filtrera dina mejl, och blockera det mesta av det oönskade innehållet som hamnar i din inkorg.  Om den gör ett misstag är inte allt förlorat.
                                        Maia kan sätta dina mejl i karantän och du når dem från den här sidan, för att kunna \"rädda\", eller \"raportera\" till myndigheter.  Det tillåter dig även att träna filtret när ett
                                        spam slinker igenom, genom att rapportera från din \"icke-spam cache\" - en samling av de senast inkomna mejlen som anses vara goda mejl.";
    $lang['text_welcome_intro'] = "<p>Gör motstånd mot det ökade inslagen av oönskade mejl med Maia Mailguard.  När ett mejl är listat i det nedre högra fönstret kan du
                                    träna Maia med avseende på skillnaden mellan goda mejl (icke-spam) och oönskade mejl (spam).  Var snäll och ta tid på dig så du är säker på att 
                                    alla mejl raporteras korrekt; om du inte har tid att göra jobbet, var snäll och radera alla mejl istället för att rapportera dem 
                                    inkorrekt.<p>
                                    Kom ihåg att, Maia kan och vill rapportera mejl bekräftade som spam till andra tjänster och myndigheter.  Genom att hålla igång rapporteringsprocessen, 
                                    du  hjälpa till i kampen mot spam.";
    $lang['text_welcome_current_level'] = "Nuvarande säkerhetsnivå:"; 
    $lang['text_welcome_custom_level'] = "**Egna inställningar används:<br>Använd inställningar för att hantera, eller välja en förinställd nivå ovan.";

    $lang['text_welcome_spam_blocked'] = "SPAM-mejl har blockerats för dig";
    $lang['text_welcome_virus_blocked'] = "Virus har blockerats för dig";
    $lang['text_welcome_spam_blocked_system'] = "SPAM-mejl har blockerats i systemet";
    $lang['text_welcome_virus_blocked_system'] = "Virus har blockerats i systemet";
    $lang['button_delete_all_items'] = "Radera alla poster";
    $lang['button_change_protection'] = "Byt nivå";
    
    $lang['radio_protection'] = array(  'off' => "Av",
		 								'low' => "Låg",
     									'medium' => "Medel",
										'high' => "Hög",
										'custom' => "Egen");
    
    $lang['banner_subtitle'] = "Välkommen";
    
    $lang['text_cache_spam'] = "Du har <b>%d</b> mejl i din spam-cache.  <br>Klicka <a href=\"%s\">här</a> för att rapportera dem, eller för att rädda ett mejl som av misstag har blockerats.";
    $lang['text_cache_virus'] = "Du har <b>%d</b>  mejl i din virus-cache.  <br>Klicka <a href=\"%s\">här</a> för att radera dem, eller för att rädda ett mejl som av misstag har blockerats.";
    $lang['text_cache_banned'] = "Du har <b>%d</b> mejl i din förbjudna filer-cache.  <br>Klicka <a href=\"%s\">här</a>  för att radera dem, eller för att rädda ett mejl som av misstag har blockerats.";
    
    $lang['text_cache_header'] = "Du har <b>%d</b> mejl i din felaktiga header-cache.  <br>Klicka <a href=\"%s\">här</a> för att radera dem, eller för att rädda ett mejl som av misstag har blockerats.";
    $lang['text_cache_ham'] = "Du har <b>%d</b> mejl i din Icke-spam-cache.  <br>Klicka <a href=\"%s\">här</a> för att hjälpa med att träna filtret, eller för att träna ett spam-mejl som har missats.";
    $lang['action_ham_cache']   = "Rapportera/Bekräfta";
    $lang['action_spam_cache']  = "Rapportera/Rädda";
    $lang['action_virus_cache'] = "Radera/Rädda";
    $lang['action_banned_cache'] = "Radera/Rädda";
    $lang['action_header_cache'] = "Radera/Rädda";
