<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Definições do Filtro de Email";

    // Table headers
    $lang['header_addresses'] =  "Endereços de Email";
    $lang['header_miscellaneous'] =  "Definições Diversas";
    $lang['header_address'] =  "Endereço";
    $lang['header_login_info'] =  "Credenciais de Autenticação";

    // Text messages
    $lang['text_username'] =  "Nome de utilizador";
    $lang['text_email_address'] =  "Endereço de email";
    $lang['text_password'] =  "Palavra passe";
    $lang['text_reminders'] =  "Enviar email de lembrete de quarentena?";
    $lang['text_charts'] =  "Exibir gráficos?";
    $lang['text_yes'] =  "Sim";
    $lang['text_no'] =  "Não";
    $lang['text_virus_scanning'] =  "Verificação de Vírus";
    $lang['text_enabled'] =  "Activa";
    $lang['text_disabled'] =  "Inactiva";
    $lang['text_quarantined'] =  "posto em quarentena";
    $lang['text_labeled'] =  "Etiquetado";
    $lang['text_discarded'] =  "Apagado";
    $lang['text_detected_viruses'] =  "Vírus detectados devem ser...";
    $lang['text_spam_filtering'] =  "Filtragem de Spam";
    $lang['text_detected_spam'] =  "Spam detectado deve ser...";
    $lang['text_prefix_subject'] =  "Adicionar um prefixo ao assunto de mensagens de spam";
    $lang['text_add_spam_header'] =  "Adicionar cabeçalhos X-Spam: quando a Pontuação é";
    $lang['text_consider_mail_spam'] =  "Considerar email 'Spam' quando a Pontuação é";
    $lang['text_quarantine_spam'] =  "Colocar Spam em quarentena quando a Pontuação é";
    $lang['text_kill_spam'] =  "Apagar Spam (sem quarentena) quando a Pontuação é";
    $lang['text_attachment_filtering'] =  "Filtragem de tipo de Anexo";
    $lang['text_mail_with_attachments'] =  "Email com anexos perigosos devem ser...";
    $lang['text_bad_header_filtering'] =  "Filtragem de Cabeçalhos Inválidos";
    $lang['text_mail_with_bad_headers'] =  "Email com cabeçalhos inválidos deve ser...";
    $lang['text_settings_updated'] =  "As suas definições do filtro de email foram actualizadas.";
    $lang['text_address_added'] =  "O endereço %s foi associado à sua conta.";
    $lang['text_login_failed'] =  "A autenticação falhou para '%s'.";
    $lang['text_primary'] =  "Endereço Primário";
    $lang['text_no_addresses_linked'] =  "Não existem endereços associados a esta conta.";
    $lang['text_new_primary_email'] =  "%s é agora o seu endereço de email primário.";
    $lang['text_language'] =  "Linguagem";
    $lang['text_charset'] =  "Codificação de Caracteres";
    $lang['text_theme']	= "Tema";
    $lang['text_spamtrap'] =  "Esta é uma conta de spam-trap?";
    $lang['text_auto_whitelist'] =  "Adicionar recipientes de email resgatado à sua lista de acesso?";
    $lang['text_items_per_page'] =  "Items de email a serem exibidos por página?";
    $lang['text_digest_interval'] = "Intervalo entre Resumo de Emails? (0 para desactivar, em horas)";
    $lang['text_new_login_name'] =  "Novo nome de utilizador";
    $lang['text_new_password'] =  "Nova palavra passe";
    $lang['text_confirm_new_password'] =  "Confirmar nova palavra passe";
    $lang['text_login_name_empty'] =  "É necessário um nome de utilizador.";
    $lang['text_login_name_not_allowed'] =  "Nomes de utilizador não podem começar com '@'.";
    $lang['text_password_empty'] =  "Uma password e sua confirmação devem ser introduzidas.";
    $lang['text_password_mismatch'] =  "A password e a confirmação não coincidem.";
    $lang['text_login_name_exists'] =  "O nome de utilizador que indicou já está em uso por outro utilizador.";
    $lang['text_password_updated'] =  "A sua password foi alterada";
    $lang['text_credentials_updated'] =  "O seu nome de utilizador e password foram alteradas.";

    // Buttons
    $lang['button_add_email_address'] =  "Adicionar Endereço de Email";
    $lang['button_reset'] =  "Limpar";
    $lang['button_update_misc'] =  "Actualizar Definições Diversas";
    $lang['button_update_address'] =  "Actualizar Definições deste Endereço";
    $lang['button_update_all_addresses'] =  "Actualizar Definições de TODOS os Endereços";
    $lang['button_make_primary'] =  "Fazer Primário";
    $lang['button_change_login_info'] =  "Actualizar Credenciais de Autenticação";

    // Links
    $lang['link_settings'] =  "Voltar à página das suas Definições";
?>
