<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Bem-vindo ao Maia Mailguard!";
    $lang['text_welcome_first_time'] = "Bem-vindo ao Maia Mailguard. Parece ser a primeira vez que se autenticou. Por favor leia a seguinte mensagem até ao fim, porque o ajudará a compreender
                                        a importância da sua participação para ajudar a parar o spam.<P>
                                        Para activar a protecção de spam rapidamente, basta escolher um nível abaixo e clicar em \"Mudar Nível\". O nível \"alto\" é perfeitamente seguro e recomendado.
                                        <P>O Maia Mailguard pode filtrar o seu email, e consegue bloquear grande parte do conteúdo indesejado antes de este chegar à sua caixa de entrada. Se porventura se enganar, nem tudo está perdido.
                                        O Maia pode colocar sob quarentena o seu email, acessível nesta página, para você poder \"resgatar\" ou \"reportar\" às autoridades. Também permite que você treine o filtro quando um item de spam 
                                        é entregue, reportando-o através da sua  \"cache não-spam\" - um registo de emails recentes identificados como emails válidos.";
    $lang['text_welcome_intro'] = "<p>Faça algo contra a proliferação de email indesejado com Maia Mailguard. Quando o email é listado na caixa abaixo à direita, você pode
                                    treinar o Maia para distinguir entre email válido (não-spam) e email indesejado (spam).  Por favor verifique que todos os items são reportados 
                                    correctamente; se não tiver tempo para o fazer, por favor opte por eliminar todos os items em em vez de os reportar incorrectamente.<p>                                    
                                    Não se esqueça, Maia pode e irá reportar items confirmados como spam a outros serviços e autoridades. Através da sua colaboração no processo de reporte, 
                                    você está a ajudar na guerra contra o spam.";
    $lang['text_welcome_current_level'] = "Nível de protecção actual:"; 
    $lang['text_welcome_custom_level'] = "**Nível personalizado em uso:<br>Utilize o ecrâ de definições para geri-lo, ou seleccione um nível pré-configurado acima.";

    $lang['text_welcome_spam_blocked'] = "Items de Spam foram bloqueados para si";
    $lang['text_welcome_virus_blocked'] = "Vírus foram bloqueados para si";
    $lang['text_welcome_spam_blocked_system'] = "Items de Spam bloqueados em todo o sistema";
    $lang['text_welcome_virus_blocked_system'] = "Vírus bloqueados em todo o sistema";
    $lang['button_delete_all_items'] = "Eliminar todos os items";
    $lang['button_change_protection'] = "Mudar nível";
    
    $lang['radio_protection'] = array(  'off' => "Desligado",
		 								'low' => "Baixo",
     									'medium' => "Médio",
										'high' => "Alto",
										'custom' => "Personalizado");
    
    $lang['banner_subtitle'] = "Bem-vindo";
    
    $lang['text_cache_spam'] = "Você tem <b>%d</b> items na sua cache de spam.  <br>Clique <a href=\"%s\">aqui</a> para reportá-los, ou para resgatar uma mensagem bloqueada por engano.";
    $lang['text_cache_virus'] = "Você tem <b>%d</b> items na sua cache de vírus.  <br>Clique <a href=\"%s\">aqui</a> para removê-los, ou para resgatar uma mensagem bloqueada por engano.";
    $lang['text_cache_banned'] = "Você tem <b>%d</b> items na sua cache de ficheiros banidos.  <br>Clique <a href=\"%s\">aqui</a> para removê-los, ou para resgatar uma mensagem bloqueada por engano.";
    
    $lang['text_cache_header'] = "Você tem <b>%d</b> items na sua cache de cabeçalhos inválidos.  <br>Clique <a href=\"%s\">aqui</a> para removê-los, ou para resgatar uma mensagem bloqueada por engano.";
    $lang['text_cache_ham'] = "Você tem <b>%d</b> items na sua cache não-spam.  <br>Clique <a href=\"%s\">aqui</a> para ajudar a treinar o filtro, ou para reportar uma mensagem que não foi assinalada.";
    $lang['action_ham_cache']   = "Reportar/Confirmar";
    $lang['action_spam_cache']  = "Reportar/Resgatar";
    $lang['action_virus_cache'] = "Eliminar/Resgatar";
    $lang['action_banned_cache'] = "Eliminar/Resgatar";
    $lang['action_header_cache'] = "Eliminar/Resgatar";
