<?php
    /*
     * $Id: xadminlanguages.php 1439 2009-11-17 23:31:04Z dmorton $
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     *                   David Morton   <mortonda@dgrmm.net>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    require_once ("core.php");
    require_once ("maia_db.php");
    require_once ("authcheck.php");

    // Only the superadministrator should be here.
    if (!is_superadmin($uid)) {
       header("Location: index.php" . $sid);
       exit();
    }

    // Find out which button we pushed to get here
    if (isset($_POST["install"])) {

    	$lang_abbrev = strtolower(trim($_POST["language"]));

    	// Make sure the language files are actually installed
        $lang_dir = getcwd();
        if (preg_match("/.*\/$/si", $lang_dir)) {
            $lang_dir .= "locale";
        } else {
    	    $lang_dir .= "/locale";
        }
        $d = dir($lang_dir);

        // Check if language is already in database
        $select = "SELECT language_name, abbreviation, id " .
                  "FROM maia_languages " .
                  "WHERE abbreviation = ?";

        $sth = $dbh->prepare($select);
        $res = $sth->execute($lang_abbrev);
        if (PEAR::isError($sth)) {
            die($sth->getMessage());
        }

        // Make the language available to users
        if($res->numrows()) {
            if (is_dir($lang_dir . "/" . $lang_abbrev)) {
                $update = "UPDATE maia_languages SET installed = 'Y' WHERE abbreviation = ?";
                $sth = $dbh->prepare($update);
                $res = $sth->execute($lang_abbrev);
                if (PEAR::isError($sth)) {
                    die($sth->getMessage());
                }
            }
            $d->close();
        } else {
            if (is_dir($lang_dir . "/" . $lang_abbrev)) {
                if(file_exists($lang_dir . "/" . $lang_abbrev . "/name")) {
                    $lang_name = file_get_contents($lang_dir . "/" . $lang_abbrev . "/name");
                } else {
                    $lang_name = "N/A";
                }
                $insert = "INSERT INTO maia_languages (language_name, abbreviation, installed) VALUES (?, ?, 'Y')";
                $sth = $dbh->prepare($insert);
                $res = $sth->execute(array($lang_name, $lang_abbrev));
                if (PEAR::isError($sth)) {
                    die($sth->getMessage());
                }
            }
            $d->close();
        }

    } elseif (isset($_POST["uninstall"])) {

        // Register the full set of POST variables.
        foreach($_POST as $varname => $value)
        {
            $formVars[$varname] = trim($value);
        }

        // Don't allow the default language to be removed
        $select = "SELECT language_name, abbreviation, id " .
                  "FROM maia_languages " .
                  "WHERE installed = 'Y' AND abbreviation <> ?";
        $sth = $dbh->prepare($select);
        $res = $sth->execute(array(strtolower($default_display_language)));
        if (PEAR::isError($sth)) {
            die($sth->getMessage());
        }

        while ($row = $res->fetchrow()) {

            $lang_name = $row["language_name"];
            $lang_abbrev = strtolower($row["abbreviation"]);
            $lang_id = $row["id"];

            if (isset($formVars[$lang_abbrev]) && trim($formVars[$lang_abbrev]) == $lang_id) {
                    // Make this language unavailable to users
                $update = "UPDATE maia_languages SET installed = 'N' WHERE id = ?";


                $sth = $dbh->prepare($update);
                $res = $sth->execute($lang_id);
                if (PEAR::isError($sth)) {
                    die($sth->getMessage());
                }

                // Reset all users who used this language to the default
        	    $update = "UPDATE maia_users SET language = ? WHERE language = ?";


                $sth = $dbh->prepare($update);
                $res = $sth->execute(array($default_display_language, $lang_abbrev));
                if (PEAR::isError($sth)) {
                    die($sth->getMessage());
                }
                $_SESSION["display_language"] = $default_display_language;
            }
        }

        $res->free();

    }

    // Return to the language administration page
    header("Location: adminlanguages.php" . $sid);
    exit();
?>
