<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     *                   Motoharu Kubo  <mkubo@3ware.co.jp>
     *                   Oyaji          <oyaji@mail.aconus.com>
     * All rights reserved.
     *
     * Fri Jul 22 2016 YAMAMOTO Takashi <yamachan@piwikjapan.org>
     * - Checked for version 1.0.4
     * 
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Maia Mailguard へようこそ!";
    $lang['text_welcome_first_time'] = 
"あなたはこれがはじめてのログインですね。" .
"スパムとウィルスを遮断するために、このメッセージをよく読んでください。<p>まず最初に、保護レベルを設定してください。高レベルがお勧めです。" .
"保護レベルを選んだら「レベルを変更する」をクリックして、Maia Mailguard によるフィルタリングをスタートしましょう<p>" .
"スパムのチェックは非常に複雑で、Maia Mailguard が間違った判定を行うことがあります。しかし心配はいりません。Maia Mailguard はスパムと判断したメールを隔離エリアに保存します。" .
"この画面から隔離エリアのメールにアクセスできます。間違ってスパムと判定されてしまったメールは隔離エリアから救出できます。" .
"また、スパムなのに誤って配送されてしまうこともありえます。このような場合には、[すり抜けたスパムを報告]をクリックして、誤配送されたスパムを Maia Mailguard に学習させることができます。";

    $lang['text_welcome_intro'] =
"Maia Mailguard を上手に活用して、スパムとウィルスを排除しましょう。<p>" .
"「隔離エリアと履歴」の各カテゴリをチェックしてください。" .
"時間が取れるなら、隔離エリアのメールを個々にチェックして、" .
"スパムかどうかの最終判断を行ってください。" .
"Maia Mailguard はあなたの判断結果にもとづいて学習を積み重ねます。" .
"詳細にチェックする余裕がないときは、誤判定されたメールの救出などの必要な作業だけを行い、" .
"残りのメールは全部破棄してください。<p>" .
"システム設定によっては、あなたが判定したスパムの情報は、" .
"インターネット上の互助組織にも送られ、スパム情報の整備に使われます。" .
"この結果は次のスパム判定に生かされることになります。";

    $lang['text_welcome_current_level'] = "現在の保護レベル:"; 
    $lang['text_welcome_custom_level'] = "**保護レベルをカスタマイズしています。<br><b>設定</b>メニューで保護レベルを確認するか、上記の保護レベルのどれかを選んでください。";

    $lang['text_welcome_spam_blocked_prefix'] = "${user_name} さんの"; //unused
    $lang['text_welcome_spam_blocked'] = "通のスパムをブロック（あなた）";
    $lang['text_welcome_virus_blocked_prefix'] = "${user_name} さんの"; //unused
    $lang['text_welcome_virus_blocked'] = "通のウィルスメールをブロック（あなた）";
    $lang['text_welcome_spam_blocked_system_prefix'] = "システム全体で"; // unused
    $lang['text_welcome_spam_blocked_system'] = "通のスパムをブロック（全体）";
    $lang['text_welcome_virus_blocked_system_prefix'] = "システム全体で"; //unused
    $lang['text_welcome_virus_blocked_system'] = "通のウィルスメールをブロック（全体）";
    $lang['button_delete_all_items'] = "すべて破棄する";
    $lang['button_change_protection'] = "レベルを変更する";
    
    $lang['radio_protection'] = array(  'off' => "オフ",
		 								'low' => "低レベル",
     									'medium' => "中レベル",
										'high' => "高レベル",
										'custom' => "カスタム");
    
    $lang['banner_subtitle'] = "隔離エリアのサマリー";
    
    $lang['text_cache_spam'] = "スパムと思われるメールが <b>%d</b> 通隔離されています。<br><a href=\"%s\">ここをクリックして、</a>スパムと認定するか、誤って隔離されているなら救出してください。";
    $lang['text_cache_virus'] = "ウィルス感染メールが <b>%d</b> 通隔離されています。<br><a href=\"%s\">ここをクリックして、</a>破棄するか、どうしても必要なら救出してください。";
    $lang['text_cache_banned'] = "危険な添付ファイルが付いたメールが <b>%d</b> 通隔離されています。<br><a href=\"%s\">ここをクリックして、</a>破棄するか、どうしても必要なら救出してください。";

    $lang['text_cache_header'] = "不正なヘッダがあるメールが <b>%d</b> 通隔離されています。<br><a href=\"%s\">ここをクリックして、</a>破棄するか、どうしても必要なら救出してください。";
    $lang['text_cache_ham'] = "スパムではないと判断されたメールの履歴が <b>%d</b> 通記録されています。<br><a href=\"%s\">ここをクリックして、</a>すり抜けたスパムがあったかどうか、Maia Mailguard に教えてください。";
    $lang['action_ham_cache']   = "すり抜けたスパムを報告";
    $lang['action_spam_cache']  = "確認・救出";
    $lang['action_virus_cache'] = "破棄と救出";
    $lang['action_banned_cache'] = "破棄・救出";
    $lang['action_header_cache'] = "破棄・救出";
?>